### PR TITLE
Mainmenu: Fix error after ESC in dialog windows

### LINKED ISSUE #16115: fields.te_port is nil.
### Luanti version

```true
Luanti 5.12.0-dev-486fb7cc4-dirty (Linux)
Using LuaJIT 2.1.1741730670
Built by GCC 15.1
Running on Linux/6.13.12 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Operating system and version

Arch Linux x86_64

### CPU model

AMD Ryzen 7 7730U (16) @ 4.55 GHz

### GPU model

AMD Barcelo [Integrated]

### Active renderer

4.6 / opengl / SDL 2.32.56

### Summary

2025-05-06 15:37:18: ERROR[Main]: Main menu error: Runtime error from mod '??' in callback handleMainMenuButtons(): ...r/Projects/luanti/bin/../builtin/mainmenu/tab_online.lua:539: attempt to index field 'te_port' (a nil value)
2025-05-06 15:37:18: ERROR[Main]: stack traceback:
2025-05-06 15:37:18: ERROR[Main]: 	...r/Projects/luanti/bin/../builtin/mainmenu/tab_online.lua:539: in function 'handle_buttons'
2025-05-06 15:37:18: ERROR[Main]: 	/home/user/Projects/luanti/bin/../builtin/fstk/ui.lua:138: in function 'handle_buttons'
2025-05-06 15:37:18: ERROR[Main]: 	/home/user/Projects/luanti/bin/../builtin/fstk/ui.lua:182: in function </home/user/Projects/luanti/bin/../builtin/fstk/ui.lua:168>

### Steps to reproduce

Supply wrong password when joining a server, after you get the "Invalid Password" dialog error, click escape.

### PR DESCRIPTION
**Pull request by SmallJoker**
The error was caused by fd857374, where 'MenuQuit' was processed after 'try_quit'. This commit fixes the error by moving the special 'MenuQuit' handling to Lua.

Fixes #16115 

## To do

This PR is Ready for Review.

## How to test

1. Enter a wrong password in the server list
2. Close the "access denied" dialogue by ESC
3. No error
4. Ensure there's no error for other dialogues.

### CODE REVIEW

File: builtin/fstk/ui.lua [hunk 1]
```diff
@@ -166,6 +166,14 @@ end
 --------------------------------------------------------------------------------
 --------------------------------------------------------------------------------
 core.button_handler = function(fields)
+	if fields["try_quit"] then
+		for name, value in pairs(ui.childlist) do
+			if value.type == "toplevel" and name ~= ui.default then
+				core.event_handler("MenuQuit")
+				return
+			end
+		end
```
Comment (grorp) [inline builtin/fstk/ui.lua:175]: why those extra checks before forwarding it to `core.event_handler`? this was a "global" event before already, `core.event_handler` should handle it correctly regardless of what dialog/tab/etc. is open.

Comment (grorp) [reply builtin/fstk/ui.lua:175]: also, the extra checks break exiting the mainmenu entirely with ESC

**Comment by grorp** [comment]
also, with this PR, pressing Enter while nothing is focused will close mainmenu dialogs

**Comment by SmallJoker** [comment]
> this PR breaks the ability to exit the mainmenu entirely with ESC

I thought this was a bug. Did that change recently, and willingly? I'll fix this.

> with this PR, pressing Enter while nothing is focused will close mainmenu dialogs

Is there any way to differentiate between ESC and Enter?

File: builtin/fstk/ui.lua (hunk 1 above)
Comment (SmallJoker) [reply builtin/fstk/ui.lua:175]: The difference now is that there's an additional `try_quit` event sent to the main menu which triggers a server list refresh. Thus, using the `try_quit` event to generate `MenuQuit` seems to be the most reasonable approach.

File: builtin/fstk/ui.lua [hunk 2]
```diff
@@ -166,6 +166,10 @@ end
 --------------------------------------------------------------------------------
 --------------------------------------------------------------------------------
 core.button_handler = function(fields)
+	if fields["try_quit"] and not fields["key_enter"] then
```
Comment (grorp) [inline builtin/fstk/ui.lua:169]: the `not fields["key_enter"]` approach is slightly hacky. instead of only including the "<kbd>ESC</kbd> pressed" case like previously, we're now excluding one case and including all others.

I think the one other case we might be including here now (that wasn't included before) is this:

https://github.com/luanti-org/luanti/blob/c2b9be5160215c61acbfe6df27f97c66170eddf3/src/gui/guiFormSpecMenu.cpp#L4033-L4039

seems acceptable to me though

**Review by grorp — APPROVED** [review]
