### PR TITLE
Move keybinding settings to (Lua-based) setting menu

### LINKED ISSUE #3847: In-game controls configuration does not detect collisions wth minetest.conf-only or hardcoded keys
The controls configuration menu is able to (kinda) detect key collisions with keys displayed on the page and displays a warning. For instance, if I make both forwards and backwards use the W key, the warning is shown.

However, the same warning is not used when either a hardcoded key is used or a key which can only be configured with minetest.conf.
For instance, if I assign F1 to anything, no warning is shown, but this is of course the default key for HUD hiding.
Also, you can assign Esc to any action but this has no effect, probably since Esc is very deeply hardcoded into Minetest. IMO the Esc key should not be assignable to anything (at least in the GUI, minetest.conf is an entirely different beast) to keep things simple.

Revision: 0d2df732e5c5075cd8848b9a9530865430630bfe

### LINKED ISSUE #4211: Being able to use middle Mouse button (button 3 aka scroll wheel) for controls
It's impossible to use button 3 (scroll wheel button) as a control (I like to assign Crouch to it)

### LINKED ISSUE #9602: Allow using the delete key as a keybinding
## Problem

You can no longer bind the delete key

## Solutions

Use a button/the currently bound key instead of the delete key to delete a binding

## Additional context
Had someone complaining on Discord recently. They use the arrow keys for movement, and delete for sneaking.

### LINKED ISSUE #11209: Redo change keys dialog
The key config menu has a lot of problems:

* The code behind this menu is ancient and has been updated significantly in ages
* Strange, ancient warning: “If this menu screws up, delete stuff from minetest.conf”
* All the text in this menu is very crammed in a tiny space, making it hard to translate
* It doesn't support theming/styling
* This menu seems to be one of the few menus of the main menu that is *not* implemented in Lua
* Can't unbind keys
* Can't bind mouse buttons
* Doesn't show all keys

There are so many problems that I suggest a complete redo of this menu. Requested features:

* Implement this in Lua
* Add theming support
* Replace the crammed pseudotable format with a scrollable list
* Expose ALL the rebindable keys (#10927)
* Separate the list of key actions into sections like Movement, Camera, Graphics, etc.
* Remove the strange warning (#8064)
* When clicking to change a key, open a small window to prompt input. Keypress will register as a key. Add clickable buttons for the mouse buttons, deleting the keybind (#9602) and aborting
* Add a button to revert everything to default
* Make sure the detection of key conflicts always works (#3847)

Please post your own suggestions and comments.

### LINKED ISSUE #15729: Cinematic Camera is not in the keybindings menu
### Luanti version

```true
Luanti 5.10.0 (Linux)
Using LuaJIT 2.1.1731486438 (OpenResty)
Built by GCC 14.2
Running on Linux/6.12.10 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/app/share/luanti"
STATIC_LOCALEDIR="/app/share/locale"
```

### Operating system and version

Arch Linux (flatpak)

### CPU model

irrelevant

### GPU model

irrelevant

### Active renderer

OpenGL 4.6

### Summary

I can't find the option to set the key for toggling cinematic mode in the keybindings menu. As it is still in `keys.h` and the cinematic camera smoothing setting still exists, I guess this feature isn't EOL. 

### Steps to reproduce

1. Open luanti
2. Open keybindings menu
3. See this (note there is no cinematic camera):

Image

### PR DESCRIPTION
**Pull request by y5nw**
https://github.com/luanti-org/luanti/pull/15614#issuecomment-2569715077

Alternative to #15152.

Due to merge conflicts, please merge this _after_ #14964.

- Goal of the PR
  This PR removes the dedicated settings menu for keybindings and instead adds the keybinding settings to the "Keyboard and mouse" section in the settings menu.
- How does the PR work?
  This PR introduces a `button_key` formspec element for capturing key inputs. This element is used in the Lua-based settings menu.
  The `aux1_descends`, `doubletap_jump`, and `autojump` options (which were also included in the keybinding form) can be found in "Controls" -> "General".
- Does it resolve any reported issue?
  - Fixes #11209
  - Fixes #15729
  - Fixes #9602
  - Fixes #3847
  - Fixes #4211
- Does this relate to a goal in [the roadmap](https://github.com/luanti-org/luanti/blob/master/doc/direction.md)?
  2.3 UI Improvements.

## To do

This PR is ready for review.

- [x] Implement `button_key` element.
  - [x] Send event on release instead of on press.
- [x] Add button to delete keybinding.
- [x] Implement setting callback.
- ~~Add sections to the keybinding list.~~
- [x] Implement checks for keybinding collisions.

## How to test
See #15152.

### CODE REVIEW

File: src/gui/guiButtonKey.cpp [hunk 1]
```diff
@@ -0,0 +1,93 @@
+#include "guiButtonKey.h"
```
Comment (SmallJoker) [inline src/gui/guiButtonKey.cpp:1]: Please add the SPDX header. Also feel free to add your own name as copyright holder.

File: src/gui/guiButtonKey.h [hunk 2]
```diff
@@ -0,0 +1,80 @@
...
+	{
+		return key_value;
+	}
+
+private:
+	void sendKey();
+
+	bool capturing = false;
+	KeyPress key_value = {};
+	std::wstring keysym;
```
Comment (SmallJoker) [inline src/gui/guiButtonKey.h:79]: I would prefer to use the `m_ ` prefix for these variables. I find it very helpful to see the scope of a variable within a function without having to rely on IDE features (which might also require interactions to reveal this information).

Although it seems that the code style guidelines make it seem optional? In this case I'll leave the decision to you.

File: builtin/common/settings/components.lua [hunk 3]
```diff
@@ -442,6 +442,51 @@ local function make_noise_params(setting)
...
+						core.formspec_escape(defaulttexturedir .. "clear.png"),
+						btn_clear),
+			}
+			local height = 0.8
+			if value ~= "" then
+				for _, o in pairs(core.full_settings) do
+					if o.type == "key" and o.name ~= setting.name and core.settings:get(o.name) == value then
+						table.insert(fs, ("label[0,%f;%s]"):format(height+0.3,
+								fgettext("Keybinding conflict: $1", o.readable_name)))
+						height = height+0.6
```
Comment (SmallJoker) [inline builtin/common/settings/components.lua:471]: Formspec escape + translation. Also a few stylistic changes:
```suggestion
						table.insert(fs, ("label[0,%f;%s]"):format(height + 0.3,
								fgettext("Keybinding conflict: $1", fgettext(o.readable_name))
						))
						height = height + 0.6
```
To reduce indent levels, you could consider to offload this loop to a separate local function.

File: builtin/settingtypes.txt [hunk 4]
```diff
@@ -158,6 +158,229 @@ enable_hotbar_mouse_wheel (Hotbar: Enable mouse wheel for selection) bool true
 #    Requires: keyboard_mouse
 invert_hotbar_mouse_wheel (Hotbar: Invert mouse wheel direction) bool false
 
+#    Key for moving the player forward.
```
Comment (SmallJoker) [inline builtin/settingtypes.txt:161]: Might an additional `Requires: keyboard_mouse` be needed for these settings?

File: builtin/common/settings/components.lua [hunk 5]
```diff
@@ -442,6 +442,51 @@ local function make_noise_params(setting)
...
+			local btn_bind_width = math.max(2.5, avail_w/2)
+			local value = core.settings:get(setting.name)
+			local fs = {
+				("label[0,0.4;%s]"):format(get_label(setting)),
+				("button_key[%f,0;%f,0.8;%s;%s]"):format(
+						btn_bind_width, btn_bind_width-0.8,
+						btn_bind, core.formspec_escape(value)),
+				("image_button[%f,0;0.8,0.8;%s;%s;]"):format(avail_w - 0.8,
+						core.formspec_escape(defaulttexturedir .. "clear.png"),
+						btn_clear),
```
Comment (SmallJoker) [inline builtin/common/settings/components.lua:463]: Please add a tooltip for this button to clarify what exactly it does.

File: builtin/common/settings/components.lua [hunk 6]
```diff
@@ -442,6 +442,51 @@ local function make_noise_params(setting)
...
+	return {
+		info_text = setting.comment,
+		setting = setting,
+
+		get_formspec = function(self, avail_w)
+			self.resettable = core.settings:has(setting.name)
+			local btn_bind_width = math.max(2.5, avail_w/2)
+			local value = core.settings:get(setting.name)
+			local fs = {
+				("label[0,0.4;%s]"):format(get_label(setting)),
```
Comment (SmallJoker) [inline builtin/common/settings/components.lua:457]: These setting descriptions are no longer translated since this PR, despite the use of gettext. I tried to find an explanation for this without success so far...

**Review by SmallJoker — COMMENTED** [review]
Unfortunately this layout crops a few texts on smaller screens or window sizes. Although I don't think this can be fixed easily with the current formspec design. Just mentioning.
small window PR
Meanwhile in master:
![small window master]https://github.com/user-attachments/assets/88535fb5-67d1-4391-a4dc-53bb0777f82a)

File: builtin/settingtypes.txt (hunk 4 above)
Comment (y5nw) [reply builtin/settingtypes.txt:161]: I am not sure. These keybinding settings only appear in the "Keyboard and mouse" tab which already requires `keyboard_mouse`.

Also the `key` setting type only makes sense in the context of keyboard and mouse control, so for future changes (e.g. SSCSMs) where we would have keybinding settings outside of the "Keyboard and mouse" tab we should consider automatically adding the `keyboard_mouse` requirement to these settings (so that mods will not need to specify the requirement explicitly).

File: builtin/common/settings/dlg_settings.lua [hunk 7]
```diff
@@ -104,23 +103,7 @@ local function load()
...
-			local btn_w = math.min(avail_w, 3)
-			return ("button[0,0;%f,0.8;btn_change_keys;%s]"):format(btn_w, fgettext("Controls")), 0.8
-		end,
-		on_submit = function(self, fields)
-			if fields.btn_change_keys then
-				core.show_keys_menu()
-			end
-		end,
-	}
+	core.full_settings = settingtypes.parse_config_file(false, true)
```
[the remark this answers is not in the document]
Comment (y5nw) [reply builtin/common/settings/dlg_settings.lua]: [272a4f4](https://github.com/luanti-org/luanti/pull/15791/commits/272a4f42ee52ad18f38afd20050d1798e442b7d6)

File: src/gui/guiButtonKey.cpp (hunk 1 above)
Comment (y5nw) [reply src/gui/guiButtonKey.cpp:4]: [f0cd316](https://github.com/luanti-org/luanti/pull/15791/commits/f0cd316266e97658e7dbb96741259f560d502db8)

File: builtin/common/settings/components.lua (hunk 5 above)
Comment (y5nw) [reply builtin/common/settings/components.lua:463]: [0119c9f](https://github.com/luanti-org/luanti/pull/15791/commits/0119c9f6e7406652def7e1161e7538219f752a72)

File: builtin/settingtypes.txt (hunk 4 above)
Comment (y5nw) [reply builtin/settingtypes.txt:161]: https://github.com/luanti-org/luanti/pull/15791/commits/37ce4039617231789582cbdac8e49d5cabaf29dd and https://github.com/luanti-org/luanti/pull/15791/commits/4cc1521c5bec7d33a939839a8b5068f292f6d6f1

File: builtin/common/settings/components.lua (hunk 3 above)
Comment (y5nw) [reply builtin/common/settings/components.lua]: https://github.com/luanti-org/luanti/pull/15791/commits/37ce4039617231789582cbdac8e49d5cabaf29dd and https://github.com/luanti-org/luanti/pull/15791/commits/4cc1521c5bec7d33a939839a8b5068f292f6d6f1

File: builtin/common/settings/components.lua (hunk 6 above)
Comment (y5nw) [reply builtin/common/settings/components.lua:473]: The reason is simply that the description of the settings in `settingtypes.txt` are different from their `guiKeyChangeMenu` counterparts.

(That said, I might change some to verify that the `gettext` call works.)

Comment (y5nw) [reply builtin/common/settings/components.lua:472]: I changed some in https://github.com/luanti-org/luanti/pull/15791/commits/06e05e0dea3cfc8d9c7f8be314c363af9af3ca37. I decided to change some other a bit differently since I redesigned the components to make labels take up the full width of the tab (instead of just half of it) and this allows for longer descriptions.

**Comment by y5nw** [comment]
> Unfortunately this layout crops a few texts on smaller screens or window sizes. Although I don't think this can be fixed easily with the current formspec design.

I changed this a bit so that that label (and the keybinding button) now takes up the entire width of the form:

Bildschirmfoto 2025-03-23 um 15 57 27
Bildschirmfoto 2025-03-23 um 15 57 47

Hard to say I like this given that most key names are just one letter long. (That said, this can change once we have keybindings with modifier keys or secondary keybindings)

File: builtin/settingtypes.txt (hunk 4 above)
Comment (y5nw) [reply builtin/settingtypes.txt:163]: https://github.com/luanti-org/luanti/pull/15791/commits/5069fc736179f91f626653334afc15715514d25a

**Comment by y5nw** [comment]
> Unfortunately this layout crops a few texts on smaller screens or window sizes.

I tried https://github.com/luanti-org/luanti/pull/15791#issuecomment-2746260534. It does not crop the text, but it looks worse IMO, so I reverted it.

IMO it might be better to change the setting menu to use up the full screen/window space, although that would be out of scope for this PR.

File: src/script/lua_api/l_mainmenu.cpp [hunk 8]
```diff
@@ -1029,6 +1012,15 @@ int ModApiMainMenu::l_share_file(lua_State *L)
 	return 1;
 }
 
+/******************************************************************************/
+int ModApiMainMenu::l_are_keycodes_equal(lua_State *L)
+{
```
Comment (grorp) [inline src/script/lua_api/l_mainmenu.cpp:1017]: duplicated

File: src/script/lua_api/l_pause_menu.cpp [hunk 9]
```diff
@@ -3,26 +3,28 @@
...
 {
-	g_gamecallback->keyConfig();
+	g_gamecallback->touchscreenLayout();
 	return 0;
 }
 
-
-int ModApiPauseMenu::l_show_touchscreen_layout(lua_State *L)
+int ModApiPauseMenu::l_are_keycodes_equal(lua_State *L)
 {
```
Comment (grorp) [inline src/script/lua_api/l_pause_menu.cpp:18]: duplicated

I think you're looking for l_menu_common

File: src/gui/mainmenumanager.h [hunk 10]
```diff
@@ -160,7 +154,6 @@ class MainGameCallback : public IGameCallback
 	bool settings_requested = false;
 	bool changepassword_requested = false;
 	bool changevolume_requested = false;
-	bool keyconfig_requested = false;
 	bool touchscreenlayout_requested = false;
 	bool shutdown_requested = false;
 	bool keyconfig_changed = false;
```
Comment (grorp) [inline src/gui/mainmenumanager.h:159]: looks like this should go, along with signalKeyConfigChange

File: src/client/inputhandler.h [hunk 11]
```diff
@@ -163,6 +172,12 @@ class InputHandler
 	virtual void clear() {}
 	virtual void releaseAllKeys() {}
 
+	static void settingChangedCallback(const std::string &name, void *data)
+	{
+		clearKeyCache();
```
Comment (grorp) [inline src/client/inputhandler.h:177]: reloadKeybindings also calls clearKeyCache, should only be done in one of them

File: src/client/inputhandler.cpp [hunk 12]
```diff
@@ -14,6 +14,8 @@
 
 void MyEventReceiver::reloadKeybindings()
 {
+	clearKeyCache();
```
Comment (grorp) [inline src/client/inputhandler.cpp:17]: (2nd occurrence)

File: builtin/common/settings/components.lua [hunk 13]
```diff
@@ -442,6 +442,58 @@ local function make_noise_params(setting)
...
+	local btn_clear = "unbind_" .. setting.name
+	local function add_conflict_warnings(fs, height)
+		local value = core.settings:get(setting.name)
+		if value == "" then
+			return height
+		end
+		for _, o in pairs(core.full_settingtypes) do
+			if o.type == "key" and o.name ~= setting.name and core.are_keycodes_equal(core.settings:get(o.name), value) then
+				table.insert(fs, ("label[0,%f;%s]"):format(height + 0.3,
+						fgettext("Keybinding conflict: $1", fgettext(o.readable_name))))
```
Comment (grorp) [inline builtin/common/settings/components.lua:456]: should be pretty obvious that it's about a keybinding, "conflict" should be enough (saving label space for translations etc.)

also should be MT_ORANGE or MT_RED

**Review by grorp — COMMENTED** [review]
- there's too much unused vertical space inbetween. you have to scroll too much to see all the keybindings. I think something like this would be better:
   screenshot
   (info buttons would need to go in again of course)

- it's impossible to set a keybinding to mouse buttons, even though dig/place are listed and show them correctly

- might make sense to put the keybinding section below a new sub-heading

File: src/script/lua_api/l_pause_menu.cpp (hunk 9 above)
Comment (y5nw) [reply src/script/lua_api/l_pause_menu.cpp]: Thanks for the information!

Fixed in [faff70b](https://github.com/luanti-org/luanti/pull/15791/commits/faff70b7366c64451078289efce40586035b6cb5)

File: src/client/inputhandler.h (hunk 11 above)
Comment (y5nw) [reply src/client/inputhandler.h]: [467e157](https://github.com/luanti-org/luanti/pull/15791/commits/467e15700d7fa71eb57f426189e31697e51a7e64)

(Should be in `reloadKeybindings`; I think this duplication resulted from a merge conflict or something similar.)

File: builtin/common/settings/components.lua (hunk 13 above)
Comment (y5nw) [reply builtin/common/settings/components.lua:456]: IMO this is more obvious for translation since `Conflict: $1` can become somewhat vague unless we add an explanation that this refers to keybindings.

File: src/gui/mainmenumanager.h (hunk 10 above)
Comment (y5nw) [reply src/gui/mainmenumanager.h]: [d80622e](https://github.com/luanti-org/luanti/pull/15791/commits/d80622e347002c2ed02a118a488ca5b065d037a8)

File: builtin/common/settings/components.lua (hunk 13 above)
Comment (y5nw) [reply builtin/common/settings/components.lua]: Changed in https://github.com/luanti-org/luanti/pull/15791/commits/126a4f586183cb4ee6e5ed9af6d4a74920513ddb

**Comment by y5nw** [comment]
> (button height reduced to 0.6, spacing reduced heavily as well):

I'm not sure whether this makes a significant difference in terms of scrolling. I would personally prefer having a dedicated tab with a table of keybindings, but this does not seem to fit well into the way the setting form is currently designed.

The height of 0.8 is also taken from other elements, so I would like to keep it this way for consistency.

> It's impossible to set a keybinding to mouse buttons, even though dig/place are listed and show them correctly

Fixed in [33adc71](https://github.com/luanti-org/luanti/pull/15791/commits/33adc7120ecf1c278e6f046bbc44d517c384f28d):

Bildschirmfoto 2025-04-01 um 22 56 13

(Actually I just noticed that this crashes the client if one tries to change the keybinding in-game; I need to look into this.)

> It might make sense to put the keybinding section below a new sub-heading

Done in [cfaf84d](https://github.com/luanti-org/luanti/pull/15791/commits/cfaf84db439421948feac510028f4c74f645f8e5).

**Comment by grorp** [comment]
> Fixed in 33adc71: [screenshot]

Thank you, that looks good.

> The height of 0.8 is taken from other elements, so I would like to keep it this way for consistency.

Reducing the height would indeed make things look more inconsistent. It could be a significant improvement in this case though. The amount of hidden pixels (the amount of scrolling necessary to see all the keybindings) was reduced by about 40% in my test (from 3711 to 2185). Maybe it would be possible to argue that buttons that usually only show a single letter don't need as much space :)

Since #13282, the keybinding menu also serves the purpose of viewing the controls, so being able to get a good overview is useful.

Some of the keys listed at the very bottom are actually quite useful, like the viewing range and camera mode keys, so you'd want users to scroll all the way. On a side note, it might make sense to move these three further up.

**Comment by SmallJoker** [comment]
> Fixed in [33adc71](https://github.com/luanti-org/luanti/pull/15791/commits/33adc7120ecf1c278e6f046bbc44d517c384f28d):

Why exactly do we need this additional dialogue? Could we instead listen to mouse/keypad events as well to avoid ..
1. Click the settings button to opening the "single key change menu"
2. Selecting the right item in the dropdown
3. Pressing the button to capture a key || or select the mouse button in the dropdown
4. Close the menu

Shorter alternative:
1. Click the settings button to listen to any input.

**Comment by y5nw** [comment]
> Why exactly do we need this additional dialogue? Could we instead listen to mouse/keypad events as well to shorten the following steps ...

The main issue _was_ that I could not figure out how to cleanly handle mouse buttons with the keybinding button. I have a solution now (and committed) so I reverted the dialog.

Side note: We will likely still need a dialog for #15934, but we can leave it to that PR instead of here.

**Comment by y5nw** [comment]
> The amount of hidden pixels (the amount of scrolling necessary to see all the keybindings) was reduced by about 40% in my test (from 3711 to 2185).

:eyes: That definitely sounds like an improvement. If you still have the diff, feel free to post it here or push it directly yourself.

> Some of the keys listed at the very bottom are actually quite useful, like the viewing range and camera mode keys, so you'd want users to scroll all the way. On a side note, it might make sense to move these three further up.

I suppose I'll just move the hotbar slot selection keys to the bottom of the keybinding list then given that the entries beyond slot 10 is likely unset: 702fea7

**Review by SmallJoker — APPROVED** [review]
Works as-is. I am happy. Thank you. Works well.

File: builtin/settingtypes.txt [hunk 14]
```diff
@@ -178,6 +180,231 @@ enable_hotbar_mouse_wheel (Hotbar: Enable mouse wheel for selection) bool true
...
+keymap_toggle_chat (Toggle chat log) key KEY_F2
+
+#    Key for toggling the display of the large chat console.
+keymap_console (Large chat console) key KEY_F10
+
+#    Key for toggling the display of fog.
+keymap_toggle_fog (Toggle fog) key KEY_F3
+
+#    Key for toggling the camera update. Only usable with 'debug' privilege.
+keymap_toggle_update_camera (Toggle camera update) key
```
Comment (grorp) [inline builtin/settingtypes.txt:292]: perhaps this should be in advanced settings? since the behavior this causes could only be described as buggy by a normal user

File: src/gui/guiButtonKey.cpp [hunk 15]
```diff
@@ -0,0 +1,125 @@
...
+		switch (event.MouseInput.Event)
+		{
+		case EMIE_LMOUSE_LEFT_UP: [[fallthrough]];
+		case EMIE_MMOUSE_LEFT_UP: [[fallthrough]];
+		case EMIE_RMOUSE_LEFT_UP:
+			setPressed(false);
+			if (capturing) {
+				sendKey();
+				return true;
+			} if (AbsoluteClippingRect.isPointInside(
```
Comment (grorp) [inline src/gui/guiButtonKey.cpp:82]: ?

File: src/gui/guiButtonKey.cpp [hunk 16]
```diff
@@ -0,0 +1,125 @@
...
+	{
+	case EET_KEY_INPUT_EVENT:
+		if (!event.KeyInput.PressedDown) {
+			setPressed(false);
+			if (capturing) {
+				cancelCapture();
+				if (event.KeyInput.Key != KEY_ESCAPE)
+					sendKey();
+				return true;
+			} else if (isPressed() && (event.KeyInput.Key == KEY_RETURN || event.KeyInput.Key == KEY_SPACE)) {
```
Comment (grorp) [inline src/gui/guiButtonKey.cpp:56]: is this supposed to allow starting capturing by keypress? that doesn't work, the button shows the press animation, but nothing else happens

File: src/gui/guiButtonKey.h [hunk 17]
```diff
@@ -0,0 +1,80 @@
...
+			const wchar_t *tooltiptext = L"");
+
+	//! Called if an event happened
+	virtual bool OnEvent(const SEvent &event) override;
+
+	//! Start key capture
+	void startCapture()
+	{
+		capturing = true;
+		super::setText(wstrgettext("Press Key").c_str());
```
Comment (grorp) [inline src/gui/guiButtonKey.h:49]: maybe "button" because mouse buttons are also possible?

File: src/gui/guiButtonKey.cpp [hunk 18]
```diff
@@ -0,0 +1,125 @@
...
+			} if (AbsoluteClippingRect.isPointInside(
+						core::position2d<s32>(event.MouseInput.X, event.MouseInput.Y))) {
+				startCapture();
+				return true;
+			}
+			break;
+		case EMIE_LMOUSE_PRESSED_DOWN:
+			if (capturing) {
+				setKey(LMBKey);
+				return true;
```
Comment (grorp) [inline src/gui/guiButtonKey.cpp:91]: it might make sense to ignore events with `MouseInput.Simulated` when capturing. currently, a tap on Android also sets the keybinding to LBM, which doesn't make much sense as it doesn't work that way in-game.

if you decide to deal with this, it should to be done consistently though. not required.

**Comment by grorp** [comment]
> The main issue was that I could not figure out how to cleanly handle mouse buttons with the keybinding button. I have a solution now (and committed) so I reverted the dialog.

:+1: 
my only concern would be that it might not be obvious to users how to set a mouse button, but I don't have a suggestion

> 👀 That definitely sounds like an improvement. If you still have the diff, feel free to post it here or push it directly yourself.

while testing my changes on my Android phone, I unfortunately found out that the buttons end up being too small there with height 0.6

so the only thing I can still offer is the spacing reduction, which is still an improvement, but a much smaller one: https://github.com/grorp/luanti/commit/e285fd8f03f580176dc5bb310a1792e8e6e56493

> Considering that hotbar slot keys are likely unset beyond slot 10, I suppose I'll just move the hotbar slot selection keys to the bottom of the keybinding list then: [702fea7](https://github.com/luanti-org/luanti/pull/15791/commits/702fea72de2c3a0f47e1da12d8e2846a43063783)

:+1:

File: src/gui/guiButtonKey.cpp (hunk 15 above)
Comment (y5nw) [reply src/gui/guiButtonKey.cpp]: I was thinking about `else if`: [f1bb764](https://github.com/luanti-org/luanti/pull/15791/commits/f1bb764550a31b33be126dbb28beec233b7c71d3)

File: src/gui/guiButtonKey.h (hunk 17 above)
Comment (y5nw) [reply src/gui/guiButtonKey.h]: [64c13b2](https://github.com/luanti-org/luanti/pull/15791/commits/64c13b2f6240635319dcf6a9b3dd2ad69b7cce87)

File: src/gui/guiButtonKey.cpp (hunk 16 above)
Comment (y5nw) [reply src/gui/guiButtonKey.cpp]: Seems like this was caused by an early `setPressed(false)`: [6998755](https://github.com/luanti-org/luanti/pull/15791/commits/69987557df2169ba684450cfb47047998dbd51c3)

File: src/gui/guiButtonKey.h [hunk 19]
```diff
@@ -45,14 +45,20 @@ class GUIButtonKey : public GUIButton
 	//! Start key capture
 	void startCapture()
```
Comment (grorp) [inline src/gui/guiButtonKey.h:46]: btw: is there a reason these are public, instead of private?  (`startCapture`, `cancelCapture`, `setKey`)
and for the unused public getter functions, is there a reason they exist? (`isCapturing`, `getKey`)

File: src/gui/guiButtonKey.cpp [hunk 20]
```diff
@@ -0,0 +1,132 @@
...
+{
+	if (Parent) {
+		SEvent e;
+		e.EventType = EET_GUI_EVENT;
+		e.GUIEvent.Caller = this;
+		e.GUIEvent.Element = nullptr;
+		e.GUIEvent.EventType = EGET_BUTTON_CLICKED;
+		Parent->OnEvent(e);
+	}
+	cancelCapture();
```
Comment (grorp) [inline src/gui/guiButtonKey.cpp:41]: however `cancelCapture` is called before `sendKey` already, originally only for key event handling, but now also for mouse event handling

File: src/gui/guiButtonKey.cpp [hunk 21]
```diff
@@ -78,17 +78,23 @@ bool GUIButtonKey::OnEvent(const SEvent & event)
 		case EMIE_RMOUSE_LEFT_UP:
 			setPressed(false);
 			if (capturing) {
-				sendKey();
+				cancelCapture();
+				if (!event.MouseInput.Simulated)
```
Comment (grorp) [inline src/gui/guiButtonKey.cpp:82]: in the `MouseInput.Simulated == true` case, capturing is already cancelled earlier while handling `EMIE_LMOUSE_PRESSED_DOWN`, so this check is unnecessary, isn't it? (anyway, I somewhat doubt this is worth the extra complexity)

File: src/gui/guiButtonKey.cpp (hunk 16 above)
Comment (grorp) [reply src/gui/guiButtonKey.cpp]: works now :+1:

File: src/gui/guiButtonKey.cpp [hunk 22]
```diff
@@ -0,0 +1,132 @@
...
+			} else if (AbsoluteClippingRect.isPointInside(
+						core::position2d<s32>(event.MouseInput.X, event.MouseInput.Y))) {
+				Environment->setFocus(this);
+				setPressed(true);
+				return true;
+			}
+			break;
+		case EMIE_MMOUSE_PRESSED_DOWN:
+			if (capturing) {
+				setKey(MMBKey);
```
Comment (grorp) [inline src/gui/guiButtonKey.cpp:108]: could add a `setPressed(true);` when capturing mouse buttons to match how the button responds when capturing keys

File: src/gui/guiButtonKey.h (hunk 19 above)
Comment (y5nw) [reply src/gui/guiButtonKey.h:49]: I think I had some C++-based testing code before where this was useful, but it is not useful anymore. Resolved in https://github.com/luanti-org/luanti/pull/15791/commits/fd1b9a588a213bc5414b8c6be3450aad38f86e8b

File: src/gui/guiButtonKey.cpp (hunk 21 above)
Comment (y5nw) [reply src/gui/guiButtonKey.cpp:81]: This is from a tempoary commit where I partially address https://github.com/luanti-org/luanti/pull/15791#discussion_r2043165415 . The reason I have not (yet) resolved that comment is that it causes some weird behavior with the keybinding buttons (e.g. tapping different a different button while another one is capturing)

Comment (y5nw) [reply src/gui/guiButtonKey.cpp]: https://github.com/luanti-org/luanti/pull/15791/commits/88989c58220622b881f11e6e55540932f6048320 for now

File: src/gui/guiButtonKey.cpp (hunk 18 above)
Comment (y5nw) [reply src/gui/guiButtonKey.cpp]: Fixed in multiple commits since https://github.com/luanti-org/luanti/pull/15791/commits/d7f92263f38d6cfa1b44f626ca2f7bbf1ed218e1

File: builtin/settingtypes.txt (hunk 14 above)
Comment (y5nw) [reply builtin/settingtypes.txt]: [bbf1e42](https://github.com/luanti-org/luanti/pull/15791/commits/bbf1e423d544e31b418faffb215d75d596773f0d)

File: builtin/settingtypes.txt [hunk 23]
```diff
@@ -1825,6 +2049,22 @@ instrument.profiler (Profiler) bool false
...
+keymap_quicktune_prev (Quicktune: select previous entry) key
+
+#    Key for switching to the next entry in Quicktune.
+keymap_quicktune_next (Quicktune: select next entry) key
+
+#    Key for decrementing the selected value in Quicktune.
+keymap_quicktune_dec (Quicktune: decrement value) key
+
+#    Key for incrementing the selected value in Quicktune.
+keymap_quicktune_inc (Quicktune: increment value) key
```
Comment (y5nw) [inline builtin/settingtypes.txt:2067]: I hope the description for Quicktune keys is correct? (I have never used quicktune before)

File: builtin/settingtypes.txt [hunk 24]
```diff
@@ -1825,6 +2049,22 @@ instrument.profiler (Profiler) bool false
 #    0 = disable. Useful for developers.
 profiler_print_interval (Engine profiling data print interval) int 0 0
 
+[*Advanced Controls] [common]
```
Comment (grorp) [inline builtin/settingtypes.txt:2052]: - `[client]`
- This is not really "advanced controls", more like "keybindings for engine developers"
- I'm not sure this warrants its own category. I would have suggested making this a section in the "Developer Options" category right above, but the audience of the existing settings there are mod developers, not engine developers, so not a good fit. Could just dump it into the long "Advanced" -> "Advanced" category as a new section :shrug:  
   (That one will need splitting up anyway at some point, and then these keybindings could be moved into a new "Advanced" -> "Client" category along with other stuff.)

**Review by grorp — COMMENTED** [review]
The new changes look good :+1:

File: builtin/settingtypes.txt (hunk 23 above)
Comment (grorp) [reply builtin/settingtypes.txt:2067]: (I don't know either)

File: builtin/settingtypes.txt (hunk 24 above)
Comment (y5nw) [reply builtin/settingtypes.txt]: [ed423f8](https://github.com/luanti-org/luanti/pull/15791/commits/ed423f8d069119ffa7d28277906c1efbdf158960). I guess I'll just call it "Client Debugging" then.

**Review by grorp — APPROVED** [review]
Looks good 👍

Thank you for working on this!
