### PR TITLE
Lua API: Unify server env checks and fix missing ones

### LINKED ISSUE #16456: Segfault when attempting to call `core.get_player_information` during load time
### Luanti version

```true
Luanti 5.14.0-dev-f390137d6 (Linux)
Using LuaJIT 2.1.0-beta3
Built by GCC 12.2
Running on Linux/6.1.0 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Operating system and version

Debian

### CPU model

_No response_

### GPU model

_No response_

### Active renderer

_No response_

### Summary

The game crashes by segfault when attempting to call `core.get_player_information` from a mod during load time.

The game should not crash and instead either return `nil` or valid player information.

### Steps to reproduce

Add

```lua
core.get_player_information("hello") -- can be any user name
```

To the `init.lua` file of a mod.

Then start the game and get the following (output from gdb):

```
Thread 21 "ServerStart" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffc8a316c0 (LWP 13048)]
0x0000555555be477e in ServerEnvironment::getPlayer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) [clone .constprop.0] ()
```

### PR DESCRIPTION
**Pull request by SmallJoker**
A few functions tried to dereference a ServerEnvironment nullptr by calling 'getEnv()'. This change makes use of the macro where possible.

Fixes #16456. The additional `luaL_error` call is very likely to reveal more mod bugs.

## To do

This PR is Ready for Review.

## How to test

```lua
core.get_player_information("hello")
core.get_player_ip("hello")
core.get_player_window_information("hello")
core.create_schematic(nil, nil, nil, "hello")
```

### CODE REVIEW

File: src/script/lua_api/l_internal.h [hunk 1]
```diff
@@ -44,8 +44,10 @@
 #define GET_ENV_PTR_NO_MAP_LOCK                              \
 	DEBUG_ASSERT_NO_CLIENTAPI;                               \
 	ServerEnvironment *env = (ServerEnvironment *)getEnv(L); \
-	if (env == NULL)                                         \
-		return 0
+	if (!env) {                                              \
+		luaL_error(L, "Calling this function during script init is disallowed."); \
```
Comment (sfan5) [inline src/script/lua_api/l_internal.h]: now I'm usually on the "it's considered user error" side but this sure looks like a too severe behavior change.

File: src/script/lua_api/l_server.cpp [hunk 2]
```diff
@@ -124,35 +124,34 @@ int ModApiServer::l_get_player_privs(lua_State *L)
...
 
 	const char *name = luaL_checkstring(L, 1);
-	RemotePlayer *player = server->getEnv().getPlayer(name);
+	RemotePlayer *player = env->getPlayer(name);
 	if (!player) {
 		lua_pushnil(L); // no such player
 		return 1;
 	}
 
+	Server *server = env->getGameDef();
```
Comment (sfan5) [inline src/script/lua_api/l_server.cpp:153]: huh how does this work without a cast?

Comment (SmallJoker) [reply src/script/lua_api/l_server.cpp:153]: `GET_ENV_PTR_NO_MAP_LOCK` and `GET_ENV_PTR` already cast `env` into `ServerEnvironment`, which has a reference to `Server`.

File: src/script/lua_api/l_internal.h (hunk 1 above)
Comment (SmallJoker) [reply src/script/lua_api/l_internal.h]: I thought this would come up, but is it more correct to silently return `nil` or throw another error? Currently there are inconsistencies and I would like to unify them as much as possible.

EDIT: None out of the approx. 10 `l_env.cpp` functions that I looked up have any documentation about the behaviour during the init phase. Thus, we're technically changing the undefined behaviour.

Comment (appgurueu) [reply src/script/lua_api/l_internal.h]: I agree that this looks likely to break mods. If we wanted to consider shipping this, a lengthy feature freeze & RC would be a must to make sure it does not.

I can tell you that unfortunately modders do occasionally call functions "too early". For example I've seen it with `get_connected_players()`, which now throws a deprecation warning if you do this. One reason they do it is that they have one big step that does everything, and they want to run that at init with t=0.

---

> I thought this would come up, but is it more correct to silently return nil or throw another error?

Third option: Return nothing, but raise a deprecation warning. `get_connected_players()` is a good precedent for this.

Those who want errors can opt into deprecation warnings as errors, those who don't care won't care, those who maintain legacy mods will presumably be glad they get a warning and time to fix it rather than everything being on fire again.

Comment (sfan5) [reply src/script/lua_api/l_internal.h]: I think we should stay with the "env functions silently do nothing when called early" paradigm. A deprecation warning can be considered.

File: src/script/lua_api/l_server.cpp (hunk 2 above)
Comment (sfan5) [reply src/script/lua_api/l_server.cpp:153]: right.
https://github.com/luanti-org/luanti/blob/f390137d6eae6cc94208b3d9cc3556d4d5cc9754/src/serverenvironment.h#L121-L122

File: src/script/lua_api/l_internal.h (hunk 1 above)
Comment (SmallJoker) [reply src/script/lua_api/l_internal.h]: The most recent commit now changed the error to a deprecation warning. I'd prefer throwing an error outright but well.. maybe later.

File: src/script/lua_api/l_object.cpp [hunk 3]
```diff
@@ -770,7 +770,7 @@ int ObjectRef::l_get_bone_overrides(lua_State *L)
 // set_attach(self, parent, bone, position, rotation, force_visible)
 int ObjectRef::l_set_attach(lua_State *L)
 {
-	GET_ENV_PTR;
+	GET_ENV_PTR_NO_MAP_LOCK;
```
Comment (appgurueu) [inline src/script/lua_api/l_object.cpp:773]: So the map lock does not include entities then?

Since the map lock macros don't do anything and are just for future use: Do we have a definition of what the map lock should cover to apply here?

**Review by appgurueu — APPROVED** [review]
You could leave the already existing errors in (no risk of a regression there, no need to be lenient), but I'm also fine with being simply consistent and logging a deprecation warning for everything.

Tested, got the expected deprecation warnings.

File: src/script/lua_api/l_object.cpp (hunk 3 above)
Comment (SmallJoker) [reply src/script/lua_api/l_object.cpp:773]: It should include entities if it affects their lifecycle or physical properties. Attachments are only kept in memory, and are handled outside of ServerMap (if that ever makes a functional difference).

File: src/script/lua_api/l_internal.h [hunk 4]
```diff
@@ -44,8 +44,10 @@
 #define GET_ENV_PTR_NO_MAP_LOCK                              \
 	DEBUG_ASSERT_NO_CLIENTAPI;                               \
 	ServerEnvironment *env = (ServerEnvironment *)getEnv(L); \
-	if (env == NULL)                                         \
-		return 0
+	if (!env) {                                              \
+		log_deprecated(L, "Calling this function during script init is disallowed.", 1); \
+		return 0;                                            \
+	} do {} while (0)
```
Comment (sfan5) [inline src/script/lua_api/l_internal.h]:
```suggestion
	} \
	((void)0)
```

**Review by sfan5 — APPROVED** [review]
LGTM
