### PR TITLE
SDL: Use scancodes for keybindings

### LINKED ISSUE #8781: keymap_slot setting differentiating capital letters
##### Minetest version

```
https://github.com/minetest/minetest/commit/49f100618350e81d98410a874ce30b5c30b32927
```

##### OS / Hardware

Operating system:
CPU:

GPU model:
OpenGL version:

##### Summary

I can't select an item slot if I'm holding down shift, because keymap_slot1 = "t" is not the same as keymap_slot1 = "T" apparently.

it's not possible to assign two actions to one keymap_slot1 or any other key binding, otherwise I would bind it to both "t" /and/ "T".

### LINKED ISSUE #12556: A fatal error occurred: Unexpected multibyte character on launch
##### Minetest version

```
Minetest 5.5.1 (Linux)
Using Irrlicht 1.9.0mt4
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/share/minetest"
STATIC_LOCALEDIR="/usr/share/locale"

```

##### OS / Hardware

Operating system: Artix, 5.18.12-artix1-1 kernel
CPU: Ryzen 5 3600X

GPU model: NVidia RTX 2060 Super

##### Summary

Minetest crashes on launch, as soon as a window appear(without rendering the first frame), running it from the terminal with `--verbose` yields the following:
```
--- snip ---
2022-07-18 12:30:39: VERBOSE[Main]: Client: Setting Xorg window manager Properties
2022-07-18 12:30:39: VERBOSE[Main]: Client: Setting Xorg _NET_WM_PID extended window manager property
2022-07-18 12:30:39: VERBOSE[Main]: Client: Setting Xorg WM_CLIENT_LEADER property
2022-07-18 12:30:39: VERBOSE[Main]: Client: Configuring general top level window properties
2022-07-18 12:30:39: ERROR[Main]: In thread 7f7819a15240:
2022-07-18 12:30:39: ERROR[Main]: /build/minetest/src/minetest-5.5.1/src/client/keycode.cpp:126: KeyPress::KeyPress(const char*): A fatal error occurred: Unexpected multibyte character
```
I have both the `us` and `he` keyboard layouts, i tried removing `he` and keeping only the `us` keyboard layout to no avail.
 
I also tried compiling master but the bug still remained.

##### Steps to reproduce

I pretty much just try to launch minetest(through terminal or gui, same results).

### LINKED ISSUE #13904: Keys are either mis-detected or mis-labeled in keybinding dialog (Neo2 keyboard layout)
### Minetest version

```true
5.7.0-279-gb1dec37ad
5.7.0-350-g8a9855241
```

### Active renderer

OpenGL 1.4

### Irrlicht device

X11 / SDL (both are bugged, but in a different way)

### Operating system and version

Debian GNU/Linux 11.7

### CPU model

Intel(R) Core(TM) Duo CPU      T2400  @ 1.83GHz

### GPU model

Intel Corporation Mobile 945GM/GMS/GME, 943/940GML Express Integrated Graphics Controller (rev 03)

### OpenGL version

1.4

### Summary

I tried to bind some keys in the keybinding dialog and think they are either mistranslated or mis-detected by Minetest:

Here are the keys I pressed, the German label I see after pressing them and what that translates to:

* ISO_Level3_Shift left (above shift key) → Menü rechts (Menu right)
* ISO_Level3_Shift right (next to enter key) → Menü rechts (Menu right)
* Alt left → Menü links (Menu left)
* Alt right → Linke Taste (literally: left key)
* Acute (dead key) → OEM 6
* Grave (dead key) → OEM 3
* Circumflex (dead key) → OEM 5
* ß → OEM 4
* ~Num Lock (on keypad) → Tab (Tabulator)~

**Edit:** The Num Lock key is apparently set to an actual tab character on my system.

Meanwhile, the Menu and Tab keys are correctly detected/labeled as ”Menü” and “Tab”.

My keyboard is a QWERTY keyboard with a numpad and my keyboard layout is German (Neo 2).

### Steps to reproduce

1. Start Minetest with German (Neo 2) keyboard layout and German locale.
2. Try to bind some keys to some functions in the keybinding dialog.
3. Look at the names of the keys that are diplayed.

### LINKED ISSUE #14940: Use scancodes for key binding
To increase cross-platform compatibility for key binding, Minetest should switch to using scancodes by default for key bindings.

When displaying the key in the GUI, the key name should still be shown (not the scancode name). `SDL_GetKeyName(SDL_GetKeyFromScancode(scancode));`

https://wiki.libsdl.org/SDL2/SDL_Scancode

### LINKED ISSUE #15747: Make the numpad and directional arrows possible to bind.
### Problem

Binding the numpad or the directional arrows will result in the buttons to perform the custom action while at the same time perform the hardcoded action. Example, binding forward to 8 means that when I move forward I also select hotbar 8 item.

### Solutions

Remove the hardcoded purpose for the numpad and directional arrows, or any other thing honestly, just allow players to bind what they want to what they want without predefined hardcoded binding.

### Alternatives

I don't think there's alternatives unless we consider leaving this an alternative.

### Additional context

I'm left handed, I use the numpad to move as one would wasd and to interact/open inventoury. I also reach for the directional arrows to jump, crouch and sprint.
I've been doing this for decades (literally, I guess I'm old) and I would love to be able to do on luanti too.
However, if I try to jump, which uses the left arrow in my case, I always jump to the left. If I move forward (numpad 8) I move and also select the 8 slot of my action bar.
It would be wonderful if those buttons were not hardcoded for those purposes.

### PR DESCRIPTION
**Pull request by y5nw**
This PR makes Minetest use scancodes for keybindings.

- Goal of the PR
  Make Minetest use scancodes (instead of keycodes) for key bindings.
- How does the PR work?
  The SDL scancode is passed to `SKeyInput::SystemKeyCode`. The `KeyPress` class is modified to be basically a wrapper around this.
- Does it resolve any reported issue?
  - Fixes #14940
  - Fixes #13904 (if not, this would be an upstream issue)
  - Fixes #15747
  - Resolves #12556 (relevant code path removed)
  - Resolves #8781 (keycode-based syntax deprecated)
- Does this relate to a goal in [the roadmap](https://github.com/minetest/minetest/blob/master/doc/direction.md)?
  Yes - SDL.
- If not a bug fix, why is this PR needed? What usecases does it solve?
  This was discussed recently.

Related: #12507 (new default key), #14545, #14874 (allows people to continue using e.g. Shift+7 if they want to).

Documentation update: luanti-org/docs.luanti.org#211

## To do

This PR is ready for review.

- [x] Switch to scancodes for SDL. Address regressions:
  - [x] Fix: Escape and `AC_BACK` keys not working.
  - [x] Fix: (Android) Cannot close formspec when a text field is focused.
  - [x] Fix: actions without keybindings are bound to the left mouse button.
  - [x] Properly implement scancodes (using `std::variant`) for keypresses from non-keyboard input (mouse, joystick, etc.)
  - [x] Convert `KEY_OEM_*` keys to scancodes directly. (See note below)
  The current approach no longer requires changing non-SDL `IrrlichtDevices`.
- Partial rework of `KeyPress` and event handling
  - [x] Rework `KeyPress`
  - [x] Allow binding to keys with keychars (keycodes) not in the lookup table.
  - [x] Allow binding to keys with no keycode (e.g. dead keys).
  - [x] Change touchscreen GUI to send events with scancodes.
- Keybinding settings
  - [x] Add syntax for scancode settings. (see notes)
- Followup PRs:
  - Allow using secondary keybindings: #15577
  - Allow keybindings with modifer keys: #14874
  - **Important:** Warn users about new keybindings.
  - After removing non-SDL `IrrlichtDevice`s:
    - Expose SDL headers to Luanti.
    - Implement `std::hash<KeyPress>` and replace `KeyList` with `std::unordered_set<KeyPress>`
    - Implement SDL-specific scancode names (i.e. `SDL_SCANCODE_x`). (Useful for #12488) Note that this requires Luanti (not just Irrlicht) to have access to SDL headers.
    - Fix unittests

## How to test
* Set keybindings as usual or use existing keybinding settings. (In particular, test binding to keys such as backtick, `ü`, and dead keys). Observe that the keybinding (in terms of scancodes) is the same after switching to a different layout.
* Observe that both the Escape key and the Android back key work as the same key.

## Notes
* The scancode-based keybinding syntax introduced in this PR is only used (and enabled) for SDL builds.
* Unittests have been disabled:
  * The behavior of `KeyPress` is fully dependent on the Irrlicht device.
  * Scancode/keycode conversions for SDL require an active `IrrlichtDevice` which is not available in unittests.
* The "press Shift to bind to symbols" feature has been removed as it does not work with SDL scancodes. Note that this causes existing configurations to break *even when Minetest is built without SDL*.
* The Irrlicht source code suggests that the various OEM keys refer to phsical keys (similar to SDL scancodes), but on my non-SDL X11 build it appears that the _exact_ OEM key still depends on the keyboard layout.
* https://github.com/minetest/minetest/pull/14964#issuecomment-2299626800
* This PR uses scancodes for individual keys. In particular, left shift and right shift are treated as separate keys. *Addressing this requires a separate/followup PR that implements secondary keybindings.*
* We will end up (one way or another) requiring requiring some users to rebind their keys regardless of what we choose as the default. Scancode-based defaults basically break keyboard layouts where a key is located in a different position than its US counterpart, while keycode-based configurations would break on layouts where a key is not present in the **unshifted** position. (https://github.com/minetest/minetest/pull/14964#issuecomment-2559974639 and https://irc.minetest.net/minetest-dev/2024-12-26#i_6230893) Using a mixture of both can result in key conflicts (https://irc.minetest.net/minetest-dev/2024-11-10#i_6216414)

### CODE REVIEW

**Comment by rubenwardy** [comment]
Very nice work y5nw! Thanks for picking this up so quickly

**Comment by rubenwardy** [comment]
Pressing a key (P) in the controls menu shows invalid wide string

image

**Comment by y5nw** [comment]
> When using the X11 driver, pressing a key (P) in the controls menu shows invalid wide string

Oops, I wrote some boilerplate code to allow other devices to pass scancode information but did not actually implement scancode passing for devices other than SDL. Will fix.

**Comment by y5nw** [comment]
Testing needed. Note that binding to Shift+[Key] is also removed for non-SDL devices.

**Comment by rubenwardy** [comment]
Sorry for being such a Linux user, but this key should be called Left Super not Left Windows:

image

**Comment by rubenwardy** [comment]
Inc range is unbound by default. Should be bound to `=`

image

**Comment by rubenwardy** [comment]
> This PR does not change the default keybindings to scancodes.
> The default setting in this PR remains that keybindings are saved as keycodes.

Would it not make sense to change the defaults when built with SDL? We don't need to worry about breaking user configs created using a `-dev` version

**Comment by y5nw** [comment]
> Sorry for being such a Linux user, but this key should be called Left Super not Left Windows:

This is defined in the existing keycode map:
https://github.com/minetest/minetest/blob/b0ad9a6c3321c58044c5bcb5d2c0d904487d14fa/src/client/keycode.cpp#L128-L129

In the future (i.e. after fully switching to SDL), this map should ideally be factor to drop `irr::EKEY_CODE` (since it is just another layer of abstraction) in favor of SDL's native keycode (or scancode, if we want to make the default settings more readable than just numbers). I would prefer renaming the keys at that point.

> Inc range is unbound by default. Should be bound to `=`

Yes, this is a result of `=` not corresponding to a scancode (and therefore being unset). This should be fixed now that the default settings have been adjust to use scancodes instead:

> > This PR does not change the default keybindings to scancodes.
> > The default setting in this PR remains that keybindings are saved as keycodes.
> 
> Would it not make sense to change the defaults when built with SDL? We don't need to worry about breaking user configs created using a `-dev` version

On a second thought, this would make sense. I have added this in a later commit now.

(I only skimmed through the `defaultsettings.cpp` file and had the impression that the file would be parsed be some other code. Turned out I was wrong.)

**Comment by okias** [comment]
I would love to backport this one to 5.9.0, so we can have proper SDL 2 for Linux distros (and we can run Minetest nicely on the phones).

If I would ask if it would be possible to keep this MR without behavior changes when using SDL 2 and drop anything which changing behavior into followup MR.

Thank you for addressing it so quickly!

**Comment by y5nw** [comment]
> I would love to backport this one to 5.9.0, so we can have proper SDL 2 for Linux distros (and we can run Minetest nicely on the phones).
> 
> If I would ask if it would be possible to keep this MR without behavior changes when using SDL 2 and drop anything which changing behavior into followup MR.

The PR in itself is intended to bring a (potentially breaking) behavior change: switching from SDL keycodes to scancodes, so I don't think it would make much sense to split this PR specifically.

My intention with this PR is to have this merged immediately before/after creating a hard dependency on SDL, as support for the non-SDL device is (at least) partly broken by this PR anyway and it would therefore not make sense to ship a release with a non-SDL device with breaking changes only to break things again in the release after that. The result of this intention is that the code changes are relatively (in comparison to another approach I attempted) small and simple (quite some things can be removed without much pain in a post-SDL refactor) but at the cost of partly breaking non-SDL devices.

**Comment by rubenwardy** [comment]
We're planning on releasing much more frequently, on a regular interval of every 2-3 months rather than 6-9 months. So if this gets in soon then we can release 5.10.0 with SDL2 in October.

There's also an argument to release 5.10 sooner than that if we finish all the SDL2 required changes

**Comment by okias** [comment]
> We're planning on releasing much more frequently, on a regular interval of every 2-3 months rather than 6-9 months.

amazing, that sounds like very good news to me! :)

If the new release comes soon after the SDL2 testing and switch, that would help the effort of bringing more users to mobile Linux platforms by a lot. Good games always help :wink:

**Comment by Zughy** [comment]
@y5nw rebase needed

File: src/client/keycode.cpp [hunk 1]
```diff
@@ -236,122 +238,122 @@ static const struct table_key table[] = {
...
-		if (strcmp(table_key.Name, name) == 0)
+		if (table_key.Char == Char)
 			return table_key;
 	}
 
-	throw UnknownKeycode(name);
+	std::ostringstream os;
+	os << "<Char " << hex_encode((char*) &Char, sizeof(wchar_t)) << ">";
+	auto newsym = wide_to_utf8(std::wstring_view(&Char, 1));
+	table_key new_key = {newsym, irr::KEY_KEY_CODES_COUNT, Char, newsym};
```
Comment (appgurueu) [inline src/client/keycode.cpp:259]:
```suggestion
	table_key new_key {newsym, irr::KEY_KEY_CODES_COUNT, Char, newsym};
```

File: src/client/keycode.cpp [hunk 2]
```diff
@@ -236,122 +238,122 @@ static const struct table_key table[] = {
...
+
 	for (const auto &table_key : table) {
-		if (strcmp(table_key.Name, name) == 0)
+		if (table_key.Char == Char)
 			return table_key;
 	}
 
-	throw UnknownKeycode(name);
+	std::ostringstream os;
+	os << "<Char " << hex_encode((char*) &Char, sizeof(wchar_t)) << ">";
```
Comment (appgurueu) [inline src/client/keycode.cpp:257]: unused

File: irr/src/CIrrDeviceSDL.cpp [hunk 3]
```diff
@@ -267,6 +267,32 @@ int CIrrDeviceSDL::findCharToPassToIrrlicht(uint32_t sdlKey, EKEY_CODE irrlichtK
...
+		}
+	} else {
+		keynum = std::get<wchar_t>(key);
+	}
+	return SDL_GetScancodeFromKey(keynum);
+}
+
+KeyCode CIrrDeviceSDL::getKeyFromScancode(const u32 scancode) const
+{
+	auto keycode = SDL_GetKeyFromScancode((SDL_Scancode)scancode);
```
Comment (appgurueu) [inline irr/src/CIrrDeviceSDL.cpp:289]: Why not make the parameter `SDL_Scancode` to begin with?

File: irr/src/CIrrDeviceSDL.cpp [hunk 4]
```diff
@@ -858,18 +884,31 @@ bool CIrrDeviceSDL::run()
...
+				scancode = SDL_SCANCODE_ESCAPE;
+				keysym = SDLK_ESCAPE;
+			}
 
+			const auto &entry = KeyMap.find(keysym);
 			EKEY_CODE key;
-			if (idx == -1)
-				key = (EKEY_CODE)0;
+			if (entry == KeyMap.end())
+				key = (EKEY_CODE)KEY_UNKNOWN;
```
Comment (appgurueu) [inline irr/src/CIrrDeviceSDL.cpp:906]:
```suggestion
				key = KEY_UNKNOWN;
```

could also just make this a ternary

File: irr/src/CIrrDeviceSDL.cpp [hunk 5]
```diff
@@ -267,6 +267,32 @@ int CIrrDeviceSDL::findCharToPassToIrrlicht(uint32_t sdlKey, EKEY_CODE irrlichtK
 	}
 }
 
+u32 CIrrDeviceSDL::getScancodeFromKey(const KeyCode &key) const
+{
+	u32 keynum = 0;
+	if (key.index() == 0) {
+		auto keycode = std::get<EKEY_CODE>(key);
+		for (const auto &entry: KeyMap) {
```
Comment (appgurueu) [inline irr/src/CIrrDeviceSDL.cpp:275]: (In principle this is screaming for a bidirectional mapping but I don't think this is a performance concern?)

Comment (y5nw) [reply irr/src/CIrrDeviceSDL.cpp:275]: IMO this is hardly a performance concern. With the SDL device this is run when the `KeyPress` object is created from the keycode syntax, which mostly happens when the keybindings (and only ones that are configured as keycodes) are read from the settings (i.e. on startup).

File: irr/include/IrrlichtDevice.h [hunk 6]
```diff
@@ -337,6 +337,41 @@ class IrrlichtDevice : public virtual IReferenceCounted
...
+			key.emplace<wchar_t>(scancode - KEY_KEY_CODES_COUNT);
+		return key;
+	}
+
+protected:
+
+	// TODO: This is just some boilerplate for non-SDL devices. Remove this once we fully switch to SDL.
+	void fillScancode(SEvent &irrevent)
+	{
+		auto &keyinput = irrevent.KeyInput;
```
[the remark this answers is not in the document]
Comment (y5nw) [reply irr/include/IrrlichtDevice.h]: Looks like this should actually not be `const` as the goal is to fill out `irrevent.KeyInput.SystemKeyCode` from other fields in the key input.

File: irr/src/CIrrDeviceLinux.cpp [hunk 7]
```diff
@@ -862,10 +862,19 @@ bool CIrrDeviceLinux::run()
 
 				irrevent.EventType = irr::EET_KEY_INPUT_EVENT;
 				irrevent.KeyInput.PressedDown = false;
-				irrevent.KeyInput.Char = 0; // on release that's undefined
 				irrevent.KeyInput.Control = (event.xkey.state & ControlMask) != 0;
 				irrevent.KeyInput.Shift = (event.xkey.state & ShiftMask) != 0;
 				irrevent.KeyInput.Key = getKeyCode(event);
+				{ // Pass a char on release as well since this is needed for the scancode stub.
```
[the remark this answers is not in the document]
Comment (y5nw) [reply irr/src/CIrrDeviceLinux.cpp:868]: > This fragment seems a bit weird to me:

TL;DR: it is weird.

As for where this came from: this is actually copied from around ~50 lines further down the source file (and apparently was around before IrrlichtMT was fored). I copied this under the impression that it "just works" without seriously looking into this too carefully. Turns out this is a huge WTF.

> In the call to `XLookupString`, `tmp.buf` and `sizeof(tmp.buf)` are passed. The man page indicates to me that `XLookupString` will write a couple characters there. But afterwards, a different union field, `wbuf` is accessed. [...]
> 
> Is just converting to `wchar_t` in this manner correct? Doesn't this assume that an UTF-32 encoding is used? 

_Ideally_ we would use `XmbLookupString` or `XwcLookupString` here, in which case we would use `mbtowc` (or something similar), but these two [should only be used in `KeyPress` events](https://linux.die.net/man/3/xwclookupstring), so that becomes irrelevant here.

So we use `XLookupString`, which actually returns the string [in the ISO-8859-1 encoding](https://linux.die.net/man/3/xlookupstring), which is compatible with Unicode in the 0x80-0xFF range, so IMO a direct cast to `wchar_t` should be fine.

(By the way, I originally copied only this snippet because I thought that the input context would not be relevant here, which is apparently different thing.)

> Doesn't this make endianness assumptions?

Apparently yes. It seems like nobody so far has noticed this because it requires a setup with a big endian machine _and_ (until now) where `XInputContext` is not available.

> Furthermore, the return value of `XLookupString`, the number of characters written to `buf`, is ignored. Arguably this is probably fine if the endianness checks out because the rest has been zero-initialized, but again not quite obvious to the reader.

IMO this is (aside from the endianness) not really an issue because we only need the first character (see below).

> Also, why can / do we want to ignore `wbuf[1]`?

I don't think we have any reason to consider the present of a second character. Irrlicht's keypress/keyrelease events only use one character.

---

I think I will change this to `irrevent.KeyInput.Char = buf[0]` (to address the endianness issue) as I don't think there is anything else I can do about this mess.

File: src/client/keycode.cpp [hunk 8]
```diff
@@ -236,122 +238,122 @@ static const struct table_key table[] = {
...
-	else
-		ret = lookup_keychar(Char).LangName;
-	return ret ? ret : "<Unnamed key>";
+	return lookup_scancode(scancode).Char;
 }
 
-const KeyPress EscapeKey("KEY_ESCAPE");
+bool KeyPress::loadFromScancode(std::string_view name)
+{
+	if (name.size() < 2 || name[0] != '<')
```
[the remark this answers is not in the document]
Comment (y5nw) [reply src/client/keycode.cpp]: > That might be a tad bit cleaner with `std::stoul`.

Not really. I made this stricter by also checking that the end pointer points exactly at the ending `>` character. With `std::stoul` this would not work well because it would additionally involve constructing (and, with said pointer check, keeping) a `std::string`, which could be avoided with `std::strtoul`.

**Comment by sfence** [comment]
I tried changing the viewing range on Linux:
5.9.0 version reacts to `+` and `-` keys on the numeric part of the keyboard and also on `-` and `=` keys in the alphanumeric part.
Version from this branch reacts only on `-` and `=` keys in the alphanumeric part.

The same behaviors I see on Windows with the build from this branch vs the 5.9.0 version.

**Comment by y5nw** [comment]
> 5.9.0 version reacts to `+` and `-` keys on the numeric part of the keyboard and also on `-` and `=` keys in the alphanumeric part.
> Version from this branch reacts only on `-` and `=` keys in the alphanumeric part.

IMO this an implication of using scancodes for keybindings: the current master binds to both a keycode and a character, but with scancodes this only makes sense in a limited number of cases. This can also be observed with the shift key: with this PR sneaking is bound to left shift, so presssing the right shift key does not work.

I would prefer addressing this with a follow-up PR that allows binding to multiple keys. The default can then be adjusted accordingly.

**Comment by sfence** [comment]
Understand. The second PR for binding multiple keys should be part of 5.10.0 if we want to enable SDL as default. Otherwise, players will be confused.

**Comment by y5nw** [comment]
> Our of curiosity: is there a particular reason why the notation `<number>` is used? That seems overly cryptic compared to a possible `KEY_SCANCODE_number` format.

For some reason `<num>` was the first thing that I came up with. I would also be fine with e.g. `SYSTEM_SCANCODE_num`, but I am slightly concerned that this can be confused with `SDL_SCANCODE_x` values.

File: irr/src/CIrrDeviceSDL.cpp (hunk 3 above)
Comment (y5nw) [reply irr/src/CIrrDeviceSDL.cpp]: Update now that I think about this again: another approach here would be to limit scancodes to SDL and put scancode-related logic behind `#ifdef _IRR_COMPILE_WITH_SDL_DEVICE_` guards. This would also avoid issues arising from the awkward non-SDL scancode workaround in the current form of the PR.

File: irr/src/CIrrDeviceLinux.cpp (hunk 7 above)
[the remark this answers is not in the document]
Comment (y5nw) [reply irr/src/CIrrDeviceLinux.cpp]: Resolving this since I have reverted changes to non-SDL `IrrlichtDevice`s.

(Note that the issue mentioned here is still present in the existing code, but fixing that is outside the scope of this PR.)

**Comment by appgurueu** [comment]
> Observe that existing keybinding settings are loaded and converted to scancodes based on the keyboard layout used when Minetest is started.

There seem to be some issues with this. I'm using a standard German keyboard layout. Here's a screenshot of the controls:
Screenshot from 2024-12-23 17-02-01

The letters are mostly fine, but Z for zoom has become Y instead, which suggests it's somehow using an English keyboard layout. Similarly, ß for decreasing range and <46> for increasing range don't make much sense; again I think they might correspond to how the scancodes would be on an English keyboard layout. Also `-` for commands?

Binding arbitrary keys (including Fn keys, numpad, insert, ü, etc.) works. Bindings are saved as scancodes and continue to work when changing the keyboard layout. Escape works; I have not tested the Android back key yet.

**Comment by y5nw** [comment]
> The letters are mostly fine, but Z for zoom has become Y instead, which suggests it's somehow using an English keyboard layout. Similarly, ß for decreasing range and <46> for increasing range don't make much sense; again I think they might correspond to how the scancodes would be on an English keyboard layout.

I think there is a catch here: the `guiKeyChangeMenu` only saves the keybinding if it differs from the default:

https://github.com/minetest/minetest/blob/c49ff769553960183f1f092d71d25858d963d872/src/gui/guiKeyChangeMenu.cpp#L209-L217

As keybindings that are not different from the defaults are not saved, the result is that they are bound to potentially different keys if the default keybinidng is changed, which I assume is that happened here as the default keys in this PR are now based on scancodes (with the exception of the F1-F12 keys since I did not take the time to look up their numeric scancodes).

The `<46>` key is the dead acute/grave key to the right of the `ß` key on the German keyboard. The numeric scancode is shown since SDL doesn't provide a sensible keycode value for dead keys. (Demonstrated in https://github.com/minetest/minetest/issues/13904#issuecomment-1777959803 ; but aside from that the Luanti source code doesn't seem able to use SDL headers aside from Andorid builds)

> Also `-` for commands?

I chose to use scancodes as the default key since it is sometimes hard to find a sensible default otherwise. Note that we can't use Shift-7 here because of #14545, so I chose the scancode for the `/` key on the US layout.

Related: https://irc.minetest.net/minetest-dev/2024-11-10#i_6216414

File: builtin/settingtypes.txt [hunk 9]
```diff
@@ -151,6 +151,16 @@ enable_hotbar_mouse_wheel (Hotbar: Enable mouse wheel for selection) bool true
 #    Requires: keyboard_mouse
 invert_hotbar_mouse_wheel (Hotbar: Invert mouse wheel direction) bool false
 
+#    SDL only: Save key controls as scancodes (position on the keyboard) instead of keycodes (the
```
Comment (sfan5) [inline builtin/settingtypes.txt:154]: we aim to default to sdl, so IMO we should ignore the "non-sdl" case in descriptions and such

File: builtin/settingtypes.txt [hunk 10]
```diff
@@ -151,6 +151,16 @@ enable_hotbar_mouse_wheel (Hotbar: Enable mouse wheel for selection) bool true
...
+#    symbol marked on the key). This allows using the same physical keys with multiple
+#    keyboard layouts, but the new scancode-based settings can not be parsed by older clients.
```
Comment (sfan5) [inline builtin/settingtypes.txt:156]: "the new scancode-based settings can not be parsed by older clients."
this does not deserve mentioning since it applies to all new/changed settings

File: builtin/settingtypes.txt [hunk 11]
```diff
@@ -151,6 +151,16 @@ enable_hotbar_mouse_wheel (Hotbar: Enable mouse wheel for selection) bool true
...
+#    Note that this only affects how keybindings are saved in the settings. In particular,
+#    key controls are always matched based on scancodes regardless of this setting if SDL is used.
+#    Key controls are matched based on keycodes for non-SDL devices.
+#
+#    Requires: !touch_controls
```
Comment (sfan5) [inline builtin/settingtypes.txt:161]: no other key settings are gated behind this, so I don't think this should be either.

File: irr/include/IrrlichtDevice.h [hunk 12]
```diff
@@ -342,6 +343,20 @@ class IrrlichtDevice : public virtual IReferenceCounted
 	{
 		return video::isDriverSupported(driver);
 	}
+
+#if defined(_IRR_COMPILE_WITH_SDL_DEVICE_) || USE_SDL2
```
Comment (sfan5) [inline irr/include/IrrlichtDevice.h:347]: i dont think this ifdef is needed

File: irr/src/CIrrDeviceSDL.cpp [hunk 13]
```diff
@@ -27,6 +29,14 @@
 
 #include "CSDLManager.h"
 
+// Since SDL doesn't have mouse keys as keycodes we fall back to EKEY_CODE
+static const std::unordered_set<irr::EKEY_CODE> fake_keys = {
+	irr::KEY_LBUTTON, irr::KEY_MBUTTON, irr::KEY_RBUTTON, irr::KEY_XBUTTON1, irr::KEY_XBUTTON2
+};
+static inline bool is_fake_key(irr::EKEY_CODE key) {
+	return fake_keys.find(key) != fake_keys.end();
+}
```
Comment (sfan5) [inline irr/src/CIrrDeviceSDL.cpp:38]: personally I would have used a switch-case here, no need for a data structure

File: irr/src/CIrrDeviceSDL.cpp [hunk 14]
```diff
@@ -220,6 +230,51 @@ int CIrrDeviceSDL::findCharToPassToIrrlicht(uint32_t sdlKey, EKEY_CODE irrlichtK
 	}
 }
 
+// Irrlicht has some EKEY_CODE entries that only appear to make sense in a SDL-scancode-like context.
+// These keycodes are passed by (in particular) the X11 IrrlichtDevice.
+// Perform one-way conversion if we encounter them.
+std::unordered_map<EKEY_CODE, SDL_Scancode> ekey_scancodes = {
```
Comment (sfan5) [inline irr/src/CIrrDeviceSDL.cpp:236]: missing const static

File: irr/src/CIrrDeviceSDL.cpp [hunk 15]
```diff
@@ -220,6 +230,51 @@ int CIrrDeviceSDL::findCharToPassToIrrlicht(uint32_t sdlKey, EKEY_CODE irrlichtK
 	}
 }
 
+// Irrlicht has some EKEY_CODE entries that only appear to make sense in a SDL-scancode-like context.
+// These keycodes are passed by (in particular) the X11 IrrlichtDevice.
```
Comment (sfan5) [inline irr/src/CIrrDeviceSDL.cpp:234]: this is a bit confusing at first, because it's not like x11 and sdl can be active at the same time.
is this for the sake of sharing configs between them?

File: irr/include/Keycodes.h [hunk 16]
```diff
@@ -182,4 +183,29 @@ enum EKEY_CODE
 	KEY_KEY_CODES_COUNT = 0x100 // this is not a key, but the amount of keycodes there are.
 };
 
+class Keycode : public std::variant<EKEY_CODE, wchar_t> {
```
Comment (sfan5) [inline irr/include/Keycodes.h:186]:
```c
// A Keycode is either a character produced by the key or one of Irrlicht's codes (EKEY_CODE)
```
right?

File: irr/include/IrrlichtDevice.h [hunk 17]
```diff
@@ -342,6 +343,20 @@ class IrrlichtDevice : public virtual IReferenceCounted
...
+	//! Get the scancode of the corresponding keycode.
+	virtual std::variant<u32, EKEY_CODE> getScancodeFromKey(const Keycode &key) const {
```
Comment (sfan5) [inline irr/include/IrrlichtDevice.h:349]: the u32 type represent an implementation-defined code for the key, is that correct?
please document this better

File: irr/src/CIrrDeviceSDL.cpp [hunk 18]
```diff
@@ -220,6 +230,51 @@ int CIrrDeviceSDL::findCharToPassToIrrlicht(uint32_t sdlKey, EKEY_CODE irrlichtK
...
+std::variant<u32, EKEY_CODE> CIrrDeviceSDL::getScancodeFromKey(const Keycode &key) const
+{
+	u32 keynum = 0;
+	if (const auto *keycode = std::get_if<EKEY_CODE>(&key)) {
+		if (is_fake_key(*keycode))
+			return *keycode;
+		if (const auto &ent = ekey_scancodes.find(*keycode); ent != ekey_scancodes.end())
+			return ent->second;
+		for (const auto &entry: KeyMap) {
+			if (entry.second == *keycode) {
```
Comment (sfan5) [inline irr/src/CIrrDeviceSDL.cpp:258]: this is comparing an SDL_Scancode to an EKEY_CODE, why?

File: irr/src/CIrrDeviceSDL.h [hunk 19]
```diff
@@ -319,28 +324,13 @@ class CIrrDeviceSDL : public CIrrDeviceStub
...
-		s32 Win32Key;
-
-		bool operator<(const SKeyMap &o) const
-		{
-			return SDLKey < o.SDLKey;
-		}
-	};
-
-	core::array<SKeyMap> KeyMap;
+	std::unordered_map<s32, EKEY_CODE> KeyMap;
```
Comment (sfan5) [inline irr/src/CIrrDeviceSDL.h:327]: should be u32

File: src/client/keycode.cpp [hunk 20]
```diff
@@ -6,15 +6,17 @@
...
 #include "util/basic_macros.h"
+#include <vector>
 
 struct table_key {
-	const char *Name;
+	std::string Name;
 	irr::EKEY_CODE Key;
 	wchar_t Char; // L'\0' means no character assigned
-	const char *LangName; // NULL means it doesn't have a human description
+	std::string LangName; // NULL means it doesn't have a human description
```
Comment (sfan5) [inline src/client/keycode.cpp:19]: comment wrong

File: src/client/keycode.cpp [hunk 21]
```diff
@@ -221,122 +223,177 @@ static const struct table_key table[] = {
...
+
 	for (const auto &table_key : table) {
-		if (strcmp(table_key.Name, name) == 0)
+		if (table_key.Char == Char)
 			return table_key;
 	}
 
-	throw UnknownKeycode(name);
+	auto newsym = wide_to_utf8(std::wstring_view(&Char, 1));
+	table_key new_key {newsym, irr::KEY_KEY_CODES_COUNT, Char, newsym};
```
Comment (sfan5) [inline src/client/keycode.cpp:242]: this needs some explanation

File: src/client/keycode.cpp [hunk 22]
```diff
@@ -221,122 +223,177 @@ static const struct table_key table[] = {
...
-	os << "<Char " << hex_encode((char*) &Char, sizeof(wchar_t)) << ">";
-	throw UnknownKeycode(os.str().c_str());
+	auto wname = utf8_to_wide(name);
+	if (wname.empty())
+		return invalid_key;
+	return lookup_keychar(wname[0]);
 }
 
-KeyPress::KeyPress(const char *name)
+#if USE_SDL2
```
Comment (sfan5) [inline src/client/keycode.cpp:275]: same here. `IrrlichtDevice` has a fallback implementation so no need to make it more complicated than necessary

File: src/client/keycode.h [hunk 23]
```diff
@@ -4,62 +4,86 @@
...
 // Global defines for convenience
-
-extern const KeyPress EscapeKey;
-
-extern const KeyPress LMBKey;
-extern const KeyPress MMBKey; // Middle Mouse Button
-extern const KeyPress RMBKey;
+// This implementation defers creation of the objects to make sure that the
+// IrrlichtDevice is initialized.
+#define EscapeKey KeyPress::getSpecialKey("KEY_ESCAPE")
```
Comment (sfan5) [inline src/client/keycode.h:80]: I must have missed it but which information does `KeyPress` hold that is not available without an SDL device?
the scancode?
and it wouldn't work if it contained `irr::KEY_ESCAPE`?

File: src/defaultsettings.cpp [hunk 24]
```diff
@@ -129,7 +130,43 @@ void set_default_settings()
...
+	settings->setDefault("keymap_backward", "<22>");
+	settings->setDefault("keymap_left", "<4>");
+	settings->setDefault("keymap_right", "<7>");
+	settings->setDefault("keymap_jump", "<44>");
+	settings->setDefault("keymap_sneak", "KEY_LSHIFT");
+	settings->setDefault("keymap_dig", "KEY_LBUTTON");
+	settings->setDefault("keymap_place", "KEY_RBUTTON");
+	settings->setDefault("keymap_drop", "<20>");
+	settings->setDefault("keymap_zoom", "<29>");
+	settings->setDefault("keymap_inventory", "<12>");
```
Comment (sfan5) [inline src/defaultsettings.cpp:146]: can we add comments here to say which these map to on an US keyboard?

**Review by sfan5 — COMMENTED** [review]
After reviewing this I feel like I understand less than before.

File: builtin/settingtypes.txt (hunk 11 above)
Comment (grorp) [reply builtin/settingtypes.txt:161]: The correct one to use is `#    Requires: keyboard_mouse`

File: builtin/settingtypes.txt (hunk 9 above)
Comment (y5nw) [reply builtin/settingtypes.txt]: I removed non-SDL-related explanations in d34dc3520f03af854948ad51d3b609a73c2eb250.

File: builtin/settingtypes.txt (hunk 10 above)
Comment (y5nw) [reply builtin/settingtypes.txt]: Removed in d34dc3520f03af854948ad51d3b609a73c2eb250.

File: builtin/settingtypes.txt (hunk 11 above)
Comment (y5nw) [reply builtin/settingtypes.txt]: Fixed in d34dc3520f03af854948ad51d3b609a73c2eb250.

File: irr/include/IrrlichtDevice.h (hunk 12 above)
Comment (y5nw) [reply irr/include/IrrlichtDevice.h]: Anyway I dropped this ifdef in e13e1bc92603b2962170ecb7c050b2fd4af1951c.

File: irr/include/Keycodes.h (hunk 16 above)
Comment (y5nw) [reply irr/include/Keycodes.h:187]: Right. I added this annotation in 9590be17f121b09c78bd9f1d28dba0603049ec29.

File: src/client/keycode.cpp (hunk 20 above)
Comment (y5nw) [reply src/client/keycode.cpp]: Corrected in 9590be17f121b09c78bd9f1d28dba0603049ec29.

**Comment by sfan5** [comment]
> The issue we have here is that the actual implementation sends `EKEY_CODE` based on keycodes instead of scancodes. E.g. the keymap from the X11 device has these entries:

Okay, I see. Let's scratch that point then and it will not entirely work correctly on old devices.

Still reusing `EKEY_CODE` would avoid much of the complexity in this PR (for an initial implementation), wouldn't it?

> Ideally we should only need to look at the scancode and not look at the char at all.

Yeah.

> Then we would have the issue here of using EKEY_CODE inconsistently as scancodes and keycodes depending on whether we use SDL or not.

The thing is: When we get the switch to scancodes done there is no reason to still use the old devices, so we can ignore this problem.
Either this PR is merged and we ship 5.11 with SDL, or it isn't and we revert to X11/WIN32/OSX for yet another release.

**Comment by Zughy** [comment]
> Either this PR is merged and we ship 5.11 with SDL

Yes, please, it's been two releases (3 with this) we've been telling the public that we're switching to SDL

**Comment by sfan5** [comment]
Here's a proof of concept of what I am proposing with basic things working.
One way to tell that it works is on a German layout zoom is suddenly on Y instead of Z.
```diff
diff --git a/irr/src/CIrrDeviceSDL.cpp b/irr/src/CIrrDeviceSDL.cpp
index f7974202f..1c25b7cb0 100644
--- a/irr/src/CIrrDeviceSDL.cpp
+++ b/irr/src/CIrrDeviceSDL.cpp
@@ -815,7 +815,7 @@ bool CIrrDeviceSDL::run()
 		case SDL_KEYDOWN:
 		case SDL_KEYUP: {
 			SKeyMap mp;
-			mp.SDLKey = SDL_event.key.keysym.sym;
+			mp.SDLKey = SDL_event.key.keysym.scancode;
 			s32 idx = KeyMap.binary_search(mp);
 
 			EKEY_CODE key;
@@ -836,8 +836,7 @@ bool CIrrDeviceSDL::run()
 			irrevent.KeyInput.PressedDown = (SDL_event.type == SDL_KEYDOWN);
 			irrevent.KeyInput.Shift = (SDL_event.key.keysym.mod & KMOD_SHIFT) != 0;
 			irrevent.KeyInput.Control = (SDL_event.key.keysym.mod & KMOD_CTRL) != 0;
-			irrevent.KeyInput.Char = findCharToPassToIrrlicht(mp.SDLKey, key,
-					(SDL_event.key.keysym.mod & KMOD_NUM) != 0);
+			irrevent.KeyInput.Char = 0;
 			postEventFromUser(irrevent);
 		} break;
 
@@ -1306,6 +1305,7 @@ void CIrrDeviceSDL::createKeyMap()
 
 	// buttons missing
 
+#if 0
 	// Android back button = ESC
 	KeyMap.push_back(SKeyMap(SDLK_AC_BACK, KEY_ESCAPE));
 
@@ -1434,6 +1434,22 @@ void CIrrDeviceSDL::createKeyMap()
 	KeyMap.push_back(SKeyMap(SDLK_COMMA, KEY_COMMA));
 	KeyMap.push_back(SKeyMap(SDLK_MINUS, KEY_MINUS));
 	KeyMap.push_back(SKeyMap(SDLK_PERIOD, KEY_PERIOD));
+#endif
+
+	KeyMap.push_back(SKeyMap(SDL_SCANCODE_A, KEY_KEY_A));
+	KeyMap.push_back(SKeyMap(SDL_SCANCODE_D, KEY_KEY_D));
+	KeyMap.push_back(SKeyMap(SDL_SCANCODE_E, KEY_KEY_E));
+	KeyMap.push_back(SKeyMap(SDL_SCANCODE_I, KEY_KEY_I));
+	KeyMap.push_back(SKeyMap(SDL_SCANCODE_Q, KEY_KEY_Q));
+	KeyMap.push_back(SKeyMap(SDL_SCANCODE_S, KEY_KEY_S));
+	KeyMap.push_back(SKeyMap(SDL_SCANCODE_W, KEY_KEY_W));
+	KeyMap.push_back(SKeyMap(SDL_SCANCODE_Z, KEY_KEY_Z));
+	KeyMap.push_back(SKeyMap(SDL_SCANCODE_V, KEY_KEY_V));
+	KeyMap.push_back(SKeyMap(SDL_SCANCODE_ESCAPE, KEY_ESCAPE));
+	KeyMap.push_back(SKeyMap(SDL_SCANCODE_F10, KEY_F10));
+	KeyMap.push_back(SKeyMap(SDL_SCANCODE_LSHIFT, KEY_LSHIFT));
+	KeyMap.push_back(SKeyMap(SDL_SCANCODE_RETURN, KEY_RETURN));
+	KeyMap.push_back(SKeyMap(SDL_SCANCODE_SPACE, KEY_SPACE));
 
 	// some special keys missing
 
diff --git a/src/client/keycode.cpp b/src/client/keycode.cpp
index 0a3b0db3f..813c72697 100644
--- a/src/client/keycode.cpp
+++ b/src/client/keycode.cpp
@@ -196,6 +196,7 @@ static const struct table_key table[] = {
 	DEFINEKEY1(KEY_OEM_CLEAR, N_("OEM Clear"))
 
 	// Keys without Irrlicht keycode
+#if 0
 	DEFINEKEY5("!")
 	DEFINEKEY5("\"")
 	DEFINEKEY5("#")
@@ -219,6 +220,7 @@ static const struct table_key table[] = {
 	DEFINEKEY5("]")
 	DEFINEKEY5("^")
 	DEFINEKEY5("_")
+#endif
 };
 
 #undef N_
@@ -299,7 +301,7 @@ KeyPress::KeyPress(const char *name)
 
 KeyPress::KeyPress(const irr::SEvent::SKeyInput &in, bool prefer_character)
 {
-	if (prefer_character)
+	if (prefer_character && false)
 		Key = irr::KEY_KEY_CODES_COUNT;
 	else
 		Key = in.Key;
diff --git a/src/client/keycode.h b/src/client/keycode.h
index 4c63be7fa..02d2a3cb8 100644
--- a/src/client/keycode.h
+++ b/src/client/keycode.h
@@ -31,7 +31,7 @@ class KeyPress
 
 	bool operator==(const KeyPress &o) const
 	{
-		return (Char > 0 && Char == o.Char) || (valid_kcode(Key) && Key == o.Key);
+		return Key == o.Key;
 	}
 
 	const char *sym() const;
```

> We'd start losing credibility if we postponed it yet again

Realistically I doubt that many people even know or care, but sure.

**Comment by y5nw** [comment]
> Still reusing `EKEY_CODE` would avoid much of the complexity in this PR (for an initial implementation), wouldn't it?

Yes, but I am not sure whether it makes sense to strip this PR back down given that it already works well. In particular, this PR also reformats the lookup table in the SDL devices and refactors `keycode.cpp`, both of which are not strictly necessary for this PR, but moving these to separate PRs at this point would IMO only increase the amount of work we need.

> Either this PR is merged and we ship 5.11 with SDL, or it isn't and we revert to X11/WIN32/OSX for yet another release.

I'm afraid we might be a bit late at this point. We still need #14874 (to address #14545) which needs to be rebased once we merge this PR.

**Comment by sfan5** [comment]
IRC discussion during meeting https://irc.minetest.net/minetest-dev/2025-01-19#i_6236115

> Yes, but I am not sure whether it makes sense to strip this PR back down given that it already works well and includes some work beyond a bare-bones implementation.

Sure, I understand this argument. I just feel the additional complexity won't serve us well.

**Comment by sfan5** [comment]
Future steps, as proposed:
1. We agree on the following:
 - Settings don't need to be backwards-compatible (mainmenu dialog needed!)
 - Settings don't need to be forwards-compatible
 - Immediately breaking all non-SDL devices is okay
2. PR is reworked as needed (e.g. to remove unnecessary compat)
3. We merge it early in the 5.12 cycle and work on issues that crop up.
4. ???
5. Profit

**Comment by y5nw** [comment]
>     * (mainmenu dialog needed!)

+1. Although I would prefer having this in a different PR. (Also: do we have code to check whether the user upgraded from a preivous version? Or would we simply check whether the user has settings based on keycodes?)

>     * Settings don't need to be forwards-compatible

Agreed. The current numeric scancodes are a temporary/fallback solution anyway; I would personally prefer naming keys based on SDL scancodes as such names are IMO much easier to work with.

(Note that SDL [renamed](https://wiki.libsdl.org/SDL3/README/migration#sdl_scancodeh) certain scancodes from SDL2 to SDL3.)

>     * Immediately breaking all non-SDL devices is okay

I sort of did: the modified `GUIKeyChangeMenu` no longer considers modifier keys, so it is no longer possible to _bind_ to e.g. Shift-7 for `/` even on non-SDL devices.

The main limitation here is that SDL headers are not exposed to Luanti except for Android builds, which limits our ability to use e.g. SDL scancodes directly.

>     2. PR is reworked as needed (e.g. to remove unnecessary compat)

Aside from keeping the PR _buildable_ with non-SDL devices (and without SDL headers, as I mentioned above), the other piece of compat code involves keeping compatibility with keycodes. I am largely not sure whether we want to (at least) _attempt_ to help migrate user settings to scancodescodes. Note that we currently cannot drop `EKEY_CODE` yet due to the lack of SDL headers. I still need to figure out how to work with cmake, so I would prefer having a follow-up PR to require SDL - or would we merge such a PR before this one?

>     3. We merge it early in the 5.12 cycle and work on issues that crop up.

I suppose I will just request a review when I finish some of the cleanup (and rebase).

Another idea here is to tag (in what name?) such an SDL build to make users aware of the oncoming change.

**Comment by sfan5** [comment]
> Although I would prefer having this in a different PR

Sure.

> Also: do we have code to check whether the user upgraded from a preivous version? Or would we simply check whether the user has settings based on keycodes?

Both would work. The former could be implemented like [here](https://github.com/luanti-org/luanti/blob/master/builtin/mainmenu/dlg_reinstall_mtg.lua).

> I still need to figure out how to work with cmake, so I would prefer having a follow-up PR to require SDL - or would we merge such a PR before this one?

Requiring SDL needs to come after this. We can't do everything in one big step.

File: irr/src/CIrrDeviceSDL.cpp (hunk 15 above)
Comment (y5nw) [reply irr/src/CIrrDeviceSDL.cpp]: I dropped the the conversion code from OEM keys and scancodes because we now ask users to rebind anyway. Resolving.

**Comment by mruncreative** [comment]
Inputs being string based rather than key position based annoys me every single time. It doesn't even use my currently selected layout but the first one in the list of selected keyboard layouts just like Wine.
> We will end up (one way or another) requiring requiring some users to rebind their keys regardless of what we choose as the default.
I don't care if you destroy my keyboard configuration. I can just reset it somehow. It's not valuable. It's more important that it works consistently and position based.

File: irr/src/CIrrDeviceSDL.cpp [hunk 25]
```diff
@@ -1311,142 +1366,135 @@ void CIrrDeviceSDL::createKeyMap()
...
 	// buttons missing
 
-	// Android back button = ESC
-	KeyMap.push_back(SKeyMap(SDLK_AC_BACK, KEY_ESCAPE));
-
-	KeyMap.push_back(SKeyMap(SDLK_BACKSPACE, KEY_BACK));
-	KeyMap.push_back(SKeyMap(SDLK_TAB, KEY_TAB));
-	KeyMap.push_back(SKeyMap(SDLK_CLEAR, KEY_CLEAR));
-	KeyMap.push_back(SKeyMap(SDLK_RETURN, KEY_RETURN));
+	KeyMap.emplace(SDLK_BACKSPACE, KEY_BACK);
```
Comment (sfan5) [inline irr/src/CIrrDeviceSDL.cpp:1371]: what I still don't understand is why are we mapping keycodes here? isn't this supposed to be scancodes?

File: irr/src/CIrrDeviceSDL.h [hunk 26]
```diff
@@ -322,28 +327,13 @@ class CIrrDeviceSDL : public CIrrDeviceStub
...
-	};
-
-	core::array<SKeyMap> KeyMap;
+	std::unordered_map<SDL_Keycode, EKEY_CODE> KeyMap;
 	SDL_SysWMinfo Info;
 
 	s32 CurrentTouchCount;
 	bool IsInBackground;
+
+	std::unordered_set<SDL_Scancode> escapeKeys;
```
Comment (sfan5) [inline irr/src/CIrrDeviceSDL.h:336]: fwiw considering this has a very low amount of elements a `std::set` would be more efficient

File: src/client/keycode.cpp (hunk 21 above)
Comment (sfan5) [reply src/client/keycode.cpp:243]: this seems to imply we need to be able to return valid data for any wchar. why is that?

File: src/client/keycode.cpp [hunk 27]
```diff
@@ -221,122 +223,153 @@ static const struct table_key table[] = {
...
-const KeyPress LMBKey("KEY_LBUTTON");
-const KeyPress MMBKey("KEY_MBUTTON");
-const KeyPress RMBKey("KEY_RBUTTON");
+bool KeyPress::loadFromScancode(std::string_view name)
+{
+#if USE_SDL2
+	if (name.size() < 2 || name[0] != '<' || name.back() != '>')
+		return false;
+	char *p;
+	const auto code = strtoul(name.data()+1, &p, 10);
```
Comment (sfan5) [inline src/client/keycode.cpp:355]: string_view does not guarantee null termination, so this is not safe

File: src/client/keycode.cpp [hunk 28]
```diff
@@ -221,122 +223,153 @@ static const struct table_key table[] = {
...
+		return false;
+	scancode.emplace<u32>(code);
+	return true;
+#else
+	return false;
+#endif
+}
+
+std::unordered_map<std::string, KeyPress> KeyPress::specialKeyCache;
+const KeyPress &KeyPress::getSpecialKey(const std::string &name)
```
Comment (sfan5) [inline src/client/keycode.cpp:366]: string_view

File: src/client/keycode.cpp [hunk 29]
```diff
@@ -345,23 +378,18 @@ const KeyPress RMBKey("KEY_RBUTTON");
...
-const KeyPress &getKeySetting(const char *settingname)
+const KeyPress &getKeySetting(const std::string &settingname)
 {
 	auto n = g_key_setting_cache.find(settingname);
 	if (n != g_key_setting_cache.end())
 		return n->second;
 
 	auto &ref = g_key_setting_cache[settingname];
-	ref = g_settings->get(settingname).c_str();
+	ref = std::string_view(g_settings->get(settingname));
```
Comment (sfan5) [inline src/client/keycode.cpp:388]: would show the intent clearer IMO
```suggestion
	ref = KeyPress(g_settings->get(settingname));
```

File: src/client/keycode.h [hunk 30]
```diff
@@ -4,62 +4,70 @@
 
 #pragma once
 
-#include "exceptions.h"
 #include "irrlichttypes.h"
+#include "cmake_config.h" // USE_SDL2
```
Comment (sfan5) [inline src/client/keycode.h:8]: not used in header

File: src/client/keycode.h [hunk 31]
```diff
@@ -4,62 +4,70 @@
...
+	KeyPress(std::string_view name);
 
-	KeyPress(const irr::SEvent::SKeyInput &in, bool prefer_character = false);
+	KeyPress(const irr::SEvent::SKeyInput &in);
 
-	bool operator==(const KeyPress &o) const
+	std::string sym() const;
+	std::string name() const;
+
+	irr::EKEY_CODE getKeycode() const;
```
Comment (sfan5) [inline src/client/keycode.h:28]: can we document these with short comments? doesn't have to be the full doxygen form

File: src/client/keycode.h [hunk 32]
```diff
@@ -4,62 +4,70 @@
...
+			return *pv;
+		return 0;
 	}
 
-	const char *sym() const;
-	const char *name() const;
+	bool operator==(const KeyPress &o) const
+	{
+		return scancode == o.scancode;
+	}
```
Comment (sfan5) [inline src/client/keycode.h:41]:
```suggestion
	bool operator==(const KeyPress &o) const {
		return scancode == o.scancode;
	}
	bool operator!=(const KeyPress &o) const {
		return scancode != o.scancode;
	}
```

File: src/client/keycode.cpp [hunk 33]
```diff
@@ -221,122 +223,153 @@ static const struct table_key table[] = {
...
-			m_name = lookup_keykey(Key).Name;
-		else
-			m_name = lookup_keychar(Char).Name;
-	} catch (UnknownKeycode &e) {
-		m_name.clear();
-	};
+		scancode.emplace<irr::EKEY_CODE>(in.Key);
+#else
+	Keycode keycode(in.Key, in.Char);
+	scancode = RenderingEngine::get_raw_device()->getScancodeFromKey(keycode);
```
Comment (sfan5) [inline src/client/keycode.cpp:309]: should include a sanity_check before dereferencing the device

File: irr/src/CIrrDeviceSDL.cpp (hunk 25 above)
Comment (y5nw) [reply irr/src/CIrrDeviceSDL.cpp:1371]: This is used for `IrrlichtDevice::getKeyFromScancode` which the key change menu uses to present keys to users. (Ideally the latter/`KeyPress` should use SDL keycodes directly instead of such a map, but we currently cannot do that as we discussed earlier.)

File: src/client/keycode.cpp (hunk 21 above)
Comment (y5nw) [reply src/client/keycode.cpp:243]: This is mostly for convenience so that we have an entry to work with if the keychar is not listed in the lookup table.

For SDL devices this is also safe, since the only cases where we get invalid wchar values are
* From SDL, which we sanitize in `findCharToPassToIrrlicht`, or
* From user input (i.e. `minetest.conf`), in which case the keychar is then converted to the `SDL_SCANCODE_UNKNOWN`.

File: src/client/keycode.cpp (hunk 28 above)
Comment (y5nw) [reply src/client/keycode.cpp:378]: We need a `std::string` in the implementation for indexing `specialKeyCache` so I don't think using `string_view` here would bring much.

File: src/client/keycode.h (hunk 31 above)
Comment (y5nw) [reply src/client/keycode.h:31]: https://github.com/luanti-org/luanti/pull/14964/commits/b349b7aa21e55be312d9a1dc1e45947202b7b448

File: irr/src/CIrrDeviceSDL.h (hunk 26 above)
Comment (y5nw) [reply irr/src/CIrrDeviceSDL.h]: https://github.com/luanti-org/luanti/pull/14964/commits/b7c6e3ec8b6453ae0a1ef058f119e7ee55d37795

File: src/client/keycode.h (hunk 30 above)
Comment (y5nw) [reply src/client/keycode.h]: https://github.com/luanti-org/luanti/pull/14964/commits/604faac1c3a42bc51347bfea9dcad65b7bbf09f6

File: src/client/keycode.cpp (hunk 33 above)
Comment (y5nw) [reply src/client/keycode.cpp]: Like this: https://github.com/luanti-org/luanti/pull/14964/commits/106cb91b9665df101fde8b87b324c6f2754edf6c ?

File: irr/src/CIrrDeviceSDL.cpp (hunk 25 above)
Comment (sfan5) [reply irr/src/CIrrDeviceSDL.cpp:1375]: I see. Please write this down in a comment.

File: src/client/keycode.cpp (hunk 33 above)
Comment (sfan5) [reply src/client/keycode.cpp]: sure. I think it should even raise a warning if the device is not initialized yet. since that means the result won't be correct.

File: irr/src/CIrrDeviceSDL.cpp (hunk 25 above)
Comment (y5nw) [reply irr/src/CIrrDeviceSDL.cpp:1375]: 7ed10fb3e

File: src/client/keycode.cpp (hunk 33 above)
Comment (y5nw) [reply src/client/keycode.cpp]: 290498b37

File: src/client/inputhandler.cpp [hunk 34]
```diff
@@ -143,7 +143,7 @@ bool MyEventReceiver::OnEvent(const SEvent &event)
 	// Remember whether each key is down or up
 	if (event.EventType == irr::EET_KEY_INPUT_EVENT) {
 		const KeyPress keyCode(event.KeyInput);
-		if (keysListenedFor[keyCode]) {
+		if (keyCode && keysListenedFor[keyCode]) {
```
Comment (SmallJoker) [inline src/client/inputhandler.cpp:146]: It's not directly obvious what `keyCode` does in this case. It is intuitive for `std::optional` and pointer-like classes (`std::unique_ptr` ...). For example, the function definition wouldn't need a comment if the function was called `isValid`.
It's probably a subjective thing. Feel free to close this comment if you disagree.

File: src/client/keycode.cpp [hunk 35]
```diff
@@ -6,15 +6,17 @@
...
 #include "debug.h"
+#include "renderingengine.h"
 #include "util/hex.h"
 #include "util/string.h"
 #include "util/basic_macros.h"
+#include <vector>
 
 struct table_key {
-	const char *Name;
+	std::string Name;
```
Comment (SmallJoker) [inline src/client/keycode.cpp:16]: While we're already at it, a small improvement?
```suggestion
	std::string Name; // An EKEY_CODE 'symbol' name as a string
```

File: src/client/keycode.cpp [hunk 36]
```diff
@@ -221,122 +223,172 @@ static const struct table_key table[] = {
...
-			m_name = lookup_keychar(Char).Name;
-	} catch (UnknownKeycode &e) {
-		m_name.clear();
-	};
+std::string KeyPress::formatScancode() const
+{
+#if USE_SDL2
+	if (auto pv = std::get_if<u32>(&scancode))
+		return *pv == 0 ? "" : "<" + std::to_string(*pv) + ">";
+#endif
```
Comment (SmallJoker) [inline src/client/keycode.cpp:337]:
```suggestion
	if (USE_SDL2) {
		if (auto pv = std::get_if<u32>(&scancode))
			return *pv == 0 ? "" : "<" + std::to_string(*pv) + ">";
	}
```
This code does not depend on SDL2 during compile time, thus let's use that to ensure that the code path still compiles. The compiler will optimize it away.

File: src/client/keycode.cpp [hunk 37]
```diff
@@ -221,122 +223,172 @@ static const struct table_key table[] = {
...
+#if USE_SDL2
+	if (in.SystemKeyCode)
+		scancode.emplace<u32>(in.SystemKeyCode);
 	else
-		Key = in.Key;
-	Char = in.Char;
+		scancode.emplace<irr::EKEY_CODE>(in.Key);
+#else
+	loadFromKey(in.Key, in.Char);
+#endif
```
Comment (SmallJoker) [inline src/client/keycode.cpp:329]: Cannot add a code suggestion... thanks GitHub.
```C++
	if (USE_SDL2) {
		if (in.SystemKeyCode)
			scancode.emplace<u32>(in.SystemKeyCode);
		else
			scancode.emplace<irr::EKEY_CODE>(in.Key);
	} else {
		loadFromKey(in.Key, in.Char);
	}
```
Same idea as in `formatScancode` below.

File: src/client/keycode.cpp [hunk 38]
```diff
@@ -221,122 +223,172 @@ static const struct table_key table[] = {
...
+
+wchar_t KeyPress::getKeychar() const
+{
+	return lookup_scancode(scancode).Char;
 }
 
-const KeyPress EscapeKey("KEY_ESCAPE");
+bool KeyPress::loadFromScancode(const std::string &name)
+{
+#if USE_SDL2
```
Comment (SmallJoker) [inline src/client/keycode.cpp:370]: Same as in `formatScancode`. `#if` can be replaced by `if` to check the code during compile-time.

File: src/client/keycode.h [hunk 39]
```diff
@@ -4,62 +4,80 @@
...
+	void loadFromKey(irr::EKEY_CODE keycode, wchar_t keychar);
+	std::string formatScancode() const;
 
-extern const KeyPress EscapeKey;
+	std::variant<u32, irr::EKEY_CODE> scancode = irr::KEY_UNKNOWN;
 
-extern const KeyPress LMBKey;
-extern const KeyPress MMBKey; // Middle Mouse Button
-extern const KeyPress RMBKey;
+	static std::unordered_map<std::string, KeyPress> specialKeyCache;
```
Comment (SmallJoker) [inline src/client/keycode.h:68]: You *could* move this variable to the source file to avoid including `unordered_map` here.

File: src/unittest/test_keycode.cpp [hunk 40]
```diff
@@ -15,20 +15,26 @@ class TestKeycode : public TestBase {
 
 	void runTests(IGameDef *gamedef);
 
+	/* TODO: Re-introduce unittests after fully switching to SDL.
```
Comment (SmallJoker) [inline src/unittest/test_keycode.cpp:18]: SDL-specific unittests would be nice, but those can be added in another PR too.

**Review by SmallJoker — APPROVED** [review]
I very much appreciate that both, SDL and other IrrDevices are supported well. Aside from the documented/mentioned Shift-modifier hotkeys I couldn't find any difference (CIrrDeviceLinux).

Works. Thank you for taking care of this topic.

**Comment by SmallJoker** [comment]
Approved because all my comments are minor. You may address them if you'd like. I'll then make sure to review follow-up commits asap.

File: irr/src/CIrrDeviceSDL.cpp [hunk 41]
```diff
@@ -822,18 +866,27 @@ bool CIrrDeviceSDL::run()
...
+
+			// Treat AC_BACK as the Escape key
+			if (scancode == SDL_SCANCODE_AC_BACK || scancode == SDL_SCANCODE_ESCAPE)
+			{
+				if (SDL_event.type == SDL_KEYDOWN)
+					escapeKeys.insert(scancode);
+				else
+					escapeKeys.erase(scancode);
+				if (SDL_event.type == SDL_KEYUP && !escapeKeys.empty())
+					break; // avoid sending KEYUP twice if AC_BACK and ESCAPE are both released
```
Comment (grorp) [inline irr/src/CIrrDeviceSDL.cpp:880]: so we may send send keydown twice, but keyup only once? why?

the old implementation had the theoretical problem of possibly sending keydown/up twice for ESC, does it matter in practice?

File: src/client/keycode.cpp [hunk 42]
```diff
@@ -221,122 +223,172 @@ static const struct table_key table[] = {
...
 
-KeyPress::KeyPress(const char *name)
+static const table_key &lookup_scancode(const u32 scancode)
 {
-	if (strlen(name) == 0) {
-		Key = irr::KEY_KEY_CODES_COUNT;
-		Char = L'\0';
-		m_name = "";
-		return;
+	auto device = RenderingEngine::get_raw_device();
```
Comment (grorp) [inline src/client/keycode.cpp:278]: `get_raw_device` does a `sanity_check`, it cannot return null, so the null check is unnecessary

File: src/client/keycode.cpp [hunk 43]
```diff
@@ -221,122 +223,172 @@ static const struct table_key table[] = {
...
+static const table_key &lookup_scancode(const std::variant<u32, irr::EKEY_CODE> &scancode)
+{
+	return std::holds_alternative<irr::EKEY_CODE>(scancode) ?
+		lookup_keykey(std::get<irr::EKEY_CODE>(scancode)) :
+		lookup_scancode(std::get<u32>(scancode));
+}
+
+void KeyPress::loadFromKey(irr::EKEY_CODE keycode, wchar_t keychar)
+{
+	if (auto device = RenderingEngine::get_raw_device()) {
```
Comment (grorp) [inline src/client/keycode.cpp:300]: same as above

File: src/defaultsettings.cpp [hunk 44]
```diff
@@ -128,65 +129,74 @@ void set_default_settings()
...
 
 	// Keymap
-	settings->setDefault("remote_port", "30000");
-	settings->setDefault("keymap_forward", "KEY_KEY_W");
+#if USE_SDL2
+#define USEKEY2(name, value, _) settings->setDefault(name, value)
+#else
+#define USEKEY2(name, _, value) settings->setDefault(name, value)
+#endif
+	USEKEY2("keymap_forward", "<26>", "KEY_KEY_W");
```
Comment (grorp) [inline src/defaultsettings.cpp:137]: having scancodes serialized as `<num>` is bad for readability. couldn't we have SDL scancode names like `SDL_SCANCODE_W`?
I guess it's only possible after we get further along with requiring SDL (SDL headers in Luanti)?

File: src/gui/touchcontrols.cpp [hunk 45]
```diff
@@ -197,15 +196,7 @@ static EKEY_CODE id_to_keycode(touch_gui_button_id id)
...
-	std::string resolved = g_settings->get("keymap_" + key);
-	try {
-		code = keyname_to_keycode(resolved.c_str());
-	} catch (UnknownKeycode &e) {
-		code = KEY_UNKNOWN;
-		warningstream << "TouchControls: Unknown key '" << resolved
-			      << "' for '" << key << "', hiding button." << std::endl;
-	}
-	return code;
+	return getKeySetting("keymap_" + key);
```
Comment (grorp) [inline src/gui/touchcontrols.cpp:199]: would make sense to keep the warning. we still have the problem that keys might not be assigned ("rangeselect" by default on desktop, but other keys can be unassigned as well) and touch buttons disappear in that case

File: irr/include/IrrlichtDevice.h [hunk 46]
```diff
@@ -345,6 +346,27 @@ class IrrlichtDevice : public virtual IReferenceCounted
 	{
 		return video::isDriverSupported(driver);
 	}
+
+	//! Get the scancode of the corresponding keycode.
```
Comment (grorp) [inline irr/include/IrrlichtDevice.h:350]: I stumbled over this while reading, shouldn't it be "Get the corresponding scancode for the keycode"? Or, "Get the scancode corresponding to the keycode"

(nitpick)

(same below)

**Review by grorp — COMMENTED** [review]
a quick look

File: src/defaultsettings.cpp (hunk 44 above)
Comment (SmallJoker) [reply src/defaultsettings.cpp:137]: or alternatively, `SDL_SCANCODE_28`.

File: src/client/inputhandler.cpp (hunk 34 above)
Comment (y5nw) [reply src/client/inputhandler.cpp:146]: I could also add an `isValid` method in addition/as an alias to `operator bool`.

File: src/defaultsettings.cpp (hunk 44 above)
Comment (y5nw) [reply src/defaultsettings.cpp:137]: > having scancodes serialized as `<num>` is bad for readability. couldn't we have SDL scancode names like `SDL_SCANCODE_W`?

Not yet since we don't (yet) expose SDL headers to Luanti. IMO this is largely a temporary solution until then, at which point we can then transition to SDL scancodes directly since the numeric mapping is deterministic.

(By the way, this is also why I chose to not yet update `builtin/settingtypes.txt`. We can update it later when we introduce SDL-based scancode settings.)

> or alternatively, `SDL_SCANCODE_26`.

This syntax will eventually with SDL scancode values once we introduce those.

That said, we could use e.g. `SYSTEM_SCANCODE_26`, which is also slightly easier to parse than the angle bracket-based syntax.

File: src/unittest/test_keycode.cpp (hunk 40 above)
Comment (y5nw) [reply src/unittest/test_keycode.cpp:18]: I would prefer this in a separate PR. IMO this can wait a bit, possibly until after we refactor the keypress system to use SDL directly.

File: src/client/keycode.cpp (hunk 38 above)
Comment (y5nw) [reply src/client/keycode.cpp]: https://github.com/luanti-org/luanti/pull/14964/commits/c54a626fe3142c71c770563084471344adc3e6df

File: src/client/keycode.cpp (hunk 37 above)
Comment (y5nw) [reply src/client/keycode.cpp]: https://github.com/luanti-org/luanti/pull/14964/commits/c54a626fe3142c71c770563084471344adc3e6df

File: src/defaultsettings.cpp (hunk 44 above)
Comment (y5nw) [reply src/defaultsettings.cpp:137]: By the way, I just observed this: sdl2-compat passes SDL3-based scancodes to programs built on top of SDL2, so e.g. the "AC back" key on one of my keyboard shows up as "Sleep".

(Arch Linux, sdl-compat 2.32.52-1)

File: irr/src/CIrrDeviceSDL.cpp (hunk 41 above)
Comment (y5nw) [reply irr/src/CIrrDeviceSDL.cpp:880]: The idea was to avoid duplicating keyup and keydown events, although the logic is admittedly not clean.

> the old implementation had the theoretical problem of possibly sending keydown/up twice for ESC, does it matter in practice?

Looking at this, I don't think this will really happen in practice, so I will keep the old behavior for now.

Comment (y5nw) [reply irr/src/CIrrDeviceSDL.cpp]: https://github.com/luanti-org/luanti/pull/14964/commits/91031a6831e95ef2d93aabef0e9e9e5607ba16d6 and https://github.com/luanti-org/luanti/pull/14964/commits/45fbd2f876e77ba96e77bdf4f86bfe2c2b243fcb for now. I can't test AC_BACK at the moment due to sdl2-compat.

File: src/client/keycode.h (hunk 39 above)
Comment (y5nw) [reply src/client/keycode.h]: 83a8d2434

File: irr/include/IrrlichtDevice.h (hunk 46 above)
Comment (y5nw) [reply irr/include/IrrlichtDevice.h]: c7eba25a1

File: src/client/keycode.cpp (hunk 42 above)
Comment (y5nw) [reply src/client/keycode.cpp]: https://github.com/luanti-org/luanti/pull/14964/commits/1397f5ad91e3afcf9e9ad30361180c81d50b25da and https://github.com/luanti-org/luanti/pull/14964/commits/1430c9c10af4ddcb41bb95c7119ca6ac1584b348

File: src/client/keycode.cpp (hunk 43 above)
Comment (y5nw) [reply src/client/keycode.cpp]: https://github.com/luanti-org/luanti/pull/14964/commits/1397f5ad91e3afcf9e9ad30361180c81d50b25da and https://github.com/luanti-org/luanti/pull/14964/commits/1430c9c10af4ddcb41bb95c7119ca6ac1584b348

File: src/gui/touchcontrols.cpp (hunk 45 above)
Comment (grorp) [reply src/gui/touchcontrols.cpp:199]: The general warning you added doesn't cover the "no key assigned" case though. And we probably don't want a warning for unbound keys in general since you can intentionally unbind them.

I'd just readd the warning in TouchControls, what you proposed above looks good

File: src/client/inputhandler.cpp (hunk 34 above)
Comment (y5nw) [reply src/client/inputhandler.cpp]: Actually I think I'll just leave a comment here instead: https://github.com/luanti-org/luanti/pull/14964/commits/c05ad9af6dffbef0abfd474fcede3e6cee70f942

File: src/gui/touchcontrols.cpp (hunk 45 above)
Comment (y5nw) [reply src/gui/touchcontrols.cpp]: Committed. IMO it's fine to have the warning in both places.

File: src/defaultsettings.cpp (hunk 44 above)
Comment (y5nw) [reply src/defaultsettings.cpp]: https://github.com/luanti-org/luanti/pull/14964/commits/e9757fd82cfbda0cfc018c67523e83625efac452 and https://github.com/luanti-org/luanti/pull/14964/commits/61c3fe1b1614299ae135ee1a538036abed08633e ? IMO this is the best we can do for now.
