### PR TITLE
ParticleSpawner: Fix crash caused by empty texture

### LINKED ISSUE #16345: a segfault related to animations in particlespawners
### Luanti version

```true
Luanti 5.12.0 (Linux)
Using LuaJIT 2.1.1741730670
Built by GCC 15.1
Running on Linux/6.15.6 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/share/luanti"
STATIC_LOCALEDIR="/usr/share/locale"
```

### Operating system and version

arch    btw

### CPU model

_No response_

### GPU model

_No response_

### Active renderer

_No response_

### Summary

if you execute `core.add_particlespawner{pos=pos,time=1,animation={type="vertical_frames"}}`  it crashes in a bad way

nothing much in the logs
```
2025-07-17 11:49:27: VERBOSE[Server]: Handling chat command "/lua" with params "core.add_particlespawner{pos=pos,time=1,animation={type=\"vertical_frames\"}}"
2025-07-17 11:49:27: ACTION[Server]: [log] Caught command '/lua', issued by 'singleplayer'. Parameters: 'core.add_particlespawner{pos=pos,time=1,animation={type="vertical_frames"}}'
2025-07-17 11:49:27: ACTION[Server]: singleplayer executed core.add_particlespawner{pos=pos,time=1,animation={type="vertical_frames"}}
Segmentation fault         (core dumped) luanti --verbose
```

### Steps to reproduce

1) `//lua core.add_particlespawner{pos=pos, time=1, animation={type="vertical_frames"}}`
2) observe the segfault

### PR DESCRIPTION
**Pull request by SmallJoker**
no_texture.png is now used as a fallback (if available), like already seen with registered items with empty 'inventory_image'.

Fixes #16345

## To do

This PR is Ready for Review.

## How to test

1. Use 3rd person perspective
2. Use the worldedit commands mod
3. `//lua pos=player:get_pos(); pos.y=pos.y+2; core.add_particlespawner{pos=pos,time=4,animation={type="vertical_frames"}}`
4. A particle must show up on top of your head, indicating failure by using `no_texture.png`.

### CODE REVIEW

File: src/noise.cpp [hunk 1]
```diff
@@ -83,6 +83,10 @@ u32 PcgRandom::range(u32 bound)
 	if (bound == 0)
 		return next();
 
+	// Optimization: only one value is possible.
+	if (bound == 1)
+		return 0;
```
Comment (sfan5) [inline src/noise.cpp:87]: I would add this to `range(s32 min, s32 max)` too and IMO the comment is not needed

Comment (SmallJoker) [reply src/noise.cpp:87]: That function is computationally trivial compared to `range(u32 bound)`, thus I did intentionally not duplicate the condition. I'll however remove the comment.

**Review by sfan5 — APPROVED** [review]
untested, LGTM
