### PR TITLE
Show proper default key name in reset tooltip on keybindings menu

### LINKED ISSUE #16515: Tooltip of "reset key" button shows cryptic key ID
### Luanti version

```true
Luanti 5.13.0
Luanti 5.14.0-rc1
```

### Operating system and version

GNU/Linux

### CPU model

_No response_

### GPU model

_No response_

### Active renderer

_No response_

### Summary

If you hover the "reset" button in the keybinding screen for mouse and keyboard for one of the keys that you have manually bound, it says something like "Reset to default (SYSTEM_SCANCODE_65)".

This is meaningless to the user, I wish to have it replaced with the actual human-readable key name.

### Steps to reproduce

1. Open the keybinding screen in the settings
2. Change any key
3. Hover the "reset setting" button (red circle arrow) next to that key
4. Read the tooltip

### PR DESCRIPTION
**Pull request by CrazyladMT**
Fixes #16515

This PR fixes an issue in the keybindings menu where the reset button shows a cryptic tooltip such as "Reset setting to default (SYSTEM_SCANCODE_##)".

This also adds a new core function for the main menu `core.get_key_description()` to take a scancode and convert it to the human-readable name that is already available in KeyPress.

## To do

This PR is Ready for Review.

## How to test

1. navigate to the keybindings menu inside settings
2. set a keybinding
3. hover over the reset button and observe that it shows a human-readable key name
Screenshot From 2025-12-24 10-42-59

### CODE REVIEW

**Review by SmallJoker — APPROVED** [review]
Does work. At least as long as the key exists.
grafik

According to https://wiki.libsdl.org/SDL3/SDL_Scancode , respectively the USB standard https://gist.github.com/mildsunrise/4e231346e2078f440969cdefb6d4caa3 this should refer to the `+` key, which does not exist on my keyboard.
Fair enough. Works.

File: src/script/lua_api/l_menu_common.cpp [hunk 1]
```diff
@@ -52,13 +52,24 @@ int ModApiMenuCommon::l_normalize_keycode(lua_State *L)
 }
 
 
+int ModApiMenuCommon::l_scancode_to_keyname(lua_State *L)
```
Comment (y5nw) [inline src/script/lua_api/l_menu_common.cpp]: IMO `get_key_description` would be better given that (1) this also accepts keycode input and (2) the `KeyPress` class will be extended in the future to includes other modes of input.

**Review by y5nw — APPROVED** [review]
LGTM

**Comment by y5nw** [comment]
> Does work. At least as long as the key exists. grafik
> 
> According to https://wiki.libsdl.org/SDL3/SDL_Scancode , respectively the USB standard https://gist.github.com/mildsunrise/4e231346e2078f440969cdefb6d4caa3 this should refer to the `+` key, which does not exist on my keyboard. Fair enough. Works.

This is the key to the left of the backspace key, which is a dead key on some layouts (dead acute on the German layout, dead circumflex on a Swiss one). SDL does not report a keycode for this, so the scancode is displayed.

File: src/script/lua_api/l_menu_common.cpp (hunk 1 above)
Comment (CrazyladMT) [reply src/script/lua_api/l_menu_common.cpp]: Hmm... I agree.

File: builtin/common/settings/dlg_settings.lua [hunk 2]
```diff
@@ -615,7 +615,10 @@ local function get_formspec(dialogdata)
 		local info_reset_y = used_h / 2 - 0.25
 
 		if show_reset then
-			local default = comp.setting.default
+			local default = comp.setting.type == "key"
+				and core.get_key_description(comp.setting.default)
```
Comment (y5nw) [inline builtin/common/settings/dlg_settings.lua]: There should be a case here for keybindings that are not bound.

Comment (CrazyladMT) [reply builtin/common/settings/dlg_settings.lua]: Perhaps it could say "Reset setting to default (Not bound)" rather than just "Reset setting to default ()"?

Comment (y5nw) [reply builtin/common/settings/dlg_settings.lua]: Yes.

File: builtin/common/settings/dlg_settings.lua [hunk 3]
```diff
@@ -615,7 +615,13 @@ local function get_formspec(dialogdata)
 		local info_reset_y = used_h / 2 - 0.25
 
 		if show_reset then
-			local default = comp.setting.default
+			local default
```
Comment (y5nw) [inline builtin/common/settings/dlg_settings.lua]: Missing fallback for `comp.setting.type ~= "key"`:

```suggestion
			local default = comp.setting.default
```

(Then you can also replace `comp.setting.default` in the `if` block below with just `default`.)

File: builtin/common/settings/dlg_settings.lua [hunk 4]
```diff
@@ -615,7 +615,13 @@ local function get_formspec(dialogdata)
...
+			if comp.setting.type == "key" then
+				default = (comp.setting.default ~= "")
+					and core.get_key_description(comp.setting.default)
+					or "Not bound"
```
Comment (y5nw) [inline builtin/common/settings/dlg_settings.lua]:
```suggestion
					--~ Indicates that the action does not have a corresponding keybinding.
					or fgettext_ne("Not bound")
```

**Review by y5nw — CHANGES_REQUESTED** [review]

File: builtin/common/settings/dlg_settings.lua (hunk 3 above)
Comment (CrazyladMT) [reply builtin/common/settings/dlg_settings.lua]: One should not code at 10:30 PM lol.
I know how to code Lua, but I don't know how to code Lua _**well**_ XD

File: builtin/common/settings/dlg_settings.lua (hunk 4 above)
Comment (CrazyladMT) [reply builtin/common/settings/dlg_settings.lua]: Thanks for the help. I knew that "Not bound" had to be translated, but I had no idea what function to use for translations since I don't ever work with locale stuff lol

File: builtin/common/settings/dlg_settings.lua [hunk 5]
```diff
@@ -616,6 +616,14 @@ local function get_formspec(dialogdata)
 
 		if show_reset then
 			local default = comp.setting.default
+			if comp.setting.type == "key" then
+				default = (default ~= "")
+					and core.get_key_description(default)
+
+					-- Indicates that the action does not have a corresponding keybinding.
```
Comment (y5nw) [inline builtin/common/settings/dlg_settings.lua]: (Nitpick) the `~` in my previous suggestion was for indicating that the comment should be added as a translation note for Weblate (which is arguably why I suggested adding such a comment): https://github.com/luanti-org/luanti/blob/3b30e131ce141e7d1d357b6f15f56e80dcf9b3a5/util/updatepo.sh#L52-L53

```suggestion
					--~ Indicates that the action does not have a corresponding keybinding.
```

Comment (CrazyladMT) [reply builtin/common/settings/dlg_settings.lua]: Oh lol

**Review by y5nw — APPROVED** [review]
Tested and works
