### PR TITLE
Client: protect against circular attachments

### LINKED ISSUE #15988: Segfault with attachments
### Luanti version

```true
5.11
```

### Operating system and version

Pop!_OS 22.04

### CPU model

i7

### GPU model

GeForce GTX something

### Active renderer

X11/SDL, doesn't matter

### Summary

It's been months since we've been experiencing a client crash in my server, Block League mini-game. The keyword is **client**, as only the players inside the mini-game crash, with no log whatsoever neither in the server `debug.txt` nor in the client's. Server remains online. The crash is pretty rare and I was finally able to collect a backtrace with `gdb`:

```
Thread 1 "luanti" received signal SIGSEGV, Segmentation fault.
0x0000555555719b8d in GenericCAO::updateAttachments (this=0x5555702877a0) at /blabla/Luanti/src/client/content_cao.cpp:1483
1483		m_attached_to_local = parent && parent->isLocalPlayer();
(gdb) backtrace
#0  0x0000555555719b8d in GenericCAO::updateAttachments (this=0x5555702877a0) at /blabla/Luanti/src/client/content_cao.cpp:1483
#1  0x0000555555719ba9 in GenericCAO::updateAttachments (this=0x555570b6c3c0) at /blabla/Luanti/src/client/content_cao.cpp:1509
#2  0x0000555555719ba9 in GenericCAO::updateAttachments (this=0x5555702877a0) at /blabla/Luanti/src/client/content_cao.cpp:1509
#3  0x0000555555719ba9 in GenericCAO::updateAttachments (this=0x555570b6c3c0) at /blabla/Luanti/src/client/content_cao.cpp:1509
#4  0x0000555555719ba9 in GenericCAO::updateAttachments (this=0x5555702877a0) at /blabla/Luanti/src/client/content_cao.cpp:1509
(repeats very often)
```

In my mini-game, when players die ([code](https://gitlab.com/zughy-friends-minetest/block_league/-/blob/master/block_league/src/arena_lib/on_death.lua?ref_type=heads#L70)), no formspec is shown and they're attached to an alive teammate of theirs ([function of previous link](https://gitlab.com/zughy-friends-minetest/block_league/-/blob/master/block_league/src/game/misc/death_state.lua?ref_type=heads#L75)), if the teammate exists. Respawn is automatically handled after a few seconds (the line below the one of the first link)

### Steps to reproduce

good luck

### PR DESCRIPTION
**Pull request by SmallJoker**
The server already includes such check. There must be a desync issue that causes an ID mismatch, resulting in client crashes. Any such crash must be prevented.

Fixes #15988

Also: checks against `id == 0` are unnecessary. 0 is a reserved ID, thus a lookup will always return `nullptr`.

## To do

This PR is Ready for Review.

## How to test

1.  Perhaps disable the server-side checks?

### CODE REVIEW

File: src/client/content_cao.cpp [hunk 1]
```diff
@@ -386,6 +386,32 @@ void GenericCAO::setChildrenVisible(bool toset)
...
+			for (obj = obj->getParent(); obj; obj = obj->getParent()) {
+				if (obj == this) {
+					problem = true;
+					break;
+				}
+			}
+		}
+		if (problem) {
+			warningstream << "Network or mod bug: "
+				<< "Attempted to attach object " << m_id << " to parent "
```
Comment (SmallJoker) [inline src/client/content_cao.cpp:409]: Split the string such that the compiler can re-use the equivalent string from `UnitSAO::setAttachment`.

**Review by sfan5 — APPROVED** [review]
lgtm
