### PR TITLE
Restrict relative mouse mode to Wayland users

### LINKED ISSUE #14932: Cursor bug, game unplayable
### Minetest version

```true
Minetest 5.9.0-dev-8ef2c42 (Linux)
Using LuaJIT 2.1.0-beta3
Built by GCC 9.4
Running on Linux/5.15.0 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Irrlicht device

_No response_

### Operating system and version

Ubuntu 20.04

### CPU model

AMD A6-7470K Radeon R5, 6 Compute Cores

### GPU model

Kaveri [Radeon R5 Graphics]
Cedar [Radeon HD 5000/6000/7350/8350 Series] 

### Active renderer

AMD CEDAR (DRM 2.50.0 / 5.15.0-117-generic, LLVM 12.0.0)

### Summary

I'm on my fixed PC, on linux, Ubuntu.

When I move the cursor it spins, and I can't steer it.
This only happens on this version, which leads me to believe that it's a bug in this version.

### Steps to reproduce

Watch the video to see what it looks like

[Video 2024-08-06.mp4.zip](https://github.com/user-attachments/files/16514654/Video.2024-08-06.mp4.zip)

### PR DESCRIPTION
**Pull request by sfan5**
fixes #14932

## To do

This PR is Ready for Review.

## How to test

nobody could reproduce the original issue but you can confirm that:
1. Luanti on wayland uses relative mouse mode
2. it doesn't on other platforms

### CODE REVIEW

File: irr/src/CIrrDeviceSDL.h [hunk 1]
```diff
@@ -96,6 +96,9 @@ class CIrrDeviceSDL : public CIrrDeviceStub
 	//! Checks if the Irrlicht device supports touch events.
 	bool supportsTouchEvents() const override;
 
+	//! Checks whether windowing uses the Wayland protocol.
+	bool isUsingWayland() const override;
```
Comment (SmallJoker) [inline irr/src/CIrrDeviceSDL.h:100]: A thought: `SomeEnum getDisplayServerType() const override;` would be more generic, thus more future-proof to give specific setups a special treatment.

Comment (sfan5) [reply irr/src/CIrrDeviceSDL.h:100]: Unlikely that we'll need it so making that "generic" now would be wasted work IMO.
