### PR TITLE
Preserve color across newline‑split log messages in chat

### LINKED ISSUE #16377: Multiline log messages do not show up fully formatted in chat
### Luanti version

```true
Luanti 5.13.0
```

### Summary

when trying to leave a log message with multiple lines, the first line shows up fully formatted but the lines after just show up as plaintext

image:

Image

### Steps to reproduce

in any world, activate this code snippet:

`core.debug("foo \n bar", "error")`

### PR DESCRIPTION
**Pull request by CrazyladMT**
This PR fixes a small problem where log messages in the chat containing newlines would lose
their color after the first line. 

Fixes #16377
## To do

This PR is Ready for Review

## How to test
1. join devtest
2. run `/lua core.log("error", "foo \nbar")`
3. log messages with newlines should be formatted properly
Screenshot From 2025-12-19 10-58-18

### CODE REVIEW

File: src/client/game.cpp [hunk 1]
```diff
@@ -2497,8 +2497,15 @@ void Game::updateChat(f32 dtime)
...
-		chat_backend->addMessage(L"", utf8_to_wide(line));
+		std::string prefix = color_for(entry.level);
+
+		// Split multi‑line log messages so each line keeps its color
+		std::stringstream ss(entry.combined);
+		std::string part;
+		while (std::getline(ss, part)) {
+			std::string colored = prefix + part;
+			chat_backend->addMessage(L"", utf8_to_wide(colored));
+		}
```
Comment (SmallJoker) [inline src/client/game.cpp]: Wouldn't it be very fitting to move your logic into the existing function here: ?
https://github.com/luanti-org/luanti/blob/0535b0c09d94cbefa14770c067e5b41e8976cbf1/src/chat.cpp#L774-L785

It's where the color information is lost in the first place - by splitting lines.

File: src/client/game.cpp [hunk 2]
```diff
@@ -2497,8 +2497,15 @@ void Game::updateChat(f32 dtime)
 	std::vector<LogEntry> entries = m_chat_log_buf.take();
 	for (const auto& entry : entries) {
 		std::string line;
```
Comment (cx384) [inline src/client/game.cpp:2499]: This variable is unused now, right?
Maybe remove it and rename `part` to `line` below.

File: src/client/game.cpp [hunk 3]
```diff
@@ -2497,8 +2497,15 @@ void Game::updateChat(f32 dtime)
...
-		line.append(color_for(entry.level)).append(entry.combined);
-		chat_backend->addMessage(L"", utf8_to_wide(line));
+		std::string prefix = color_for(entry.level);
+
+		// Split multi‑line log messages so each line keeps its color
+		std::stringstream ss(entry.combined);
```
Comment (cx384) [inline src/client/game.cpp]: Could use `std::istringstream` instead.

File: src/client/game.cpp (hunk 1 above)
Comment (CrazyladMT) [reply src/client/game.cpp]: Hmm... that would have been helpful to know about _**before**_ I started coding XD. Thanks for the feedback, and I'll see what I can do despite being a bit of a noob to C++ lol

File: src/client/game.cpp (hunk 2 above)
Comment (CrazyladMT) [reply src/client/game.cpp:2499]: True. However I followed @SmallJoker's suggestion and moved this logic to src/chat.cpp

File: src/chat.cpp [hunk 4]
```diff
@@ -775,10 +775,24 @@ void ChatBackend::addMessage(const std::wstring &name, std::wstring text)
...
 	WStrfnd fnd(text);
 	while (!fnd.at_end())
 	{
 		std::wstring line = fnd.next(L"\n");
+
+		// Reapply color prefix to each line
+		if (!color_prefix.empty())
+			line = color_prefix + line;
+
 		m_console_buffer.addLine(name, line);
```
Comment (SmallJoker) [inline src/chat.cpp]: Please have a look at the `EnrichedString` implementation. It supports text coloring and proper splitting.
As a neat fact, `addLine` (or rather the struct `ChatLine`) already uses `EnrichedString` internally. The IMO best solution here is to always work with `EnrichedString` in `addMessage` and pass it to `addLine`.

EDIT: Here's one part to the solution:
```C++
void ChatBackend::addMessage(const std::wstring &name, std::wstring text)
{
	// Note: A message may consist of multiple lines, for example the MOTD.
	EnrichedString etext(text);

	size_t str_pos = 0;
	while (str_pos < etext.size()) {
		EnrichedString line = etext.getNextLine(&str_pos);

		m_console_buffer.addLine(name, line);
		m_recent_buffer.addLine(name, line);
	}
}
```

Comment (CrazyladMT) [reply src/chat.cpp]: Interesting. I kind of figured there was a native solution such as this. Neat! This makes the fix much simpler lol.

**Review by SmallJoker — APPROVED** [review]
Works on my machine.

**Review by sfan5 — APPROVED** [review]
LGTM
