### PR TITLE
Enforce minimum `client_mapblock_limit` depending on view range

### LINKED ISSUE #10703: Streamline distance configuration
## Problem

As is there are least the following config options that relate to viewing distance:
**Client:**
`viewing_range`
`client_mapblock_limit`

**Server:**
`max_block_send_distance`
`max_block_generate_distance`
`active_object_send_range_blocks`
`active_block_range`

In addition client and server settings not aligned. The client might have a far viewing range, but the server a low send distance, in which case far blocks would just not load.

## Solutions

1. Add a server config tab for these four settings. Then people can easily configure these at least for singleplayer.
2. Have the server send its configured send distance, so that the client can (optionally) adjust its viewing range. Might be good to have this server controlled anyway. Perhaps handle this like zoom, where there server has the option to fix this.
3. Calculate the client mapblock limit dynamically.

I think a bunch of my concerns would just go away if we did (1) above. That way we set all of these low, but it's easy (and obvious how) to increase these.

### LINKED ISSUE #12010: Increase the default viewing range on Android
##### Minetest version

```
5.4.2 from Google Play Store (beta program enrolled)
```

##### OS / Hardware

Operating system: Android 12
CPU: Samsung Galaxy Z Fold2, Snapdragon 865 5G+, [full device specs](https://www.gsmarena.com/samsung_galaxy_z_fold2_5g-10342.php)

GPU model: Adreno 650
OpenGL version: OpenGL ES 3.2

##### Summary

Related to https://github.com/minetest/minetest/issues/12009.

[The default viewing range on Android](https://github.com/minetest/minetest/blob/66e8aae9f2a28ee31ffe30694fdb61a8fdceb8d7/src/defaultsettings.cpp#L489) (50) is much lower than on desktop (190). However, most devices nowadays should be able to manage higher view ranges. We can't quite default to the same view range as on desktop, but I think 70 or 80 would be a reasonable default that still looks good on a (small) mobile display.

Some other setting changes could be considered too, such as enabling smooth lighting by default.

##### Steps to reproduce

Start a new game on Android.

### LINKED ISSUE #15849: Android: blocks disappear just by turning around due to low client_mapblock_limit
### Luanti version

```true
Luanti 5.8.0 arm64-v8a (official build from official F-Droid Repo)
Luanti 5.9.0 arm64-v8a (official build from official F-Droid Repo)
Luanti 5.9.1 arm64-v8a (official build from official F-Droid Repo)
Luanti 5.10.0 arm64-v8a (official build from official F-Droid Repo)
Luanti 5.11.0 arm64-v8a (official build from official F-Droid Repo)

Luanti 5.8.0 arm64-v8a (official build from luanti github repo)
Luanti 5.9.0 arm64-v8a (official build from luanti github repo)
Luanti 5.9.1 arm64-v8a (official build from luanti github repo)
Luanti 5.10.0 arm64-v8a (official build from luanti github repo)
Luanti 5.11.0 arm64-v8a (official build from luanti github repo)
```

### Operating system and version

crDroid 8.10 (based on LineageOS 19.1, Android 12L, API level 31)

### CPU model

Qualcomm Snapdragon 8250 (865)

### GPU model

Adreno 650

### Active renderer

ES 3.2 / ogles2 / SDL

### Summary

The first time I noticed the problem was with version 5.8.0 (it has always been present, or it is a recent regression, I cannot say). It shows up in all the games I've tested it in: MTG, Mineclonia, Voxelibre. It shows up even if you reinstall Luanti with a clean config. The behavior does not depend on the selected Video Driver (opengl, opengl 3, ogles2). It does not show up with a drawing range of 100 and below (this can be seen in the video). This behavior should not occur, because I have never encountered this on my laptop in the Linux version.

### Steps to reproduce

Log into any game, enable a drawing range higher than 100 and start gradually rotating the camera around its axis.

### PR DESCRIPTION
**Pull request by sfan5**
implements a modified suggestion from #10703

fixes #15849
closes #12010
closes #10703

table: view range -> number of mapblocks needed for entire view sphere
```
20 33
30 33
40 113
50 268
60 268
70 523
80 523
90 904
100 1436
110 1436
120 2144
130 3053
140 3053
150 4188
160 4188
170 5575
180 7238
190 7238
200 9202
^ this is as far as the code enforces it
210 11494
220 11494
230 14137
240 14137
250 17157
260 20579
270 20579
280 24429
290 28730
300 28730
310 33510
320 33510
330 38792
340 44602
350 44602
360 50965
370 57905
380 57905
390 65449
400 65449
```

1000 MapBlocks is about 16 MB of just the map data

## To do

This PR is Ready for Review.

## How to test

1. set `client_mapblock_limit = 1`
2. notice how nothing seems to be going wrong

### CODE REVIEW

**Comment by debagos** [comment]
Tested on desktop and I noticed that nothing seems to be going wrong.
I like this change, for example you can use zoom now and the nodes around you won't get re-loaded from the server.

**Comment by lhofhansl** [comment]
Finally. I have been saying this forever.
I feel there are still a lot metrics that need to be set together and for a newbie it is 100% unclear how to set them.

**Review by grorp — APPROVED** [review]
I haven't tested, but the changes look good. Thank you for working on this.
This looks like it shouldn't be squashed?

File: src/defaultsettings.cpp [hunk 1]
```diff
@@ -558,16 +559,17 @@ void set_default_settings()
 	settings->setDefault("max_block_generate_distance", "5");
 	settings->setDefault("sqlite_synchronous", "1");
 	settings->setDefault("server_map_save_interval", "15");
-	settings->setDefault("client_mapblock_limit", "1000");
+	settings->setDefault("client_mapblock_limit", "1500");
 	settings->setDefault("active_block_range", "2");
-	settings->setDefault("viewing_range", "50");
+	settings->setDefault("viewing_range", "70");
```
Comment (grorp) [inline src/defaultsettings.cpp:564]: oh, also: is there a specific reason you chose 70, or just for +20?

Comment (sfan5) [reply src/defaultsettings.cpp:564]: no specific reason.

**Comment by lhofhansl** [comment]
Actually, can we go further? If the configured values for `client_mapblock_limit` is 0, then pick a good default (sphere volume), and then make 0 the default value. That way most people will never have to think about this setting.

**Comment by sfan5** [comment]
The current default of 7500 "equals" a sphere of 190 nodes. Having it be higher than strictly necessary is still beneficial if the user can afford the additional RAM.

Apart from Android where we've set a too low default I don't think anyone has had to worry about changing `client_mapblock_limit` and it's place in advanced settings is fine.
