### PR TITLE
[NO SQUASH] Two fixes I guess

### LINKED ISSUE #15812: URL open confirmation dialog uses server-provided fonts
### Luanti version

```true
5.11.0
```

### Summary

Servers could set the font to something to obscure what URL you are actually going to

### Steps to reproduce

1. Set your monospace font to an easily identifiable one (I used the italic font)
2. Join a server with custom fonts, like AES
3. Find a URL button/link (AES has a donation link in the Block League player profile)
4. Note that the dialog uses a custom font

### LINKED ISSUE #15875: Shift locking breaks descent in freemove.
### Luanti version

```true
Luanti 5.12.0-dev-18ac8b20f-dirty (Linux)
Using LuaJIT 2.1.1703358377
Built by GCC 13.3
Running on Linux/6.8.0 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Operating system and version

Ubuntu 24.04

### CPU model

_No response_

### GPU model

_No response_

### Active renderer

_No response_

### Summary

Since #15785, if a player enables free move and they are in flight they can not controle decent very well, this is due to the fact that the sneak lock is not unlocked when a player jumps.

### Steps to reproduce

1. Pull the latest, compile.
2. Enable sneak locking.
3. Start world and enable freemove.
4. Go down using sneak, try to go up and down.

### Steps to reproduce

Solution: Disable sneak lock when in free-move.

### PR DESCRIPTION
**Pull request by SmallJoker**
Two smaller fixes that I couldn't be bothered to open separate PRs. Sorry for that.

Fixes #15875 <-- commit 1
Fixes #15812 <-- commit 2

## To do

This PR is Ready for Review.

## How to test

To test commit 1: (sneak toggle)

1. Use the setting `toggle_sneak_key = true`
2. Tap the Sneak key once to activate this feature
3. Enter freemove/fly mode.
   * master: the player flies down (unwanted)
   * PR: the feature is deactivated as long fly is enabled

To test commit 2: (URL open)

1. Download and enable the "fonts" mod provided in #15606 (section "How to test")
2. `/test_formspec` -> hypertext tab -> scroll 50% down to the blue link
2. Clicky click
   * master: the dialog server-provided fonts
   * PR: the client's fonts are used

### CODE REVIEW

File: src/client/fontengine.cpp [hunk 1]
```diff
@@ -81,7 +81,7 @@ irr::gui::IGUIFont *FontEngine::getFont(FontSpec spec)
 irr::gui::IGUIFont *FontEngine::getFont(FontSpec spec, bool may_fail)
 {
 	if (spec.mode == FM_Unspecified) {
-		spec.mode = m_currentMode;
+		spec.mode = s_default_font_mode;
```
Comment (SmallJoker) [inline src/client/fontengine.cpp:84]: Note to reviewers: Variable renamed. Can undo, if that's a problem.

File: src/client/fontengine.cpp [hunk 2]
```diff
@@ -248,18 +261,6 @@ gui::IGUIFont *FontEngine::initFont(const FontSpec &spec)
 	g_settings->getU16NoEx(setting_prefix + "font_shadow_alpha",
 			font_shadow_alpha);
 
-	std::string path_setting;
```
Comment (SmallJoker) [inline src/client/fontengine.cpp:251]: Note to reviewers: I moved this code block down to where `media_name` is actually used.

File: src/client/fontengine.cpp [hunk 3]
```diff
@@ -219,8 +224,16 @@ gui::IGUIFont *FontEngine::initFont(const FontSpec &spec)
 	assert(spec.mode != FM_Unspecified);
 	assert(spec.size != FONT_SIZE_UNSPECIFIED);
 
+	FontMode mode = spec.mode; // this takes priority over `spec.mode` !
```
Comment (sfan5) [inline src/client/fontengine.cpp:227]: I think it'd be nicer to modify `spec` to avoid confusion

**Review by sfan5 — COMMENTED** [review]
LGTM otherwise

File: src/client/fontengine.cpp (hunk 3 above)
Comment (SmallJoker) [reply src/client/fontengine.cpp]: I also found that the URL dialog changed fonts when hovering over buttons. This became too messy, thus moved it to a separate boolean in `FontSpec`.

File: src/gui/guiOpenURL.cpp [hunk 4]
```diff
@@ -87,6 +87,13 @@ void GUIOpenURLMenu::regenerateGui(v2u32 screensize)
 		ok = false;
 	}
 
+	std::array<StyleSpec, StyleSpec::NUM_STATES> styles {};
+	for (StyleSpec &style : styles) {
+		style.set(StyleSpec::Property::FONT, "_no_server_media");
+	}
```
Comment (sfan5) [inline src/gui/guiOpenURL.cpp:93]:
```suggestion
	for (auto &style : styles)
		style.set(StyleSpec::Property::FONT, "_no_server_media");
```

**Review by sfan5 — APPROVED** [review]
LGTM but you probably want to squash that last commit

**Comment by SmallJoker** [comment]
> but you probably want to squash that last commit

Sure. I thought it's easier to see the new changes this way. Squashed now to be ready for merge soon (TM).
