### PR TITLE
Do not discover mod directories that fail parsing

### LINKED ISSUE #15914: `testGetModWrongDir` tests fail on MSVC
### Luanti version

```true
Luanti 5.12.0-dev-cc65c8bd7-dirty (Windows)
Using LuaJIT 2.1.0-beta3
Built by MSVC 19.39
Running on Windows/10.0.26100 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=0
USE_SOUND=1
STATIC_SHAREDIR="."
```

### Operating system and version

Windows 11

### CPU model

_No response_

### GPU model

_No response_

### Active renderer

_No response_

### Summary

The tests expect to find no mods, but do anyway. I modified `testGetModNamesWrongDir` to print out the mods it found, and the result was quite interesting. I'm filing a report for awareness although I intend to take the issue myself; I do not know the cause at this time. If someone knows why this is, please share.

```
found mod "sr"
found mod "hp"
found mod "ghcup"
found mod "cabal"
found mod "Windows"
found mod "Users"
found mod "System.sav"
found mod "System Volume Information"
found mod "SWSetup"
found mod "Recovery"
found mod "ProgramData"
found mod "Program Files (x86)"
found mod "Program Files"
found mod "PerfLogs"
found mod "OneDriveTemp"
found mod "Documents and Settings"
found mod "Config.Msi"
found mod "AMD"
found mod "$SysReset"
found mod "$Recycle.Bin"
Test assertion failed: result.empty() == true
    actual  : 0
    expected: 1
    at test_servermodmanager.cpp:150
[FAIL] testGetModNamesWrongDir - 2ms
```

### Steps to reproduce

Run the unit tests on an MSVC build.

### PR DESCRIPTION
**Pull request by JosiahWI**
Fixes #15914

The root issue of the unit test failure is that all directories that are found in the mod search are counted as mods, even if they are detected to be invalid as such by the parser. For example, the presence of an init.lua file is required, and the parser will return false if one is not found. This return value was completely ignored. Simply counting the mod conditionally on the parsing success makes the modserver tests pass on MSVC. I have also added the nodiscard attribute to the parse function as a preventive measure for regressions.

## To do

Ready for Review

- [X] ~~Reenable the test in CI now that it passes.~~ We don't ignore the failures on an individual basis. We have to fix the other three failing modules first.

## How to test

See that the servermod unittests pass on all systems including MSVC now.

### CODE REVIEW

**Comment by grorp** [comment]
related: #14172

File: src/content/mods.cpp [hunk 1]
```diff
@@ -55,6 +55,7 @@ bool parseDependsString(std::string &dep, std::unordered_set<char> &symbols)
 	return !dep.empty();
 }
 
+[[nodiscard]]
```
Comment (sfan5) [inline src/content/mods.cpp:58]: missing annotation in `mods.h`

Comment (appgurueu) [reply src/content/mods.cpp:58]: fixing that will raise the question of what to do if this fails in `l_mainmenu.cpp`. it should return nothing in that case, which would then have to be dealt with properly at all callsites of `core.get_content_info`.

**Review by appgurueu — APPROVED** [review]
this is fine

File: src/script/lua_api/l_mainmenu.cpp [hunk 2]
```diff
@@ -385,7 +385,8 @@ int ModApiMainMenu::l_get_content_info(lua_State *L)
 	if (spec.type == "mod") {
 		ModSpec spec;
 		spec.path = path;
-		parseModContents(spec);
+		// TODO return nothing on failure (needs callers to handle it)
+		static_cast<void>(parseModContents(spec));
```
Comment (sfan5) [inline src/script/lua_api/l_mainmenu.cpp:389]: I fear this TODO will still be here in 2 years

**Review by sfan5 — APPROVED** [review]
:shrug:

File: src/script/lua_api/l_mainmenu.cpp (hunk 2 above)
Comment (JosiahWI) [reply src/script/lua_api/l_mainmenu.cpp:389]: So do I. That's why I normally save source file space by omitting it.

Comment (sfan5) [reply src/script/lua_api/l_mainmenu.cpp:389]: Removing both the comment and the void cast would also be fine.

Comment (JosiahWI) [reply src/script/lua_api/l_mainmenu.cpp:389]: I'll leave them in and try to finish them this week, so that they won't be there 2 years from now.
