### PR TITLE
[no squash] Various bug fixes

### LINKED ISSUE #15761: Non-relative mouse input feels weird
### Luanti version

```true
Since #15697.
```

### Operating system and version

Arch, btw.

### CPU model

_No response_

### GPU model

_No response_

### Active renderer

SDL

### Summary

Since #15697, mouse input feels somewhat bad. I can only move it in a coarse grid (in 0.6° steps it seems (this is also the my value of `mouse_sensitivity`)). And there also seems to be some mouse acceleration or whatever going on.

This is not game-breaking, and ~~we had it like this before~~ (Edit: but not on SDL), and only happens with SDL irr device it seems, so I guess it's not a blocker.

### Steps to reproduce

Move your mouse to look around.

~~Haven't tested on non-SDL.~~ Edit: Can't reproduce with X11 irr device.

I also had to increase the `mouse_sensitivity` setting from 0.2 to 0.6, this might have an influence.

Edit: If using sdl2-compat, do:
`SDL_MOUSE_EMULATE_WARP_WITH_RELATIVE=0 luanti`

### LINKED ISSUE #15798: Cloud disappers after being 'disabled' by altitude.
### Luanti version

```true
Luanti 10.0+ (includes Luanti 11)
```

### Operating system and version

Windows 11

### CPU model

_No response_

### GPU model

NVIDIA GeForce RTX 2070 Super

### Active renderer

OpenGL 4.6.0 and others

### Summary

**Description:** 

In Luanti versions 10 and 11, the cloud layer disappears when the player reaches a high altitude (above 2600 Y). It may be normal for the cloud layer to not be visible at high altitudes, possibly for performance reasons, but this is unclear. However, the cloud layer does not become visible again when the player returns to lower altitudes near the cloud layer or ground (within +/- 500 Y). The expected behavior is that the cloud layer should be visible at lower altitudes.

**Steps to Reproduce:**

Open Luanti version 10 or 11.
Install and run a new game using the vanilla minetest_game as a subgame.
Observe that clouds are normally visible.
Increase the player's Y-coordinate above 2600.
Return to ground level or near ground level (within +/- 500 Y).
Observe that the cloud layer is no longer visible. 
Quit the game and start it again, the cloud layer is once again visible.

**Expected Behavior:** 

The cloud layer should remain visible at lower altitudes, especially around ground level or near ground level (within +/- 500 Y), even after the player has reached a high altitude.

**Actual Behavior:** 

The cloud layer disappears when the player reaches a high altitude (above 2600 Y) and does not become visible again when the player returns to lower altitudes near the cloud layer or ground.

**Environment:**

OS: [e.g., Windows 10, macOS Mojave]
Luanti Versions: 10, 11
Minetest Versions: 5.10, 5.11
Subgame: Vanilla minetest_game

**Additional Context:**

To ensure the issue was not caused by any mods, I downloaded fresh zip files of Minetest versions 5.8, 5.9, 5.10, and 5.11. I only installed the vanilla minetest_game subgame. The issue did not occur in versions 5.8 or 5.9.

### Steps to reproduce

**Steps to Reproduce:**

Open Luanti version 10 or 11.
Install and run a new game using the vanilla minetest_game as a subgame.
Observe that clouds are normally visible.
Increase the player's Y-coordinate above 2600.
Return to ground level or near ground level (within +/- 500 Y).
Observe that the cloud layer is no longer visible. 
Quit the game and start it again, the cloud layer is once again visible.

### LINKED ISSUE #15804: 'Fall bobbing' is completely busted
### Luanti version

```true
Luanti 5.11.0-dev (Linux)
Using LuaJIT 2.1.1703358377
Built by GCC 13.3
Running on Linux/6.8.0 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Operating system and version

Kubuntu 24.04

### Summary

As the title suggests, this feature is completely broken in a number of ways:

- It doesn't apply if the player jumps off an edge, only by walking off
- It doesn't apply when falling from non-full nodes (ex. slabs) from what I can tell
- It only applies when falling from one or two nodes up
- It appears to be random whether the effect is actually applied, even if the other conditions are satisfied

From testing with the teleport command it seems like the reason for most of these conditions are that it will only apply if falling from 1.99657 to 2.000999 nodes, or from 1.097494 to 1.101998 nodes (i.e. `/teleport ~ ~<height> ~`).

Another notable issue is that unlike `view_bobbing_amount`, `fall_bobbing_amount` has no sane limit in the settings menu (currently can go up to 100) and so the player can set it to a value that will clip their camera completely underground. This doesn't allow any kind of cheating since the screen will be black unless the player has the `noclip` priv, but it is really ugly.

Overall I really don't get how this feature is meant to work or the intent behind how it's implemented, especially given that `fall_bobbing_amount` defaults to a completely imperceptible 0.03 which makes it seem like it isn't meant to be there at all.

It'd be nice if it was fixed, but to be honest no one would miss it if it were just removed entirely, and looking at [this](https://github.com/luanti-org/luanti/blob/166e02955e719580772ebaabaf70d30300e18fec/src/client/camera.cpp#L354), it might not be worth the time of any dev.

### Steps to reproduce

Set `fall_bobbing_amount` to something high like 10 to make the effect obvious, walk around and fall/jump off various heights with normal physics settings and note the differences.

Stand on a full node and teleport to various heights up relative to the current position.

### LINKED ISSUE #15822: [Linux] Crash (Resource deadlock avoided) while trying to start server with ncurses terminal enabled
#### Client
```
Luanti 5.12.0-dev-f4bdf72aa (Linux)
Using LuaJIT 2.1.1736781742
Built by GCC 11.4
Running on Linux/5.15.0 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```
#### Server
```
Luanti 5.12.0-dev-abcd2e0b8 (Linux)
Using LuaJIT 2.1.1736781742
Built by GCC 10.2
Running on Linux/5.10.0 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
STATIC_SHAREDIR="/usr/share/luanti"
STATIC_LOCALEDIR="/usr/share/locale"
```

### Operating system and version

**Client:** Ubuntu 22.04 LTS, Xfce 4.18
**Server:** Debian 11

### CPU model

**Client:** Pentium(R) Dual-Core  CPU      E6300  @ 2.80GHz
**Server:** Intel Xeon Processor (Skylake, IBRS)

### GPU model

**Client:** NVIDIA GeForce GT 710

### Active renderer

**Client:** X11, OpenGL 4.6.0

### Summary

Trying to run the server with `--terminal` in command line it crashes with message `terminate called after throwing an instance of 'std::system_error'` followed by `Resource deadlock avoided` error message
Happens in both Ubuntu 22.04 LTS (Client) & Debian 11 (Server) builds, running both `luanti --server` and `luantiserver` command line, Local build of LuaJIT updated to the latest version. Terminal output:
```
========================
Begin log output over terminal (no stdout/stderr backlog during that)
terminate called after throwing an instance of 'std::system_error'
  what():  Resource deadlock avoided
Aborted
```
This bug might some times cause some world files not to be created correctly if the world was not loaded before, causing error next time world would load.

<details>
<summary>Gdb backtrace of debug build</summary>

```
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737303127616) at ./nptl/pthread_kill.c:44
        tid = <optimized out>
        ret = 0
        pd = 0x7ffff4f5a640
        old_mask = {__val = {7957695015409771384, 281470681751296, 140737335031587, 140737335031587, 0, 255, 18446462598749617920, 18446744073709551360, 0, 0, 140737335031587, 140737335031587, 0, 0, 0, 280375465082880}}
        ret = <optimized out>
        pd = <optimized out>
        old_mask = <optimized out>
        ret = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
        resultvar = <optimized out>
        resultvar = <optimized out>
        __arg3 = <optimized out>
        __arg2 = <optimized out>
        __arg1 = <optimized out>
        _a3 = <optimized out>
        _a2 = <optimized out>
        _a1 = <optimized out>
        __futex = <optimized out>
        resultvar = <optimized out>
        __arg3 = <optimized out>
        __arg2 = <optimized out>
        __arg1 = <optimized out>
        _a3 = <optimized out>
        _a2 = <optimized out>
        _a1 = <optimized out>
        __futex = <optimized out>
        __private = <optimized out>
        __oldval = <optimized out>
        result = <optimized out>
#1  __pthread_kill_internal (signo=6, threadid=140737303127616) at ./nptl/pthread_kill.c:78
No locals.
#2  __GI___pthread_kill (threadid=140737303127616, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
No locals.
#3  0x00007ffff6bee476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
        ret = <optimized out>
#4  0x00007ffff6bd47f3 in __GI_abort () at ./stdlib/abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x7ffff4f55480, sa_sigaction = 0x7ffff4f55480}, sa_mask = {__val = {140737335031456, 1, 140737335031587, 3432, 140737333397985, 93825010983680, 10, 140737335031456, 140737303127616, 17, 140737333430224, 2, 0, 0, 0, 
              0}}, sa_flags = 0, sa_restorer = 0x0}
        sigs = {__val = {32, 35322347913216, 18446744073709551615, 18446744073709551615, 2314850208470540320, 0, 18446744073709551615, 281474976710655, 16646394, 16711931, 71777205704392953, 0, 0, 0, 0, 0}}
#5  0x00007ffff6f7eb9e in __gnu_cxx::__verbose_terminate_handler () at ../../../../src/libstdc++-v3/libsupc++/vterminate.cc:95
        terminating = true
        t = <optimized out>
#6  0x00007ffff6f8a20c in __cxxabiv1::__terminate (handler=<optimized out>) at ../../../../src/libstdc++-v3/libsupc++/eh_terminate.cc:48
No locals.
#7  0x00007ffff6f8a277 in std::terminate () at ../../../../src/libstdc++-v3/libsupc++/eh_terminate.cc:58
No locals.
```

</details>

**Edit:** Found a commit probably causing this bug (found by using `git bisect`): e5542e5b024719bc5f1b111fb2e3eded3fbffca6 (Remove or restrict some client settings (#15633), by @sfan5), it has alot of changed files and also I'm not sure which ones might cause this.
**Edit2:** It appears there're some code still referencing the setting name already removed, `disable_escape_sequences`. If the code it is not needed and/or unused, such code referencing it should also be removed. Excerpt from `debug.txt`:
```
2025-02-26 16:20:16: [Main]: Using game specified by --gameid on the command line
2025-02-26 16:20:16: ACTION[Main]: [log] modname="log"
2025-02-26 16:20:16: ACTION[Main]: [log] modpath="/home/juozas/luanti_test/bin/../games/devtest/mods/log"
2025-02-26 16:20:16: ACTION[Main]: [log] worldpath="/home/juozas/luanti_test/bin/../worlds/world"
2025-02-26 16:20:16: ERROR[TerminalThread]: An unhandled exception occurred: "Setting [disable_escape_sequences] not found."
```
**Edit3:** The lines probably causing it:
https://github.com/luanti-org/luanti/blob/415e96184d41a1bda614726aaf3aebf9d05b4c3e/src/terminal_chat_console.cpp#L336-L339

### Steps to reproduce

Run the server on Linux with `--terminal` in the command line

### LINKED ISSUE #15846: SIGABRT when using dynamic shadows. Assertion `!(widthOfViewVolume == 0.f)` fails.
### Luanti version

```true
Luanti 5.12.0-dev-debug-90121dc66 (Linux)
Using LuaJIT 2.1.1731601260
Built by GCC 14.2
Running on Linux/6.13.4 x86_64
BUILD_TYPE=Debug
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Operating system and version

openSUSE Tumbleweed (20250224)

### CPU model

Intel i7-12700F (12th)

### GPU model

NVIDIA GeForce RTX 3080 (12gb) [drv 570.86.16]

### Active renderer

4.6.0 / opengl / SDL

### Summary

Howdy. It seems there is a bug with dynamic shadows. Here is my `./luanti --debugger` output:
```shell
luanti: /home/user/luanti/irr/include/matrix4.h:1316: irr::core::CMatrix4<T>& irr::core::CMatrix4<T>::buildProjectionMatrixOrthoLH(irr::f32, irr::f32, irr::f32, irr::f32, bool) [with T = float; irr::f32 = float]: Assertion `!(widthOfViewVolume == 0.f)' failed.

Thread 1 "luanti" received signal SIGABRT, Aborted.
0x00007ffff6c9a13c in __pthread_kill_implementation () from /lib64/libc.so.6
#0  0x00007ffff6c9a13c in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x00007ffff6c41436 in raise () from /lib64/libc.so.6
#2  0x00007ffff6c2891a in abort () from /lib64/libc.so.6
#3  0x00007ffff6c2882e in __assert_fail_base.cold () from /lib64/libc.so.6
#4  0x00007ffff6c39256 in __assert_fail () from /lib64/libc.so.6
#5  0x00000000005c6970 in irr::core::CMatrix4<float>::buildProjectionMatrixOrthoLH (this=0x24ebc7c, widthOfViewVolume=0, heightOfViewVolume=0, zNear=0, zFar=0, zClipFromZero=false) at /home/user/luanti/irr/include/matrix4.h:1316
#6  0x000000000063e7c0 in DirectionalLight::createSplitMatrices (this=0x24ebb70, cam=0x1e09ae0) at /home/user/luanti/src/client/shadows/dynamicshadows.cpp:75
#7  0x000000000063e827 in DirectionalLight::updateCameraOffset (this=0x24ebb70, cam=0x1e09ae0) at /home/user/luanti/src/client/shadows/dynamicshadows.cpp:89
#8  0x000000000059ede9 in Game::updateCameraOffset (this=0x7fffffffc3a0) at /home/user/luanti/src/client/game.cpp:3005
#9  0x000000000059378c in Game::run (this=0x7fffffffc3a0) at /home/user/luanti/src/client/game.cpp:1008
#10 0x00000000005a6a32 in the_game (kill=0x11f76a0 <porting::g_killed>, input=0x1b71810, rendering_engine=0x1242830, start_data=..., error_message="", chat_backend=..., reconnect_requested=0x7fffffffc83f) at /home/user/luanti/src/client/game.cpp:4164
#11 0x000000000052a7c3 in ClientLauncher::run (this=0x7fffffffd390, start_data=..., cmd_args=...) at /home/user/luanti/src/client/clientlauncher.cpp:203
#12 0x00000000009b8d92 in main (argc=2, argv=0x7fffffffd5a8) at /home/user/luanti/src/main.cpp:265
```

When using `enable_dynamic_shadows = false` the bug does not seem to happen, the game seems to run fine then.

### Steps to reproduce

 -  Enable dynamic shadows
 - Create a new world using the [void](https://content.luanti.org/packages/Linuxdirk/void/) game using "singlenode" mapgen
 - Grant yourself the "fly" privilege, fly around while moving the camera randomly
 - After a few seconds the game should SIGABRT

### LINKED ISSUE #15847: credits.json file is corrupt in 5.11 client
### Luanti version

```true
Luanti 5.11.0 (Linux)
Using LuaJIT 2.1.1736781742
Built by GCC 9.4
Running on Linux/5.15.0 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=0
USE_SOUND=1
STATIC_SHAREDIR="/usr/local/share/luanti"
```

### Operating system and version

Ubuntu 20.04

### CPU model

Intel Core I3-10100

### GPU model

NVidia RTX-2060

### Active renderer

4.6.0/OpenGl/SDL

### Summary

Many thanks to BlockHead for figuring out what was going on.  I quote him here:
"There's a JSON syntax error with a comma at the end of the list of contributors "Zemtzov7",. Lua would allow a comma here but not a strict JSON parser."
It appears that this may or may not cause an error, depending upon libraries installed on the target system.

Diff:
```
diff /usr/local/share/luanti/builtin/mainmenu/credits.json.bad /usr/local/share/luanti/builtin/mainmenu/credits.json
60c60
< 		"Zemtzov7",
---
> 		"Zemtzov7"

```

### Steps to reproduce

Compile client and launch on an affected system

### LINKED ISSUE #15854: "Camera in clouds" detection is broken (repeats?)
Luanti 415e96184

as you can see the clouds are well below:
Image
now I move up a few nodes and everything turns white just as if I was in the clouds:
Image

### PR DESCRIPTION
**Pull request by sfan5**
fixes #15822
fixes #15761
fixes #15804
fixes #15847
fixes #15846
fixes #15854
fixes #15798

## To do

This PR is Ready for Review.

## How to test

varies

### CODE REVIEW

**Review by SmallJoker — APPROVED** [review]
The devtest unittests pass.
Code looks good and works. Perhaps fall bobbing could be reimplemented properly later, but I don't really mind about that.

**Comment by sfan5** [comment]
@SmallJoker please re-review, I pushed more :smiley:

**Comment by grorp** [comment]
Here's a list of all the recent shadowmap update changes, to help me not to lose track:

b861f0c5c59546b64e937fdf384634175df4a372
eb8b44981754ba5f13be3caa0de63b18937554b4
8654e16725f56879e2d76915e5b06fe6cf40c140
c31657d8b890d739930a388dcc4f49840240265f (in this PR, not merged yet)
ef8c7d80509d518260b389ed5145be9f81ed86f4 (in this PR, not merged yet)

and all of them in a diff: https://github.com/grorp/luanti/compare/7c6ade0fc5d4fccb3af190f54ca869a799fc3782...f2c7f8fc9cd4dcb1484939ccab5fb29ca7c58b5e

**Comment by sfan5** [comment]
to explain:

> b861f0c5c59546b64e937fdf384634175df4a372: `updateCameraOffset` is just refactor and has no effect & added a bug
> eb8b44981754ba5f13be3caa0de63b18937554b4: removed bug
> 8654e16725f56879e2d76915e5b06fe6cf40c140: unrelated
> c31657d8b890d739930a388dcc4f49840240265f (in this PR, not merged yet): merely an assertion fix
> ef8c7d80509d518260b389ed5145be9f81ed86f4 (in this PR, not merged yet): actual fix for flickering

File: src/util/numeric.h [hunk 1]
```diff
@@ -15,14 +15,16 @@
...
 
-#define rangelim(d, min, max) ((d) < (min) ? (min) : ((d) > (max) ? (max) : (d)))
-#define myfloor(x) ((x) < 0.0 ? (int)(x) - 1 : (int)(x))
-// The naive swap performs better than the xor version
-#define SWAP(t, x, y) do { \
-	t temp = x; \
-	x = y; \
-	y = temp; \
-} while (0)
+// Like std::clamp but allows mismatched types
```
Comment (SmallJoker) [inline src/util/numeric.h:18]: New warnings:
```C++
In file included from src/chat.cpp:16:
src/util/numeric.h: In instantiation of ‘constexpr T rangelim(const T&, const T2&, const T3&) [with T = unsigned int; T2 = int; T3 = int]’:
src/chat.cpp:864:25:   required from here
src/util/numeric.h:22:15: warning: comparison of integer expressions of different signedness: ‘const unsigned int’ and ‘const int’ [-Wsign-compare]
   22 |         if (d < min)
      |             ~~^~~~~
src/util/numeric.h:24:15: warning: comparison of integer expressions of different signedness: ‘const unsigned int’ and ‘const int’ [-Wsign-compare]
   24 |         if (d > max)
      |             ~~^~~~~
```
.. and the same for
* src/client/renderingengine.cpp:338:23
* src/emerge.cpp:109:27

Whereas technically correct, I am not very sure whether it's helpful to require the `{number}U` notation in such cases.

Comment (sfan5) [reply src/util/numeric.h:18]: I agree, but I'm not sure why these didn't raise warnings before. The comparison was just hidden in the macro. :thinking:

Comment (Desour) [reply src/util/numeric.h:18]: With the macro, it's still literals, probably that makes a difference.
I.e. `a < 10` with an unsigned int a doesn't produce warnings. But with the template, `10` is type int.

Comment (Desour) [inline src/util/numeric.h:18]: And it's no UB with nan.

File: irr/include/vector3d.h [hunk 2]
```diff
@@ -33,6 +33,12 @@ class vector3d
 	explicit constexpr vector3d(T n) :
 			X(n), Y(n), Z(n) {}
 
+	template <class U>
+	constexpr static vector3d<T> from(const vector3d<U> &other)
```
Comment (Desour) [inline irr/include/vector3d.h:37]: Amazing!
Can we also have this for vector2d?

**Review by Desour — COMMENTED** [review]
Are we sure we want to just remove the fall bobbing feature? It makes the player feel even more like a stone.

File: irr/include/vector3d.h (hunk 2 above)
Comment (sfan5) [reply irr/include/vector3d.h:37]: we do, I actually stole it from there

**Comment by sfan5** [comment]
> Are we sure we want to just remove the fall bobbing feature?

does it do something for you? it doesn't for me.

**Comment by Desour** [comment]
> > Are we sure we want to just remove the fall bobbing feature?
> 
> does it do something for you? it doesn't for me.

It used to do something for me.

File: irr/include/irrMath.h [hunk 3]
```diff
@@ -18,47 +18,38 @@ namespace core
...
 #endif
 //! Constant for PI.
-const f32 PI = 3.14159265359f;
-
-//! Constant for reciprocal of PI.
-const f32 RECIPROCAL_PI = 1.0f / PI;
-
-//! Constant for half of PI.
-const f32 HALF_PI = PI / 2.0f;
+constexpr f32 PI = 3.14159265359f;
```
Comment (nerzhul) [inline irr/include/irrMath.h:28]: shouldn't we rely on M_PI and M_PIl in math.h ?

File: irr/include/irrMath.h [hunk 4]
```diff
@@ -85,44 +76,44 @@ inline f32 degToRad(f32 degrees)
...
 template <class T>
 inline const T &max_(const T &a, const T &b, const T &c)
 {
 	return a < b ? max_(b, c) : max_(a, c);
 }
 
-//! returns abs of two values. Own implementation to get rid of STL (VS6 problems)
+//! returns abs of two values.
 template <class T>
 inline T abs_(const T &a)
```
Comment (nerzhul) [inline irr/include/irrMath.h:114]: i understand this use, is there many calls or can we remove it to use std::abs when needed ?

File: src/client/clouds.cpp [hunk 5]
```diff
@@ -366,6 +373,19 @@ void Clouds::render()
 	if (SceneManager->getSceneNodeRenderPass() != scene::ESNRP_TRANSPARENT)
 		return;
 
+#if 0
```
Comment (nerzhul) [inline src/client/clouds.cpp:376]: can you add a comment to explain why this disabled code is there ?

File: irr/include/irrMath.h (hunk 4 above)
Comment (sfan5) [reply irr/include/irrMath.h:114]: there aren't many, but I'll leave the cleanup of this for someone else.

File: irr/include/irrMath.h (hunk 3 above)
Comment (sfan5) [reply irr/include/irrMath.h:28]: sure.

File: src/client/shadows/dynamicshadows.cpp [hunk 6]
```diff
@@ -86,6 +86,8 @@ DirectionalLight::DirectionalLight(const u32 shadowMapResolution,
 
 void DirectionalLight::updateCameraOffset(const Camera *cam)
 {
+	if (future_frustum.zFar == 0.0f) // not initialized
```
[the remark this answers is not in the document]
Comment (sfan5) [reply src/client/shadows/dynamicshadows.cpp:89]: do you have something in mind?

File: irr/include/irrMath.h [hunk 7]
```diff
@@ -85,44 +76,44 @@ inline f32 degToRad(f32 degrees)
...
 {
 	return a < b ? min_(a, c) : min_(b, c);
 }
 
-//! returns maximum of two values. Own implementation to get rid of the STL (VS6 problems)
+//! returns maximum of two values.
 template <class T>
 inline const T &max_(const T &a, const T &b)
 {
 	return a < b ? b : a;
```
[the remark this answers is not in the document]
Comment (sfan5) [reply irr/include/irrMath.h:102]: you'd think so but the engine starts crashing if you do that. I have no idea.

[the remark this answers is not in the document]
Comment (Desour) [reply irr/include/irrMath.h:102]: `std::max` doesn't allow nan.

File: src/client/game.cpp [hunk 8]
```diff
@@ -3001,8 +2989,13 @@ void Game::updateCameraOffset()
 
 	if (!m_flags.disable_camera_update) {
 		auto *shadow = RenderingEngine::get_shadow_renderer();
-		if (shadow)
+		if (shadow) {
 			shadow->getDirectionalLight().updateCameraOffset(camera);
+			// FIXME: I bet we can be smarter about this and don't need to redraw
+			// the shadow map at all, but this is for someone else to figure out.
+			if (!g_settings->getFlag("performance_tradeoffs"))
```
Comment (lhofhansl) [inline src/client/game.cpp:2996]: Instead of this, I would prefer to bring back the camera offset that does not change at fixed positions.
Right could move back and forth just one node and keep switching the offset, whereas before you also had to move at least 200 nodes. Then I do not think we need to guard this by "performance_tradeoffs".
