### PR TITLE
[no squash] httpfetch improvements

### LINKED ISSUE #14846: HTTP {`PUT`|`DELETE`} request without `data` gets stuck
### Minetest version

```true
Minetest 5.9.0-dev-9a1501ae8 (Linux)
Using LuaJIT 2.1.1703358377
Built by GCC 13.2
BUILD_TYPE=Release
USE_CURL=1
...
```

### Operating system and version

Ubuntu 24.04 LTS

### Summary

After some time the request, that have no `data` field gets stuck.
MT doesn't even send it (tested with WireShark).

**Noticed:** that after exiting MT with a stuck request, you need to press ctrl+c several times (it looks like CURL is still processing something)

### Steps to reproduce

I reproduce this on `devtest` game, by adding mod `http` with follow `init.lua`:
```lua
local http_api = minetest.request_http_api()
if not http_api then
    minetest.log("error", "You should add mod `http` into `secure.http_mods` setting in your `minetest.conf`.")
    return
end



local function send(request)
    print("sending: " .. dump(request))
    http_api.fetch(request, function(result)
        print(dump(result))
    end)
end

send({
    url = "http://0.0.0.0/api/clans/20/players/215",
    timeout = 5,
    method = "PUT"
})

minetest.after(60*1.5, function()
    send({
        url = "http://0.0.0.0/api/clans/20/players/215",
        timeout = 5,
        method = "PUT",
        --data = {
        --    _mt_workaround = "fixme"
        --}
    })
end)
```

**Output:**
```
sending: {
        timeout = 5,
        method = "PUT",
        url = "http://0.0.0.0/api/clans/20/players/215"
}
2024-07-12 03:52:01: ACTION[ServerStart]: [log] Callback: on_mods_loaded()
         __.               __.                 __.  
  _____ |__| ____   _____ /  |_  _____  _____ /  |_ 
 /     \|  |/    \ /  __ \    _\/  __ \/   __>    _\
|  Y Y  \  |   |  \   ___/|  | |   ___/\___  \|  |  
|__|_|  /  |___|  /\______>  |  \______>_____/|  |  
      \/ \/     \/         \/                  \/   
2024-07-12 03:52:01: ACTION[ServerStart]: World at [bin/../worlds/sdsds]
2024-07-12 03:52:01: ACTION[ServerStart]: Server for gameid="devtest" listening on 0.0.0.0:30000.
{
        succeeded = true,
        code = 200,
        data = "{\"id\":215,\"name\":\"Alek_one\",\"race\":\"hobbit\",\"gender\":\"male\",\"experience\":0,\"is_online\":false,\"last_login\":\"2024-07-11 19:20:16\",\"clan_id\":20,\"created_at\":\"2024-07-11 19:20:16\",\"updated_at\":\"2024-07-11 19:52:23\"}",
        timeout = false,
        completed = true
}
2024-07-12 03:52:01: ACTION[Server]: Alek [127.0.0.1] joins game. List of players: Alek
sending: {
        timeout = 5,
        method = "PUT",
        url = "http://0.0.0.0/api/clans/20/players/215"
}
2024-07-12 03:55:30: ACTION[Server]: Alek leaves game. List of players: 
2024-07-12 03:55:31: ACTION[ServerStop]: Server: Shutting down
^C^C^C
```

#### EDIT:
possible this will be handy:
- https://github.com/minetest/minetest/issues/14394

### PR DESCRIPTION
**Pull request by sfan5**
fixes #14846

## How to test

1)
```lua
local http_api = assert(minetest.request_http_api())
local function test()
	http_api.fetch({
		url = "https://httpbin.org/put",
		method = "PUT",
	}, function(result)
	    print(dump(result))
	end)
end
minetest.after(1.2, test)
minetest.after(6, test)
```
should work without freezing

2)
```lua
local http_api = assert(minetest.request_http_api())
local function test()
	http_api.fetch({
		url = "https://httpbin.org/put",
		method = "PUT",
		multipart = true,
		data = {hmm = "yes"},
	}, function(result)
	    print(dump(result))
	end)
end
minetest.after(1.10, test)
```
should complete successfully

3)
```lua
local http_api = assert(minetest.request_http_api())
local function test()
	http_api.fetch({
		url = "https://www.luanti.org/",
		method = "HEAD",
	}, function(result)
	    print(dump(result))
	end)
end
minetest.after(1.25, test)
```
should complete successfully

### CODE REVIEW

File: src/httpfetch.h [hunk 1]
```diff
@@ -55,23 +55,22 @@ struct HTTPFetchRequest
...
 
-	// Raw data of the request overrides fields
+	// Raw data of the request overrides fields (ignored if multipart)
 	std::string raw_data;
 
 	// If not empty, should contain entries such as "Accept: text/html"
 	std::vector<std::string> extra_headers;
 
-	// useragent to use
+	// Uset agent to send
```
Comment (SmallJoker) [inline src/httpfetch.h:73]: What does `Uset` mean here?

File: src/httpfetch.cpp [hunk 2]
```diff
@@ -275,55 +275,60 @@ HTTPFetchOngoing::HTTPFetchOngoing(const HTTPFetchRequest &request_,
...
+				str += "=";
+				str += urlencode(field.second);
 			}
+			curl_easy_setopt(curl, CURLOPT_POSTFIELDSIZE, str.size());
+			curl_easy_setopt(curl, CURLOPT_COPYPOSTFIELDS, str.c_str());
+		} else {
+			// We must set the fields to an empty buffer (not NULL!)
+			// or curl would try to read from stdin.
+			curl_easy_setopt(curl, CURLOPT_POSTFIELDSIZE, 0);
+			curl_easy_setopt(curl, CURLOPT_POSTFIELDS, "");
```
Comment (SmallJoker) [inline src/httpfetch.cpp:325]: Couldn't we merge this with the `if (!request.raw_data.empty()) {` branch above? It would do the same thing.

File: src/httpfetch.cpp [hunk 3]
```diff
@@ -275,55 +275,60 @@ HTTPFetchOngoing::HTTPFetchOngoing(const HTTPFetchRequest &request_,
...
+		curl_easy_setopt(curl, CURLOPT_POST, 1);
+		break;
+	case HTTP_PUT:
+		curl_easy_setopt(curl, CURLOPT_CUSTOMREQUEST, "PUT");
+		break;
+	case HTTP_DELETE:
+		curl_easy_setopt(curl, CURLOPT_CUSTOMREQUEST, "DELETE");
+		break;
+	}
+
```
Comment (SmallJoker) [inline src/httpfetch.cpp:293]: Else? Fail silently? Perhaps log a warning to uncover such incorrect API uses.

File: src/httpfetch.cpp (hunk 2 above)
Comment (sfan5) [reply src/httpfetch.cpp:327]: Will do

**Review by SmallJoker — APPROVED** [review]
LGTM. Thank you.

File: doc/lua_api.md [hunk 4]
```diff
@@ -5780,6 +5780,8 @@ Utilities
       particle_blend_clip = true,
       -- The `match_meta` optional parameter is available for `InvRef:remove_item()` (5.12.0)
       remove_item_match_meta = true,
+      -- The HTTP API supports the HEAD and PATCH methods (5.12.0)
+      httpfetch_additional_methods = true,
```
Comment (SmallJoker) [inline doc/lua_api.md:5784]: And when there's a new method, will the field be called `httpfetch_additional_methods_new_additionals`?
Jokes aside, it might be more suitable to name it `httpfetch_have_HEAD_PATCH = true` or similar.

Comment (sfan5) [reply doc/lua_api.md:5784]: If we decide the update the API again it's likely that we would make `method` a fully custom field, so the feature flag would be different (and also the last time this feature would be touched).
But I can change it if you want.

Comment (SmallJoker) [reply doc/lua_api.md:5784]: mhm okay. Whatever. Fine by me.
