### PR TITLE
Revert "Detect mouse moving out of inventory slot (#16101)"

### LINKED ISSUE #16271: Client freezes when opening 3d_armor inv page in unified_inventory
### Luanti version

```true
Note: dirty due to having a one-liner that logs chat messages added and is unrelated.

Luanti 5.13.0-dev-81d62d01d-dirty (Linux)
Using LuaJIT 2.1.0-beta3
Built by GCC 12.2
Running on Linux/6.1.0 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=0
USE_SOUND=1
STATIC_SHAREDIR="."
```

### Operating system and version

Debian Bookworm

### CPU model

Ryzen 5600G

### GPU model

IGP

### Active renderer

 4.6/opengl/SDL 2.26.5

### Summary

With latest git, the client freezes when calling up the 3d armor page on the inventory formspec on the Your Land server.
Reproduced with minetest_game + 3d_armor + unified_inventory.
Reproduced on the Your  Land server by the server admin with diffrent hardware and likewise latest git.

### Steps to reproduce

Use latest git, join server (i.e. Your Land or other one with 3d_armor + suitable inventory mod), call up inventory, click on the armor tab of the inventory - and the client freezes.

Ran luanti in gdb as instructed. Output of `thread apply all bt`:
<pre>
Thread 26 (Thread 0x7fffa8d236c0 (LWP 843530) "MeshUpdate"):
#0  __futex_abstimed_wait_common64 (private=<optimized out>, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x55555719d1e0) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x55555719d1e0, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=<optimized out>, cancel=cancel@entry=true) at ./nptl/futex-internal.c:87
#2  0x00007ffff6ca4f7b in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x55555719d1e0, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=<optimized out>) at ./nptl/futex-internal.c:139
#3  0x00007ffff6cafcff in do_futex_wait (sem=sem@entry=0x55555719d1e0, abstime=0x0, clockid=0) at ./nptl/sem_waitcommon.c:111
#4  0x00007ffff6cafd90 in __new_sem_wait_slow64 (sem=0x55555719d1e0, abstime=0x0, clockid=0) at ./nptl/sem_waitcommon.c:183
#5  0x00005555556cc338 in UpdateThread::run() ()
#6  0x0000555555b2b769 in Thread::threadProc(Thread*) ()
#7  0x00007ffff6ed44a3 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007ffff6ca81f5 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#9  0x00007ffff6d2889c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 25 (Thread 0x7fffa95246c0 (LWP 843529) "MeshUpdate"):
#0  __futex_abstimed_wait_common64 (private=<optimized out>, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x5555571df4d0) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x5555571df4d0, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=<optimized out>, cancel=cancel@entry=true) at ./nptl/futex-internal.c:87
#2  0x00007ffff6ca4f7b in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x5555571df4d0, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=<optimized out>) at ./nptl/futex-internal.c:139
#3  0x00007ffff6cafcff in do_futex_wait (sem=sem@entry=0x5555571df4d0, abstime=0x0, clockid=0) at ./nptl/sem_waitcommon.c:111
#4  0x00007ffff6cafd90 in __new_sem_wait_slow64 (sem=0x5555571df4d0, abstime=0x0, clockid=0) at ./nptl/sem_waitcommon.c:183
#5  0x00005555556cc338 in UpdateThread::run() ()
#6  0x0000555555b2b769 in Thread::threadProc(Thread*) ()
#7  0x00007ffff6ed44a3 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007ffff6ca81f5 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#9  0x00007ffff6d2889c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 24 (Thread 0x7fffa9d256c0 (LWP 843528) "MeshUpdate"):
#0  __futex_abstimed_wait_common64 (private=<optimized out>, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x555556dced50) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x555556dced50, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=<optimized out>, cancel=cancel@entry=true) at ./nptl/futex-internal.c:87
#2  0x00007ffff6ca4f7b in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x555556dced50, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=<optimized out>) at ./nptl/futex-internal.c:139
#3  0x00007ffff6cafcff in do_futex_wait (sem=sem@entry=0x555556dced50, abstime=0x0, clockid=0) at ./nptl/sem_waitcommon.c:111
#4  0x00007ffff6cafd90 in __new_sem_wait_slow64 (sem=0x555556dced50, abstime=0x0, clockid=0) at ./nptl/sem_waitcommon.c:183
#5  0x00005555556cc338 in UpdateThread::run() ()
#6  0x0000555555b2b769 in Thread::threadProc(Thread*) ()
#7  0x00007ffff6ed44a3 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007ffff6ca81f5 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#9  0x00007ffff6d2889c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 23 (Thread 0x7fffaa5266c0 (LWP 843527) "MeshUpdate"):
#0  __futex_abstimed_wait_common64 (private=<optimized out>, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x555556dbe340) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x555556dbe340, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=<optimized out>, cancel=cancel@entry=true) at ./nptl/futex-internal.c:87
#2  0x00007ffff6ca4f7b in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x555556dbe340, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=<optimized out>) at ./
nptl/futex-internal.c:139
#3  0x00007ffff6cafcff in do_futex_wait (sem=sem@entry=0x555556dbe340, abstime=0x0, clockid=0) at ./nptl/sem_waitcommon.c:111
#4  0x00007ffff6cafd90 in __new_sem_wait_slow64 (sem=0x555556dbe340, abstime=0x0, clockid=0) at ./nptl/sem_waitcommon.c:183
#5  0x00005555556cc338 in UpdateThread::run() ()
#6  0x0000555555b2b769 in Thread::threadProc(Thread*) ()
#7  0x00007ffff6ed44a3 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007ffff6ca81f5 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#9  0x00007ffff6d2889c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 22 (Thread 0x7fffccad36c0 (LWP 843517) "ConnectionRecei"):
#0  0x00007ffff6d1b21f in __GI___poll (fds=0x7fffccacf8e0, nfds=1, timeout=500) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x0000555555afb113 in UDPSocket::Receive(Address&, void*, int) ()
#2  0x0000555555aff97f in con::ConnectionReceiveThread::run() ()
#3  0x0000555555b2b769 in Thread::threadProc(Thread*) ()
#4  0x00007ffff6ed44a3 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff6ca81f5 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#6  0x00007ffff6d2889c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 21 (Thread 0x7fffce2d66c0 (LWP 843516) "ConnectionSend"):
#0  __futex_abstimed_wait_common64 (private=<optimized out>, cancel=true, abstime=0x7fffce2d2a00, op=393, expected=0, futex_word=0x555556765880) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x555556765880, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x7fffce2d2a00, private=<optimized out>, cancel=cancel@entry=true) at ./nptl/futex-internal.c:87
#2  0x00007ffff6ca4f7b in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x555556765880, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x7fffce2d2a00, private=<optimized out>) at ./nptl/futex-internal.c:139
#3  0x00007ffff6cafaf0 in do_futex_wait (sem=sem@entry=0x555556765880, abstime=abstime@entry=0x7fffce2d2a00, clockid=0) at ./nptl/sem_waitcommon.c:111
#4  0x00007ffff6cafb8b in __new_sem_wait_slow64 (sem=0x555556765880, abstime=0x7fffce2d2a00, clockid=0) at ./n
ptl/sem_waitcommon.c:183
#5  0x0000555555af7946 in con::ConnectionSendThread::run() ()
#6  0x0000555555b2b769 in Thread::threadProc(Thread*) ()
#7  0x00007ffff6ed44a3 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007ffff6ca81f5 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#9  0x00007ffff6d2889c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 20 (Thread 0x7fffcdad56c0 (LWP 843515) "MinimapUpdate"):
#0  __futex_abstimed_wait_common64 (private=<optimized out>, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x55555718ae20) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x55555718ae20, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=<optimized out>, cancel=cancel@entry=true) at ./nptl/futex-internal.c:87
#2  0x00007ffff6ca4f7b in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x55555718ae20, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=<optimized out>) at ./nptl/futex-internal.c:139
#3  0x00007ffff6cafcff in do_futex_wait (sem=sem@entry=0x55555718ae20, abstime=0x0, clockid=0) at ./nptl/sem_waitcommon.c:111
#4  0x00007ffff6cafd90 in __new_sem_wait_slow64 (sem=0x55555718ae20, abstime=0x0, clockid=0) at ./nptl/sem_waitcommon.c:183
#5  0x00005555556cc338 in UpdateThread::run() ()
#6  0x0000555555b2b769 in Thread::threadProc(Thread*) ()
#7  0x00007ffff6ed44a3 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007ffff6ca81f5 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#9  0x00007ffff6d2889c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 19 (Thread 0x7fffcead76c0 (LWP 843514) "OpenALSoundMana"):
#0  __futex_abstimed_wait_common64 (private=<optimized out>, cancel=true, abstime=0x7fffcead39e0, op=393, expected=0, futex_word=0x555556058ee8) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x555556058ee8, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x7fffcead39e0, private=<optimized out>, cancel=cancel@entry=true) at ./nptl/futex-internal.c:87
#2  0x00007ffff6ca4f7b in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x555556058ee8,
 expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x7fffcead39e0, private=<optimized out>) at ./nptl/futex-internal.c:139
#3  0x00007ffff6cafaf0 in do_futex_wait (sem=sem@entry=0x555556058ee8, abstime=abstime@entry=0x7fffcead39e0, clockid=0) at ./nptl/sem_waitcommon.c:111
#4  0x00007ffff6cafb8b in __new_sem_wait_slow64 (sem=0x555556058ee8, abstime=0x7fffcead39e0, clockid=0) at ./nptl/sem_waitcommon.c:183
#5  0x00005555557cb5ff in sound::OpenALSoundManager::run() ()
#6  0x0000555555b2b769 in Thread::threadProc(Thread*) ()
#7  0x00007ffff6ed44a3 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007ffff6ca81f5 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#9  0x00007ffff6d2889c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 17 (Thread 0x7fffcd2d46c0 (LWP 843512) "CurlFetch"):
#0  __futex_abstimed_wait_common64 (private=<optimized out>, cancel=true, abstime=0x7fffcd2d0850, op=393, expected=0, futex_word=0x555555f779e0) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x555555f779e0, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x7fffcd2d0850, private=<optimized out>, cancel=cancel@entry=true) at ./nptl/futex-internal.c:87
#2  0x00007ffff6ca4f7b in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x555555f779e0, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x7fffcd2d0850, private=<optimized out>) at ./nptl/futex-internal.c:139
#3  0x00007ffff6cafaf0 in do_futex_wait (sem=sem@entry=0x555555f779e0, abstime=abstime@entry=0x7fffcd2d0850, clockid=0) at ./nptl/sem_waitcommon.c:111
#4  0x00007ffff6cafb8b in __new_sem_wait_slow64 (sem=0x555555f779e0, abstime=0x7fffcd2d0850, clockid=0) at ./nptl/sem_waitcommon.c:183
#5  0x0000555555ac3448 in CurlFetchThread::run() ()
#6  0x0000555555b2b769 in Thread::threadProc(Thread*) ()
#7  0x00007ffff6ed44a3 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007ffff6ca81f5 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#9  0x00007ffff6d2889c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 13 (Thread 0x7fffcf7fe6c0 (LWP 843495) "luanti:gdrv0"):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x55555625ab74) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x55555625ab74, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at ./nptl/futex-internal.c:87
#2  0x00007ffff6ca4f7b in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x55555625ab74, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at ./nptl/futex-internal.c:139
#3  0x00007ffff6ca75d8 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x55555625ab20, cond=0x55555625ab48) at ./nptl/pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=0x55555625ab48, mutex=0x55555625ab20) at ./nptl/pthread_cond_wait.c:618
#5  0x00007fffe8d0c059 in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#6  0x00007fffe8cbe17b in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#7  0x00007fffe8d0bf97 in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#8  0x00007ffff6ca81f5 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#9  0x00007ffff6d2889c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 11 (Thread 0x7fffcffff6c0 (LWP 843491) "luanti:shlo0"):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x555556122060) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x555556122060, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at ./nptl/futex-internal.c:87
#2  0x00007ffff6ca4f7b in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x555556122060, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at ./nptl/futex-internal.c:139
#3  0x00007ffff6ca75d8 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x555556122010, cond=0x555556122038) at ./nptl/pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=0x555556122038, mutex=0x555556122010) at ./nptl/pthread_cond_wait.c:618
#5  0x00007fffe8d0c059 in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#6  0x00007fffe8cbe17b in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#7  0x00007fffe8d0bf97 in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#8  0x00007ffff6ca81f5 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#9  0x00007ffff6d2889c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 10 (Thread 0x7fffd4ffe6c0 (LWP 843490) "luanti:sh0"):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x555556121af0) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x555556121af0, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at ./nptl/futex-internal.c:87
#2  0x00007ffff6ca4f7b in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x555556121af0, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at ./nptl/futex-internal.c:139
#3  0x00007ffff6ca75d8 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x555556121aa0, cond=0x555556121ac8) at ./nptl/pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=0x555556121ac8, mutex=0x555556121aa0) at ./nptl/pthread_cond_wait.c:618
#5  0x00007fffe8d0c059 in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#6  0x00007fffe8cbe17b in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#7  0x00007fffe8d0bf97 in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#8  0x00007ffff6ca81f5 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#9  0x00007ffff6d2889c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 9 (Thread 0x7fffd57ff6c0 (LWP 843489) "luanti:disk$0"):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x555555f80b28) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x555555f80b28, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at ./nptl/futex-internal.c:87
#2  0x00007ffff6ca4f7b in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x555555f80b28, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at ./nptl/futex-internal.c:139
#3  0x00007ffff6ca75d8 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x555555f80ad8, cond=0x555555f80b00) at ./nptl/pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=0x555555f80b00, mutex=0x555555f80ad8) at ./nptl/pthread_cond_wait.c:618
#5  0x00007fffe8d0c059 in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#6  0x00007fffe8cbe17b in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#7  0x00007fffe8d0bf97 in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#8  0x00007ffff6ca81f5 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#9  0x00007ffff6d2889c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 8 (Thread 0x7fffe8bff6c0 (LWP 843488) "luanti:cs0"):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x55555611f128) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x55555611f128, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at ./nptl/futex-internal.c:87
#2  0x00007ffff6ca4f7b in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x55555611f128, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at ./nptl/futex-internal.c:139
#3  0x00007ffff6ca75d8 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x55555611f0d8, cond=0x55555611f100) at ./nptl/pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=0x55555611f100, mutex=0x55555611f0d8) at ./nptl/pthread_cond_wait.c:618
#5  0x00007fffe8d0c059 in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#6  0x00007fffe8cbe17b in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#7  0x00007fffe8d0bf97 in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#8  0x00007ffff6ca81f5 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#9  0x00007ffff6d2889c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 7 (Thread 0x7fffeb7d86c0 (LWP 843472) "SDLTimer"):
#0  __futex_abstimed_wait_common64 (private=<optimized out>, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x555555f99b90) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x555555f99b90, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=<optimized out>, cancel=cancel@entry=true) at ./nptl/futex-internal.c:87
#2  0x00007ffff6ca4f7b in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x555555f99b90, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=<optimized out>) at ./nptl/futex-internal.c:139
#3  0x00007ffff6cafcff in do_futex_wait (sem=sem@entry=0x555555f99b90, abstime=0x0, clockid=0) at ./nptl/sem_waitcommon.c:111
#4  0x00007ffff6cafd90 in __new_sem_wait_slow64 (sem=0x555555f99b90, abstime=0x0, clockid=0) at ./nptl/sem_waitcommon.c:183
#5  0x00007ffff736aff2 in ?? () from /lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#6  0x00007ffff72c95a7 in ?? () from /lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#7  0x00007ffff72c9085 in ?? () from /lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#8  0x00007ffff736ab79 in ?? () from /lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#9  0x00007ffff6ca81f5 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#10 0x00007ffff6d2889c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 6 (Thread 0x7ffff43d76c0 (LWP 843471) "luanti"):
#0  __futex_abstimed_wait_common64 (private=<optimized out>, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x555555f7fce0) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x555555f7fce0, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=<optimized out>, cancel=cancel@entry=true) at ./nptl/futex-internal.c:87
#2  0x00007ffff6ca4f7b in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x555555f7fce0, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=<optimized out>) at ./nptl/futex-internal.c:139
#3  0x00007ffff6cafcff in do_futex_wait (sem=sem@entry=0x555555f7fce0, abstime=0x0, clockid=0) at ./nptl/sem_waitcommon.c:111
#4  0x00007ffff6cafd90 in __new_sem_wait_slow64 (sem=0x555555f7fce0, abstime=0x0, clockid=0) at ./nptl/sem_waitcommon.c:183
#5  0x00007ffff7e3da39 in ?? () from /lib/x86_64-linux-gnu/libopenal.so.1
#6  0x00007ffff7e0212d in ?? () from /lib/x86_64-linux-gnu/libopenal.so.1
#7  0x00007ffff7e3d587 in ?? () from /lib/x86_64-linux-gnu/libopenal.so.1
#8  0x00007ffff6ca81f5 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#9  0x00007ffff6d2889c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 5 (Thread 0x7ffff45d86c0 (LWP 843470) "luanti"):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x555555f7a07c) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x555555f7a07c, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at ./nptl/futex-internal.c:87
#2  0x00007ffff6ca4f7b in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x555555f7a07c, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at ./nptl/futex-internal.c:139
#3  0x00007ffff6ca75d8 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x555555f7e550, cond=0x555555f7a050) at ./nptl/pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=0x555555f7a050, mutex=0x555555f7e550) at ./nptl/pthread_cond_wait.c:618
#5  0x00007ffff6a8aa48 in pa_threaded_mainloop_wait () from /lib/x86_64-linux-gnu/libpulse.so.0
#6  0x00007ffff7e36e7e in ?? () from /lib/x86_64-linux-gnu/libopenal.so.1
#7  0x00007ffff7e3d587 in ?? () from /lib/x86_64-linux-gnu/libopenal.so.1
#8  0x00007ffff6ca81f5 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#9  0x00007ffff6d2889c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 4 (Thread 0x7ffff4dd96c0 (LWP 843469) "threaded-ml"):
#0  0x00007ffff6d1b21f in __GI___poll (fds=0x7ffff00085c0, nfds=2, timeout=651) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ffff6a8a2e1 in ?? () from /lib/x86_64-linux-gnu/libpulse.so.0
#2  0x00007ffff6a7bfa4 in pa_mainloop_poll () from /lib/x86_64-linux-gnu/libpulse.so.0
#3  0x00007ffff6a7c606 in pa_mainloop_iterate () from /lib/x86_64-linux-gnu/libpulse.so.0
#4  0x00007ffff6a7c6b0 in pa_mainloop_run () from /lib/x86_64-linux-gnu/libpulse.so.0
#5  0x00007ffff6a8a3b9 in ?? () from /lib/x86_64-linux-gnu/libpulse.so.0
#6  0x00007ffff5df133f in ?? () from /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-16.1.so
#7  0x00007ffff6ca81f5 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#8  0x00007ffff6d2889c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 1 (Thread 0x7ffff54feac0 (LWP 843464) "luanti"):
#0  0x00005555556e6270 in irr::gui::IGUIElement::getElementFromPoint(irr::core::vector2d<int> const&) ()
#1  0x00005555556e62c1 in irr::gui::IGUIElement::getElementFromPoint(irr::core::vector2d<int> const&) ()
#2  0x00005555556e62c1 in irr::gui::IGUIElement::getElementFromPoint(irr::core::vector2d<int> const&) ()
#3  0x00005555556e62c1 in irr::gui::IGUIElement::getElementFromPoint(irr::core::vector2d<int> const&) ()
#4  0x00005555556e62c1 in irr::gui::IGUIElement::getElementFromPoint(irr::core::vector2d<int> const&) ()
#5  0x000055555583d77c in GUIInventoryList::OnEvent(irr::SEvent const&) ()
#6  0x000055555581f9b9 in GUIFormSpecMenu::preprocessEvent(irr::SEvent const&) ()
#6  0x00007ffff7e36e7e in ?? () from /lib/x86_64-linux-gnu/libopenal.so.1
#7  0x00007ffff7e3d587 in ?? () from /lib/x86_64-linux-gnu/libopenal.so.1
#8  0x00007ffff6ca81f5 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#9  0x00007ffff6d2889c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 4 (Thread 0x7ffff4dd96c0 (LWP 843469) "threaded-ml"):
#0  0x00007ffff6d1b21f in __GI___poll (fds=0x7ffff00085c0, nfds=2, timeout=651) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ffff6a8a2e1 in ?? () from /lib/x86_64-linux-gnu/libpulse.so.0
#2  0x00007ffff6a7bfa4 in pa_mainloop_poll () from /lib/x86_64-linux-gnu/libpulse.so.0
#3  0x00007ffff6a7c606 in pa_mainloop_iterate () from /lib/x86_64-linux-gnu/libpulse.so.0
#4  0x00007ffff6a7c6b0 in pa_mainloop_run () from /lib/x86_64-linux-gnu/libpulse.so.0
#5  0x00007ffff6a8a3b9 in ?? () from /lib/x86_64-linux-gnu/libpulse.so.0
#6  0x00007ffff5df133f in ?? () from /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-16.1.so
#7  0x00007ffff6ca81f5 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#8  0x00007ffff6d2889c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 1 (Thread 0x7ffff54feac0 (LWP 843464) "luanti"):
#0  0x00005555556e6270 in irr::gui::IGUIElement::getElementFromPoint(irr::core::vector2d<int> const&) ()
#1  0x00005555556e62c1 in irr::gui::IGUIElement::getElementFromPoint(irr::core::vector2d<int> const&) ()
#2  0x00005555556e62c1 in irr::gui::IGUIElement::getElementFromPoint(irr::core::vector2d<int> const&) ()
#3  0x00005555556e62c1 in irr::gui::IGUIElement::getElementFromPoint(irr::core::vector2d<int> const&) ()
#4  0x00005555556e62c1 in irr::gui::IGUIElement::getElementFromPoint(irr::core::vector2d<int> const&) ()
#5  0x000055555583d77c in GUIInventoryList::OnEvent(irr::SEvent const&) ()
#6  0x000055555581f9b9 in GUIFormSpecMenu::preprocessEvent(irr::SEvent const&) ()
--Type <RET> for more, q to quit, c to continue without paging--
#7  0x0000555555c8a975 in irr::CIrrDeviceStub::postEventFromUser(irr::SEvent const&) ()
#8  0x0000555555c83e05 in irr::CIrrDeviceSDL::run() ()
#9  0x000055555573cc95 in Game::run() ()
#10 0x000055555575d9aa in the_game(int volatile*, InputHandler*, RenderingEngine*, GameStartData const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, ChatBackend&, bool*) ()
#11 0x0000555555c037dd in ClientLauncher::run(GameStartData&, Settings const&) [clone .constprop.0] ()
#12 0x00005555556ad115 in main ()
</pre>

### PR DESCRIPTION
**Pull request by Desour**
This reverts commit 81d62d01d119a5d519b923b839ea4c08900e1d1f from #16101.

Fixes #16271.
Reopens #16100.

The code was like this on purpose. In #9287 I apparently also tried it without leaving the element invisible, but noticed loops: https://github.com/luanti-org/luanti/pull/9287/commits/823db991d317b97ac91301b1f884c50e55b52a24

Description of the bug:
* You hover over a list element A.
* A makes itself invisible to get the next element at pointer (here list element B).
* A makes itself visible again.
* A does tail-call onEvent on B. (=> no stack overflow)
* B does the same.

A proper fix for #16100 can come afterwards. Let's just revert first, to spare everyone from headaches and stress.

(Sorry for not intervening in #16101 already. But I didn't really understand the bug it was trying to fix or how, so I didn't want to look at it, nor properly noticed that I'm kind of responsible for the ugly code it was touching. Also sorry for my bad code.)

## To do

This PR is a Ready for Review.

## How to test

* In devtest, use the node meta editor to set the `formspec` meta field of a node to:
```
formspec_version[6]
size[15,15]
list[current_player;main;0,5;8,4;]
list[current_player;main;0,5;8,4;]
```
* Rightclick the node.
* Hover your mouse over the overlapping lists.
* In master: Freezes.

### CODE REVIEW

**Review by grorp — APPROVED** [review]

File: src/gui/guiInventoryList.cpp [hunk 1]
```diff
@@ -203,10 +203,10 @@ bool GUIInventoryList::OnEvent(const SEvent &event)
 	if (!hovered || hovered->getID() == -1)
 		hovered = m_fs_menu;
 
-	IsVisible = was_visible;
-
 	bool ret = hovered->OnEvent(event);
 
+	IsVisible = was_visible;
```
Comment (sfan5) [inline src/gui/guiInventoryList.cpp:211]:
```suggestion
	// Do not move this before OnEvent()
	IsVisible = was_visible;
```
