### PR TITLE
Fix texture coordinates of cuboid drawtypes

### LINKED ISSUE #12266: Combining animated & world-aligned textures has alignment issues.
##### Minetest version
5.6.0-dev e7659883cc6fca343785da2a1af3890ae273abbf (latest master as of writing)

##### Summary
When using animated world-aligned textures:
- They don't perfectly align to the block (this may not be a bug)
- There are weird strips that don't match up, maybe weird off-by-one errors

##### Steps to reproduce
[Test mod: `gromit.zip`](https://github.com/minetest/minetest/files/8612054/gromit.zip)
1. Enable block bounds for alignment (<kbd>F4</kbd>)
2. Place some `gromit:*` nodes.
3. Try to make sense of it.

<details>
<summary>Video examples (above test mod)</summary>

https://user-images.githubusercontent.com/27222523/166493934-b5853b65-53ec-42e0-adc7-394a29940fa9.mp4

https://user-images.githubusercontent.com/27222523/166496529-72ae74a1-0678-428f-92e3-d6ffde8ce138.mp4

</details>

### PR DESCRIPTION
**Pull request by cx384**
- A more general solution than #16055
- Fixes #12266 and more
- Changes texture coordinates of cuboid drawtypes to stay in the [0,1] range, instead of carrying the mapblock alignment and becoming negative after transformations

## To do
Ready for review

## How to test
See that texture coordinates are correct,
align style and other texture coordinates features like rotation still work.
and check nodebox drawtype nodes.

### CODE REVIEW

File: src/client/content_mapblock.cpp [hunk 1]
```diff
@@ -185,15 +194,47 @@ static std::array<video::S3DVertex, 24> setupCuboidVertices(const aabb3f &box,
...
-				tcoords.set(-tcoords.Y, tcoords.X);
+				tcoords.set(1 - tcoords.Y, tcoords.X);
 				break;
 			case TileRotation::R180:
-				tcoords.set(-tcoords.X, -tcoords.Y);
+				tcoords.set(1 - tcoords.X, 1 - tcoords.Y);
 				break;
 			case TileRotation::R270:
-				tcoords.set(tcoords.Y, -tcoords.X);
+				tcoords.set(tcoords.Y, 1 - tcoords.X);
```
Comment (cx384) [inline src/client/content_mapblock.cpp:203]: Subtracting from 1 here is always correct, since even for texture coordinates from oversized nodeboxes, it stays aligned to the [0,1] range, and always has scale 1.
(`visual_scale` changes the mesh scale and not the texture coords scale.)

File: src/client/content_mapblock.cpp [hunk 2]
```diff
@@ -299,26 +341,6 @@ video::SColor MapblockMeshGenerator::blendLightColor(const v3f &vertex_pos,
 	return color;
 }
 
-void MapblockMeshGenerator::generateCuboidTextureCoords(const aabb3f &box, f32 *coords)
```
Comment (cx384) [inline src/client/content_mapblock.cpp:302]: This function only makes sense for nodeboxes, since it adjusts the texture coords of every box to be aligned to the node's range [0,1] (or [0,10] in block space).
Other draw types use the full texture range, or calculate their own uv map, e.g. fencelike.

File: src/client/content_mapblock.cpp [hunk 3]
```diff
@@ -1649,7 +1660,24 @@ void MapblockMeshGenerator::drawNodeboxNode()
...
 		u8 mask = getNodeBoxMask(box, solid_neighbors, sametype_neighbors);
-		drawAutoLightedCuboid(box, tiles, 6, nullptr, mask);
+
+		// Get texture coords for nodebox uv mapping
+		f32 tx1 = (box.MinEdge.X / BS) + 0.5;
+		f32 ty1 = (box.MinEdge.Y / BS) + 0.5;
+		f32 tz1 = (box.MinEdge.Z / BS) + 0.5;
+		f32 tx2 = (box.MaxEdge.X / BS) + 0.5;
+		f32 ty2 = (box.MaxEdge.Y / BS) + 0.5;
+		f32 tz2 = (box.MaxEdge.Z / BS) + 0.5;
```
Comment (sfan5) [inline src/client/content_mapblock.cpp:1670]:
```suggestion
		f32 tx1 = (box.MinEdge.X / BS) + 0.5f;
		f32 ty1 = (box.MinEdge.Y / BS) + 0.5f;
		f32 tz1 = (box.MinEdge.Z / BS) + 0.5f;
		f32 tx2 = (box.MaxEdge.X / BS) + 0.5f;
		f32 ty2 = (box.MaxEdge.Y / BS) + 0.5f;
		f32 tz2 = (box.MaxEdge.Z / BS) + 0.5f;
```

**Comment by sfan5** [comment]
to check UV coords:
```diff
diff --git a/src/client/meshgen/collector.cpp b/src/client/meshgen/collector.cpp
--- a/src/client/meshgen/collector.cpp
+++ b/src/client/meshgen/collector.cpp
@@ -25,8 +25,9 @@ void MeshCollector::append(const TileLayer &layer, const video::S3DVertex *verti
 
        u32 vertex_count = p.vertices.size();
        for (u32 i = 0; i < numVertices; i++) {
+               v2f uv{core::clamp(vertices[i].TCoords.X, 0.f, 1.f), core::clamp(vertices[i].TCoords.Y, 0.f, 1.f)};
                p.vertices.emplace_back(vertices[i].Pos + offset, vertices[i].Normal,
-                               vertices[i].Color, vertices[i].TCoords);
+                               vertices[i].Color, uv);
                m_bounding_radius_sq = std::max(m_bounding_radius_sq,
                                (vertices[i].Pos - m_center_pos).getLengthSQ());
        }
```

File: src/client/content_mapblock.cpp [hunk 4]
```diff
@@ -185,15 +194,47 @@ static std::array<video::S3DVertex, 24> setupCuboidVertices(const aabb3f &box,
...
+					y = tcoords.Y + y;
+				}
+				if (face == 3 || face == 4) {
+					x = tcoords.X + ((scale-1)-x);
+				} else {
+					x = tcoords.X + x;
+				}
+
+				tcoords.set(x * scale_factor, y * scale_factor);
+			}
```
Comment (sfan5) [inline src/client/content_mapblock.cpp:237]: this could probably be generalized by performing maths on the normal vector of the tile (do we have that?) but whatever

**Review by sfan5 — APPROVED** [review]
checked:
* world-aligned nodes
* facedir
* nodeboxes
* `gromit` test mod from #12266

**Review by Desour — CHANGES_REQUESTED** [review]
`glasslike_framed` is broken. (Also uses `drawAutoLightedCuboid` and expects nodebox-like uv.)

Found no issues otherwise (also tested with `tileable_vertical`, it works now. :tada: ). Thanks!

File: src/client/content_mapblock.cpp [hunk 5]
```diff
@@ -224,7 +266,7 @@ void MapblockMeshGenerator::drawCuboid(const aabb3f &box,
 {
 	assert(tilecount >= 1 && tilecount <= 6); // pre-condition
 
-	auto vertices = setupCuboidVertices(box, txc, tiles, tilecount);
+	auto vertices = setupCuboidVertices(box, txc, tiles, tilecount, cur_node.p);
```
Comment (Desour) [inline src/client/content_mapblock.cpp:269]: Btw. you could easily fix scale being limited to int fractions of 16 (currently it's mesh chunk size dependent then), by adding `blockpos_nodes` here. (Maybe follow up PR.)

File: src/client/content_mapblock.cpp [hunk 6]
```diff
@@ -137,11 +137,20 @@ void MapblockMeshGenerator::drawQuad(const TileSpec &tile, v3f *coords, const v3
...
+		const f32 *txc, const TileSpec *tiles, int tilecount, v3s16 alignment)
 {
 	v3f min = box.MinEdge;
 	v3f max = box.MaxEdge;
 
+	// Texture coords are [0,1] if not specified otherwise
+	f32 uniform_txc[24];
+	if (!txc) {
+		for (int i = 0; i != 24; ++i) {
+			uniform_txc[i] = (i % 4 < 2) ? 0 : 1;
```
[the remark this answers is not in the document]
Comment (sfan5) [reply src/client/content_mapblock.cpp:149]: int will implicitly convert to float no problem

[the remark this answers is not in the document]
Comment (Desour) [reply src/client/content_mapblock.cpp:149]: I know, but I find having it explicitly better for readability. :shrug:

**Comment by cx384** [comment]
Oh, I thought glasslike_framed is just a normal node mesh, should be fixed now.

File: src/client/content_mapblock.cpp (hunk 6 above)
[the remark this answers is not in the document]
Comment (cx384) [reply src/client/content_mapblock.cpp:149]: Less to write and to look at may be better, but I don't really care.

File: src/client/content_mapblock.h [hunk 7]
```diff
@@ -86,6 +86,7 @@ class MapblockMeshGenerator
 	template <typename Fn>
 	void drawCuboid(const aabb3f &box, const TileSpec *tiles, int tilecount,
 			const f32 *txc, u8 mask, Fn &&face_lighter);
+	void generateCuboidTextureCoords(aabb3f const &box, f32 *coords);
```
Comment (sfan5) [inline src/client/content_mapblock.h]: `static`

**Comment by grorp** [comment]
Some meshgen tests were added in #13616. Would testing the texture coordinates there be possible?

> also tested with `tileable_vertical`, it works now. 🎉

Hmm, it doesn't seem to be working for me, Devtest "Dirt with Snow" still appears to use repeat instead of clamp. With texture filtering enabled, and texture_min_size disabled by source code change (also visible without, but this makes it much more obvious):

dirt with snow in devtest

https://github.com/luanti-org/luanti/blob/486fb7cc4def696d115077497d4f0ed09ec1f7ff/games/devtest/mods/basenodes/init.lua#L37-L45

File: src/client/content_mapblock.h (hunk 7 above)
Comment (cx384) [reply src/client/content_mapblock.h]: Remainder to myself, don't trust old code.

**Comment by cx384** [comment]
Maybe, I'm not very familiar with our unittests.
I suppose it would be a bit much for this PR, it can always be added later, and if we add tests it should probably be done for all draw types, not only cuboids.

I haven't looked into `tileable_vertical` and `tileable_horizontal` maybe Desour knows.
With this PR, texture coordinates are inside the [0,1] range, so at least non tillable tiles should not be completely broken.

**Comment by grorp** [comment]
> Maybe, I'm not very familiar with our unittests.
> I suppose it would be a bit much for this PR, it can always be added later, and if we add tests it should probably be done for all draw types, not only cuboids.

Some unit tests are better than no unit tests :)
But yeah, it's fair if you want to consider that out of scope for this PR.

> I haven't looked into `tileable_vertical` and `tileable_horizontal` maybe Desour knows.
> With this PR, texture coordinates are inside the [0,1] range, so at least tiles that have not wrap mode `GL_REPEAT` should not be completely broken.

Yeah, this is definitely a step in the right direction to get that working.
I think the remaining brokenness might only apply to "solid" nodes because the code for them just overrides the tile material flags:

https://github.com/luanti-org/luanti/blob/486fb7cc4def696d115077497d4f0ed09ec1f7ff/src/client/content_mapblock.cpp#L429-L434

Presumably this was done as a hacky fix for everything turning broken with tileable_vertical/horizontal=false, and is no longer needed after the fixes in this PR. (The flags are regularly set here:

https://github.com/luanti-org/luanti/blob/486fb7cc4def696d115077497d4f0ed09ec1f7ff/src/nodedef.cpp#L696-L705

)

**Comment by sfan5** [comment]
While unit testing meshgen is good I think we would also benefit from having a static scene that can be rendered in CI and the screenshot compared to a known good snapshot.

**Review by Desour — APPROVED** [review]

**Comment by Desour** [comment]
I found a small issue: `glasslike` used to just take the lower 1/scale portion of the texture, now it uses the whole texture.
In practice I think this only matters for `glasslike_framed_optional` when you want to use world aligned with scale frames (does anyone do this? x)), and want to have a proper fallback for normal glasslike.

It would be nice if we could also properly support glasslike and flowingliquid, and the shiny part of glasslike_framed.

**Comment by sfan5** [comment]
Adding to next release due to high-risk bug fix (IMO).

**Comment by cx384** [comment]
According to our documentation, `align_style` is only supported for solid nodes and nodeboxes, not sure if `glasslike` and `glasslike_framed` count as solid. And `scale` is documented to work for world-aligned textures only.

If I'm not wrong, according to our code, `glasslike` does not support `align_style` and it also did not support it before this PR. So I guess it is safe to assume that `glasslike_framed_optional` does not support it, even if `glasslike_framed` (maybe undocumented) does. If we want to it change it, better support `align_style` for `glasslike` nodes, instead of introducing a save fallback. To be honest, `glasslike_framed_optional` gets rarely used and `align_style` even more rarely. Those two combined is very unlikely, so it's probably not worth supporting for now.
