### PR TITLE
Use map_compression_level_disk from minetest.conf in recompress_map_data

### LINKED ISSUE #14115: `--recompress` does not respect `map_compression_level_disk` setting
### Minetest version

```true
Minetest
```

### Active renderer

_No response_

### Irrlicht device

_No response_

### Operating system and version

Linux

### CPU model

_No response_

### GPU model

_No response_

### OpenGL version

_No response_

### Summary

Currently the `--recompress` argument does not respect the `map_compression_level_disk` setting and will just pass a hardcoded `-1` value (meaning the default compression level) when serialising mapblocks. See the following line in the `recompress_map_database` function: https://github.com/minetest/minetest/blob/master/src/main.cpp#L1282

I'm unsure if the settings load early enough to be able to read from `map_compression_level_disk`, but some way of configuring the compression level when doing `--recompress` would be useful for anyone who would want to recompress the entire database with a compression level other than the default one.

### Steps to reproduce

Get an idea to see how the filesize difference of different zstd compression levels are and go insane wondering why the database size stays the exact same, until you realise editing `map_compression_level_disk` doesn't do anything when you're using `--recompress`.

### PR DESCRIPTION
**Pull request by Linn16**
- Goal of the PR : Use the compression level set in minetest.conf during recompression.

- How does the PR work? Reads map_compression_level_disk using g_settings, applies rangelim(-1, 9) to match existing behavior.
and replaces the previously hardcoded/default -1.

- This PR fixes #14115.

## To do

This PR is Ready for Review.
While it correctly applies the map_compression_level_disk setting during recompression, this change alone does not reduce the physical size of the map.sqlite file.

I suggest that additional steps such as running a VACUUM operation on the SQLite database be considered immediately after recompression, or as part of an optional cleanup step.
In my testing, this reduced the file size by up to 1 MB.

## Script for testing

Here's the script I used to compare chunk size statistics and overall map.sqlite file size before and after recompression.

<pre> <code>
#!/bin/bash

# === CONFIG ===
WORLD="hi"
DB="../worlds/$WORLD/map.sqlite"

# === CHECK ===
if [ ! -f "$DB" ]; then
  echo "[!] Database file not found: $DB"
  exit 1
fi

echo "Initial database file size:"
du -sh "$DB"

# === MENU ===
echo "Choose what to compare:"
echo "1) Blob size stats"
echo "2) First 5 blob hashes"
echo "3) Both"
read -p "Enter option [1/2/3]: " OPTION

# === RUN ===
echo "[BEFORE --recompress]"

if [[ "$OPTION" == "1" || "$OPTION" == "3" ]]; then
  echo -e "[Blob Size Stats - BEFORE]"
  sqlite3 "$DB" "SELECT COUNT(*), AVG(LENGTH(data)), MAX(LENGTH(data)), MIN(LENGTH(data)) FROM blocks;"
fi

if [[ "$OPTION" == "2" || "$OPTION" == "3" ]]; then
  echo -e "\n[First 5 Block Hashes - BEFORE]"
  sqlite3 "$DB" <<< $'.mode list\n.headers off\nSELECT quote(data) FROM blocks LIMIT 5;'
fi

# === RUN RECOMPRESSION ===
echo -e "Running recompression with Luanti..."
./luanti --server --recompress --worldname "$WORLD"

echo "Database file size after recompression:"
du -sh "$DB"

# === AFTER ===
echo "[AFTER --recompress]"

if [[ "$OPTION" == "1" || "$OPTION" == "3" ]]; then
  echo -e "[Blob Size Stats - AFTER]"
  sqlite3 "$DB" "SELECT COUNT(*), AVG(LENGTH(data)), MAX(LENGTH(data)), MIN(LENGTH(data)) FROM blocks;"
fi

if [[ "$OPTION" == "2" || "$OPTION" == "3" ]]; then
  echo -e "[First 5 Block Hashes - AFTER]"
  sqlite3 "$DB" <<< $'.mode list\n.headers off\nSELECT quote(data) FROM blocks LIMIT 5;'
fi

</code>
</pre>

## Test procedure:

Create a new world with map_compression_level_disk = 0 set in minetest.conf.
Generate some mapblocks by walking or flying around.
Change the config to map_compression_level_disk = 9.
Run the script i shared

My observations were that he average blob size dropped, confirming that recompression with level 9 was applied correctly.
However, the file size of map.sqlite didn’t change much until a VACUUM was performed, which then released unused space.
 You can also check the logs to see which compression_level was used.

### CODE REVIEW

File: src/main.cpp [hunk 1]
```diff
@@ -1324,6 +1325,9 @@ static bool recompress_map_database(const GameParams &game_params, const Setting
 	std::cerr << std::endl;
 	db->endSave();
 
-	actionstream << "Done, " << count << " blocks were recompressed." << std::endl;
+	actionstream << "Done, " << count
+                 << " blocks were recompressed with a compression level of: "
```
Comment (sfan5) [inline src/main.cpp:1329]: I don't think the user cares about this information too much

**Comment by Linn16** [comment]
Updated, thanks for the feedback!

File: src/main.cpp [hunk 2]
```diff
@@ -1325,5 +1326,6 @@ static bool recompress_map_database(const GameParams &game_params, const Setting
 	db->endSave();
 
 	actionstream << "Done, " << count << " blocks were recompressed." << std::endl;
+
```
Comment (sfan5) [inline src/main.cpp:1329]:
```suggestion
```

**Review by sfan5 — APPROVED** [review]

**Review by Desour — APPROVED** [review]
Haven't tested. But code is fine and it's trivial enough.
