### PR TITLE
[squash merge] Main menu: Fix ContentDB aliases for games having the '_game' suffix

### LINKED ISSUE #16063: Package with _game suffix not found after rename
### Luanti version

```true
5.11
```

### Operating system and version

n/a

### CPU model

_No response_

### GPU model

_No response_

### Active renderer

_No response_

### Summary

There have been multiple reports of "The package minetest/minetest was not found" when clicking update in the content tab for Minetest Game. MTG was moved to luanti/minetest, so it appears this code isn't taking package aliases into account

### Steps to reproduce

Install MTG.
Change author=Minetest and decrement release in game.conf
Restart Luanti, click update in content tab
Also see what happens if you navigate straight to it in the CDB dialog

### PR DESCRIPTION
**Pull request by Ekdohibs**
The objective is to fix #16063, but I did not fully test it, since I have no old installation of minetest_game with contentdb. However, I did check that the alias that now exists is `["minetest/minetest"] = "luanti/minetest"`.

### CODE REVIEW

File: builtin/mainmenu/content/contentdb.lua [hunk 1]
```diff
@@ -427,11 +428,12 @@ function contentdb.set_packages_from_api(packages)
 				-- We currently don't support name changing
 				local suffix = "/" .. package.name
 				if alias:sub(-#suffix) == suffix then
-					contentdb.aliases[alias:lower()] = package.id
+					contentdb.aliases[strip_game_suffix(packages.type, alias:lower())] = package.id
 				end
 			end
 		end
 	end
+	print(dump(contentdb.aliases))
```
Comment (SmallJoker) [inline builtin/mainmenu/content/contentdb.lua:436]: Helpful for testing; but please remove it before merge.

**Review by SmallJoker — APPROVED** [review]
Works. Tested using the instructions from https://github.com/luanti-org/luanti/issues/16063#issue-3010386191.

File: builtin/mainmenu/content/contentdb.lua (hunk 1 above)
Comment (Ekdohibs) [reply builtin/mainmenu/content/contentdb.lua:436]: Oops, thanks for spotting it!

File: builtin/mainmenu/content/contentdb.lua [hunk 2]
```diff
@@ -169,15 +169,16 @@ function contentdb.get_package_by_id(id)
 	return contentdb.package_by_id[id]
 end
 
-
-function contentdb.calculate_package_id(type, author, name)
-	local id = author:lower() .. "/"
+local function strip_game_suffix(type, name)
```
Comment (grorp) [inline builtin/mainmenu/content/contentdb.lua:172]:
```suggestion

local function strip_game_suffix(type, name)
```

(readd removed spacing)

**Review by grorp — APPROVED** [review]
Looks good, haven't tested. Thank you for picking this up!
