### PR TITLE
Detect mouse moving out of inventory slot

### LINKED ISSUE #16100: GUIInventoryList hides itself during event processing when mouse is not hovering over a slot area
### Luanti version

```true
Lunati current dev commit 893a74f9d76a73ccc2c588f78443cb77447ed9f2
```

### Operating system and version

Debian mix and match:-)

### Summary

When the mouse pointer is outside the active area of an inventory slot, `GUIInventoryList` will temporarily make itself invisible to determine the component below the inventory list and propagate the event to that component (typically `GUIFormSpecMenu`):

https://github.com/luanti-org/luanti/blob/893a74f9d76a73ccc2c588f78443cb77447ed9f2/src/gui/guiInventoryList.cpp#L194

Currently it leaves itself invisible while the underlying component processses the event, causing funky behavior, especially with the `m_old_pointer` check in

https://github.com/luanti-org/luanti/blob/893a74f9d76a73ccc2c588f78443cb77447ed9f2/src/gui/guiFormSpecMenu.cpp#L4124

This prevents the formspec code to detect and act when the pointer leaves the area of a slot, which doesn't seem to cause any problems, because currently it is good enough to detect when the pointer enters the area of a slot. Still the code doesn't look like it really expects an inventory list component to suddenly become invisible causing the `getItemAtPos` call to return different results for the same position. At least this made me scratch my head quite a bit when experimenting with #14030 and #14105. Now that i finally identified the root cause I think it's worth fixing even if only to prevent others stumbling over it in the future.

### Steps to reproduce

1. Add some debugging to `GUIFormSpecMenu::OnEvent` that logs `getItemAtPos(m_old_pointer)`.
2. open the inventory of any game
3. click into any inventory slot, notice `getItemAtPos(m_old_pointer)` identifying a valid slot (the one just clicked into)
4. move the mouse into the area between two slots, notice `getItemAtPos(m_old_pointer)` suddenly becoming the invalid slot (even though `m_old_pointer` doesn't change, because this issue causes the if condition in line 4124 of guiFormSpecMenu.cpp to remain `false`)

### PR DESCRIPTION
**Pull request by j-r**
Fixes #16100.

Currently moving the mouse out of an inventory slot, e.g. into the area between two slots, will make that inventory list invisible during event processing, causing the old mouse position check in the formspec event processing code to erroneously return an invalid slot if the old position is a slot in the same inventory list, which in turn causes the event to be ignored, even though the pointed at item changes.

Fortunately it seems that currently it's good enough to detect moving the pointer into a slot - which works - and no action on moving out is needed, but that might just be an accident. At least the formspec code doesn't look like it expects a displayed invlist to suddenly go into full stealth mode.

This patch restores inv list visibility before propagating the event. Shouldn't make an observable difference currently, but allows the formspec event code to act normally on leaving a slot in the future.

I haven't found anything user observable in the event processing of `GUiFormspeMenu` that currently depends on the visibility of the inventory list, so it shouldn't  cause any issues, but one never knows:-)

### CODE REVIEW

File: src/gui/guiInventoryList.cpp [hunk 1]
```diff
@@ -203,10 +203,10 @@ bool GUIInventoryList::OnEvent(const SEvent &event)
 	if (!hovered || hovered->getID() == -1)
 		hovered = m_fs_menu;
 
-	bool ret = hovered->OnEvent(event);
-
 	IsVisible = was_visible;
 
+	bool ret = hovered->OnEvent(event);
+
 	return ret;
```
Comment (SmallJoker) [inline src/gui/guiInventoryList.cpp:210]:
```suggestion
	return hovered->OnEvent(event);
```

**Review by SmallJoker — APPROVED** [review]
I suppose this is a good catch. I never noticed any malfunction in-game but this change does make sense. The element visibility should not be faked while executing another GUI callback.

Feel free to commit or reject my suggestion.

**Comment by j-r** [comment]
Sorry, was stressed out with work. Thanks for reviewing!
